Question
========
Betrachten Sie dieses Modell, das den Zusammenhang von PS-Zahl (`hp`: horse power) und Spritverbrauch (`mpg`: miles per Gallone) untersucht (Datensatz `mtcars`):

```{r interpret-koeff-schoice-c1, message=FALSE}
data(mtcars)
library(rstanarm)
library(easystats)
lm1 <- stan_glm(mpg ~ hp, data = mtcars,
                refresh = 0)
```

```{r interpret-koeff-schoice-c2, echo=FALSE}
model_parameters(lm1,
test = NULL,
diagnostic = NULL,
priors = FALSE) |> print_md()
```


*Wie ist der Effekt von $\beta_1$ (hp) im Modell am besten zu interpretieren?*


Answerlist
----------
* Ein Auto mit einem PS mehr kommt im Mittel ca. 0,1 (0.07) Meilen weniger weit mit einer Gallone Sprit, laut diesem Modell
* Ein Auto mit einem PS mehr verbraucht 0,1 Gallonen mehr Sprit pro gefahrener Meile
* Der PS-Wert erklärt 0,1 % der Varianz im Spritverbrauch
* Bei einem PS-Wert von 0 beträgt der geschätzte mittlere Spritverbrauch 0,1 Meilen pro Gallone
* Die Korrelation zwischen PS-Zahl und Spritverbrauch beträgt 0,1


Solution
========
*hp* ($\beta_1$) ist der Regressionskoeffizient und gibt den statistischen "Effekt" der PS-Zahl auf den Spritverbrauch an. 
Vorsicht: Dieser "Effekt" darf nicht vorschnell als kausaler Effekt verstanden werden. 
Vorsichtiger wäre zu sagen: "Ein Auto mit einem PS mehr, kommt im Mittel 0,1 (0.07) Meilen weniger weit mit einer Gallone Sprit, 
laut diesem Modell." 
Den Punktschätzer des Regressionskoeffizienten kann man in der Parametertabelle in der Spalte `Median` auslesen.

Die Regressionsformel lautet: `mpg ~ hp`.




Answerlist
----------
* True
* False
* False
* False
* False


Meta-information
================
exname: interpret-koeff-schoice
extype: schoice
exsolution: 10000
exshuffle: 5
