# Definitionen


- **Kausale Abhängigkeit**: @def-abh


- **Additionssatz für disjunkte Ereignisse**: @def-add-disjunkt


- **Allgemeiner Additionssatz**: @def-additionssatz


- **Alternativhypothese (Effekthypothese)**: @def-alternativhyp


- **Binomialkoeffizient**: @def-binkoeff


- **Binomialverteilung**: @def-binvert


- **Blockieren**: @def-blocking


- **Kollision**: @def-collision


- **Konfundierungsvariable**: @def-confound


- **DAG**: @def-dag


- **Elementarereignis**: @def-defelementarereignis


- **Deskriptivstatistik**: @def-desk


- **Direkter Effekt**: @def-dir-eff


- **Effekt**: @def-effekt


- **Ereignis**: @def-ereignis


- **Ergebnisraum**: @def-Ergebnisraum


- **Perzentilintervall (PI)**: @def-eti


- **Evidenz**: @def-evidenz


- **Funktion**: @def-fun


- **Gemeinsame Wahrscheinlichkeit**: @def-gem-wskt-abh


- **Halbe Normalverteilung**: @def-halbe-nv


- **Intervalle höchster Dichte (Highest Density Intervals)**: @def-hdi


- **Hintertür**: @def-hintertuer


- **Indirekter Effekt**: @def-ind-eff


- **Stochastische Unabhängigkeit**: @def-indep


- **Indifferenzprinzip**: @def-indifferenzprinzip


- **(Populations-)Inferenzstatistik**: @def-inf


- **Kausaleffekt**: @def-kausaleffekt


- **Kettenregel**: @def-kettenregel


- **Konfidenzintervall**: @def-konfintervall


- **Likelihood**: @def-L


- **Laplace-Experimt**: @def-laplace


- **Mächtigkeit**: @def-macht


- **Mediator**: @def-mediator


- **Komplementärereignis**: @def-menge-komplement


- **Logische Differenz**: @def-mengen-diff


- **Schnittmenge von Ereignissen**: @def-mengen-schnitt


- **Vereinigung von Ereignissen**: @def-mengen-verein


- **Minimale Adjustierungsmenge **: @def-minadjust


- **Modell**: @def-model


- **Multiplikationssatz der Wahrscheinlichkeit für unabhängige Ereignisse**: @def-multsatz


- **Nachfahre**: @def-Nachfahre


- **Exakte Nullhypothese**: @def-nullhyp


- **Effektwahrscheinlichkeit**: @def-pd


- **Pfad**: @def-pfad


- **Populationsinferenz**: @def-popinf


- **Aposteriori-Verteilung**: @def-post-ver


- **Aposteriori-Verteilung**: @def-post1


- **Bedingte Wahrscheinlichkeit**: @def-pr-cond


- **Apriori-Verteilung**: @def-priori


- **Relation**: @def-relation


- **Sigma als mittleren Vorhersagefehler**: @def-sigma


- **Statistische Signifikanz**: @def-signifikanz


- **Stratifizieren**: @def-stratifizieren


- **Totaler Effekt**: @def-tce


- **Totale Wahrscheinlichkeit**: @def-totwskt


- **Unmögliches und sicheres Ereignis**: @def-unm-sich


- **Verteilungsfunktion**: @def-vert-fun


- **Verteilungsfunktion**: @def-vert-fun-stetig


- **Verteilung**: @def-verteilung


- **Vollständiges Ereignissystem**: @def-vollereignis


- **Wahrscheinlichkeitsdichte**: @def-wdichte


- **Einfache Definition von Wahrscheinlichkeit**: @def-wskt


- **Diskrete Wahrscheinlichkeitsverteilung**: @def-wvert-disk


- **Zufälliges Ereignis**: @def-zufall


- **Zufallsvariable**: @def-zufallsvariable


- **Zufallsvorgang**: @def-zufallsvorgang


- **Stetige Zufallsvariable**: @def-zv-stetig


