# Prüfung

## Prüfungleistung

Die Prüfungsleistung besteht aus einer *Open-Book-Prüfung*.

```{r hinweise, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Hinweise/Hinweise-Pruefung-Open-Book-Child.Rmd"
childtext <- readLines(url)
cat(childtext, sep="\n")
```

## Typische Fehler in der Prüfung

-   *Rechtschreibfehler* Manchmal muss man genau hinschauen, und leicht vertippt man sich: So heißt der Datensatz vielleicht `tips` und die Spalte, um die es Ihnen geht `tip` (oder war es umgekehrt?). Oder die Spalte heißt `bill_length` aber Sie schreiben `bill_lenght`.
-   *Datensatz nicht richtig importiert* Ob ein Datensatz richtig importiert ist, erkennen Sie daran, ob er im Reiter "Environment" angezeigt wird. Außerdem können Sie dort den Datensatz anklicken, um zu einer Tabellenansicht des Datensatzes zu gelangen. Dort können Sie erkennen, ob z.B. die Anzahl der Spalten korrekt ist (und nicht etwa nur eine) oder z.B. ob die Spaltennamen korrekt sind.
-   *`data(datensatz)` ohne vorher das Paket gestartet zu haben*: Mit `data(datensatz)` können Sie den Datensatz `datensatz` *nur* dann verfügbar machen, wenn das Paket, in dem `datensatz` "wohnt", mit `library(paketname)` gestartet worden ist. So "wohnt" z.B. `penguins` im Datensatz `palmerpenguins`. [Hier](https://datenwerk.netlify.app/post/pfad/pfad/) finden Sie eine Übung (und weitere Erklärung) zum Importieren von Daten in R am Beispiel des Datensatzes `penguins`.

## Hinweise zu Scheinmängeln

Immer wieder kommt es vor, dass Studierende Beanstandungen zu einer Prüfung vorbringen. Teilweise sind diese gerechtfertigt, teilweise nicht. Im Folgenden sehen Sie eine Auswahl an *nicht* gerechtfertigten Beanstandungen, also nur scheinbaren Mängeln, keine wirklichen Mängel, in einer Prüfung.

-   "Das zu wählende Vorgehen war nicht 100% klar" -- Wenn Sie der Meinung sind, dass das zu wählende Vorgehen (zum Lösen der Aufgabe) nicht komplett klar ist, treffen Sie Annahmen und weisen Sie darauf hin, dass Sie Annahmen getroffen haben. Zum anderen halten Sie sich an das Vorgehen aus dem Unterricht (bzw. den Unterlagen und der Literatur, die im Unterricht verwendet wurde). Eine andere Situation läge vor, wenn die Aufgabe nicht lösbar ist ohne weitere Angaben lösbar ist("Ist ein Effekt bei n=100 signifikant?"). Im Falle einer nicht lösbaren Aufgabe liegt fer Fehler beim Prüfer.

-   "Ich sollte einen Punkt (ein Komma) als Dezimaltrennzeichen verwenden, aber Moodle hat ein Komma (einen Punkt) verlangt!" -- Je nach Spracheinstellung in Moodle kann es sein, dass Moodle nur einen Punkt als Dezimaltrennzeichen bzw. ein Komma als Dezimaltrennzeichen verwendet. Moodle weist Sie aber darauf hin, wenn eine Zahl nicht als Zahl erkannt wird, und zwar wenn Sie zur nächsten Aufgabe geben. Sie können also ohne Probleme den Fehler korrigieren. Darüber hinaus ist bei den Prüfungshinweisen vorab auf diesen Punkt verwiesen.
