# Theoreme


- **Stochastische Abhängigkeit**: @thm-abh


- **Stochastische Abhängigkeit 2**: @thm-abh2


- **Allgemeiner Additionssatz**: @thm-add


- **Additionssatz für disjunkte Ereignisse**: @thm-add-disjunkt


- **Bayes' Theorem**: @thm-bayes1


- **Bayes' Theorem 2**: @thm-bayes3


- **Bayes' Theorem 3**: @thm-bayes3


- **Bayes' Theorem für zusammengesetzte Hypothesen**: @thm-bayes4


- **Binomialkoeffizient**: @thm-binkoeff


- **Binomialverteilung**: @thm-binomial


- **Notation für eine binomialverteilte Zufallsvariable**: @thm-binvert


- **Regression als Korrelation**: @thm-br


- **Indifferenzprinzip**: @thm-briggs


- **Evidenz**: @thm-evidenz


- **Evidenz 2**: @thm-evidenz2


- **Hypothese für ungleiche Mittelwerte**: @thm-fofra1


- **Gemeinsame Wahrscheinlichkeit**: @thm-gem-wskt-abh


- **Stochastische Unabhängigkeit**: @thm-indep


- **Symmetrie der Unabhängigkeit**: @thm-indep-symm


- **Stochastische Unabhängigkeit 2**: @thm-indep2


- **Kettenregel**: @thm-kette


- **Laplace-Experiment**: @thm-laplace


- **Lineares Modell (Regressionsgleichung)**: @thm-lm


- **Logarithmus**: @thm-logarithmus


- **Modelldefinition**: @thm-modm42


- **Nullhypothesentest**: @thm-muf-mum


- **Multiplikationssatz für unabhängige Ereignisse**: @thm-multtheorem


- **Standardisierte Posteriori-Verteilung**: @thm-post


- **Posteriori-Verteilung 2**: @thm-poststand-allgemein


- **Bedingte Wahrscheinlichkeit**: @thm-pr-cond


- **Standardnormalverteilung**: @thm-standardnormal


- **Totale Wahrscheinlichkeit**: @thm-totale-wskt


- **Unstandardisierte Posteriori-Wahrscheinlichkeit **: @thm-unpost


- **z-Transformation**: @thm-ztrans


