# Verteilungen



## Lernsteuerung


### Lernziele

Nach Absolvieren des jeweiligen Kapitel sollen folgende Lernziele erreicht sein.

Sie können ...


- den Begriff der Zufallsvariablen erläutern
- die Begriffe von Wahrscheinlichkeitsdichte und Verteilungsfunktion erläutern und anhand einfacher Beispiele ausrechnen
- den Begriff einer Gleichverteilung erläutern und einfache Fallbeispiele ausrechnen
- die Parameter einer Normalverteilung nennen und erläutern




### Prüfungsrelevanter Stoff


Lesen Sie dazu @bourier_2018, folgende Abschnitte:

- Kap. 6.1 (Zum Begriff Zufallsvariable)
- Kap. 6.3 (Stetige Zufallsvariablen)
- Kap. 7.2.1 (Gleichverteilung) und 7.2.3 (Normalverteilung)

Lösen Sie auch die Übungsaufgaben dazu.


Weitere Übungsaufgaben finden Sie im dazu gehörigen Übungsbuch, @bourier_statistik-ubungen_2022.

## Zentrale Begriffe


### Eigenschaften von Zufallsvariablen

- Zufallsvariable (random variable)
- Diskret vs. stetig
- Wahrscheinlichkeitsdichte (Dichte, (probability) density, f)
- Wahrscheinlichkeitsfunktion (kumulierte Wahrscheinlichkeit, Wahrscheinlichkeitsmasse)


### Verteilungen

- Gleichverteilung
- Normalverteilung
- Standardnormalverteilung
