<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Start:Bayes! - 12&nbsp; Kausalinferenz</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./1200-abschluss.html" rel="next">
<link href="./1000-metrische-AV.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script><link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./1100-kausal.html">Kausalität</a></li><li class="breadcrumb-item"><a href="./1100-kausal.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kausalinferenz</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Start:Bayes!</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Dunkelmodus umschalten"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Organisatorisches</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Hinweise</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0100-Pruefung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Prüfung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Wahrscheinlichkeit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0200-Inferenz.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferenz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0300-Wskt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Wahrscheinlichkeit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0400-Verteilungen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Verteilungen</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Bayes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0500-Globusversuch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Globusversuch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0600-Post.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Die Post befragen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0700-ppv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Vorhersage-Verteilung</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Lineare Modelle</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0800-gauss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Gauss-Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0900-lineare-modelle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Lineare Modelle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1000-metrische-AV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Forschungsfragen mit metrischer AV</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Kausalität</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1100-kausal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kausalinferenz</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Abschluss</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1200-abschluss.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Abschluss</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
<li>
<a href="#lernsteuerung" id="toc-lernsteuerung" class="nav-link active" data-scroll-target="#lernsteuerung"><span class="header-section-number">12.1</span> Lernsteuerung</a>
  <ul class="collapse">
<li><a href="#r-pakete" id="toc-r-pakete" class="nav-link" data-scroll-target="#r-pakete"><span class="header-section-number">12.1.1</span> R-Pakete</a></li>
  <li><a href="#lernziele" id="toc-lernziele" class="nav-link" data-scroll-target="#lernziele"><span class="header-section-number">12.1.2</span> Lernziele</a></li>
  </ul>
</li>
  <li>
<a href="#statistik-was-soll-ich-tun" id="toc-statistik-was-soll-ich-tun" class="nav-link" data-scroll-target="#statistik-was-soll-ich-tun"><span class="header-section-number">12.2</span> Statistik, was soll ich tun?</a>
  <ul class="collapse">
<li><a href="#studie-a-%C3%B6strogen" id="toc-studie-a-östrogen" class="nav-link" data-scroll-target="#studie-a-%C3%B6strogen"><span class="header-section-number">12.2.1</span> Studie A: Östrogen</a></li>
  <li><a href="#studie-b-blutdruck" id="toc-studie-b-blutdruck" class="nav-link" data-scroll-target="#studie-b-blutdruck"><span class="header-section-number">12.2.2</span> Studie B: Blutdruck</a></li>
  <li><a href="#studie-a-und-b-gleiche-daten-unterschiedliches-kausalmodell" id="toc-studie-a-und-b-gleiche-daten-unterschiedliches-kausalmodell" class="nav-link" data-scroll-target="#studie-a-und-b-gleiche-daten-unterschiedliches-kausalmodell"><span class="header-section-number">12.2.3</span> Studie A und B: Gleiche Daten, unterschiedliches Kausalmodell</a></li>
  <li><a href="#sorry-statistik-du-allein-schaffst-es-nicht" id="toc-sorry-statistik-du-allein-schaffst-es-nicht" class="nav-link" data-scroll-target="#sorry-statistik-du-allein-schaffst-es-nicht"><span class="header-section-number">12.2.4</span> Sorry, Statistik: Du allein schaffst es nicht</a></li>
  <li><a href="#vertiefung" id="toc-vertiefung" class="nav-link" data-scroll-target="#vertiefung"><span class="header-section-number">12.2.5</span> Vertiefung</a></li>
  <li><a href="#zwischenfazit" id="toc-zwischenfazit" class="nav-link" data-scroll-target="#zwischenfazit"><span class="header-section-number">12.2.6</span> Zwischenfazit</a></li>
  </ul>
</li>
  <li>
<a href="#konfundierung" id="toc-konfundierung" class="nav-link" data-scroll-target="#konfundierung"><span class="header-section-number">12.3</span> Konfundierung</a>
  <ul class="collapse">
<li><a href="#datensatz-hauspreise-im-saratoga-county" id="toc-datensatz-hauspreise-im-saratoga-county" class="nav-link" data-scroll-target="#datensatz-hauspreise-im-saratoga-county"><span class="header-section-number">12.3.1</span> Datensatz ‘Hauspreise im Saratoga County’</a></li>
  <li><a href="#immobilienpreise-in-einer-schicken-wohngegend-vorhersagen" id="toc-immobilienpreise-in-einer-schicken-wohngegend-vorhersagen" class="nav-link" data-scroll-target="#immobilienpreise-in-einer-schicken-wohngegend-vorhersagen"><span class="header-section-number">12.3.2</span> Immobilienpreise in einer schicken Wohngegend vorhersagen</a></li>
  <li><a href="#modell-1-preis-als-funktion-der-anzahl-der-zimmer" id="toc-modell-1-preis-als-funktion-der-anzahl-der-zimmer" class="nav-link" data-scroll-target="#modell-1-preis-als-funktion-der-anzahl-der-zimmer"><span class="header-section-number">12.3.3</span> Modell 1: Preis als Funktion der Anzahl der Zimmer</a></li>
  <li><a href="#don-hat-eine-idee" id="toc-don-hat-eine-idee" class="nav-link" data-scroll-target="#don-hat-eine-idee"><span class="header-section-number">12.3.4</span> Don hat eine Idee</a></li>
  <li><a href="#r-funktionen-um-beobachtungen-vorhersagen" id="toc-r-funktionen-um-beobachtungen-vorhersagen" class="nav-link" data-scroll-target="#r-funktionen-um-beobachtungen-vorhersagen"><span class="header-section-number">12.3.5</span> R-Funktionen, um Beobachtungen vorhersagen</a></li>
  <li><a href="#modell-2" id="toc-modell-2" class="nav-link" data-scroll-target="#modell-2"><span class="header-section-number">12.3.6</span> Modell 2</a></li>
  <li><a href="#die-zimmerzahl-ist-negativ-mit-dem-preis-korreliert" id="toc-die-zimmerzahl-ist-negativ-mit-dem-preis-korreliert" class="nav-link" data-scroll-target="#die-zimmerzahl-ist-negativ-mit-dem-preis-korreliert"><span class="header-section-number">12.3.7</span> Die Zimmerzahl ist negativ mit dem Preis korreliert</a></li>
  </ul>
</li>
  <li>
<a href="#kontrollieren-von-variablen" id="toc-kontrollieren-von-variablen" class="nav-link" data-scroll-target="#kontrollieren-von-variablen"><span class="header-section-number">12.4</span> Kontrollieren von Variablen</a>
  <ul class="collapse">
<li><a href="#das-hinzuf%C3%BCgen-von-pr%C3%A4diktoren-kann-die-gewichte-der-%C3%BCbrigen-pr%C3%A4diktoren-%C3%A4ndern" id="toc-das-hinzufügen-von-prädiktoren-kann-die-gewichte-der-übrigen-prädiktoren-ändern" class="nav-link" data-scroll-target="#das-hinzuf%C3%BCgen-von-pr%C3%A4diktoren-kann-die-gewichte-der-%C3%BCbrigen-pr%C3%A4diktoren-%C3%A4ndern"><span class="header-section-number">12.4.1</span> Das Hinzufügen von Prädiktoren kann die Gewichte der übrigen Prädiktoren ändern</a></li>
  </ul>
</li>
  <li>
<a href="#welches-modell-richtig-ist-kann-die-statistik-nicht-sagen" id="toc-welches-modell-richtig-ist-kann-die-statistik-nicht-sagen" class="nav-link" data-scroll-target="#welches-modell-richtig-ist-kann-die-statistik-nicht-sagen"><span class="header-section-number">12.5</span> Welches Modell richtig ist, kann die Statistik nicht sagen</a>
  <ul class="collapse">
<li><a href="#kausalmodell-f%C3%BCr-konfundierung-km1" id="toc-kausalmodell-für-konfundierung-km1" class="nav-link" data-scroll-target="#kausalmodell-f%C3%BCr-konfundierung-km1"><span class="header-section-number">12.5.1</span> Kausalmodell für Konfundierung, <code>km1</code></a></li>
  <li><a href="#m2-kontrolliert-die-konfundierungsvariable-livingarea" id="toc-m2-kontrolliert-die-konfundierungsvariable-livingarea" class="nav-link" data-scroll-target="#m2-kontrolliert-die-konfundierungsvariable-livingarea"><span class="header-section-number">12.5.2</span> <code>m2</code> kontrolliert die Konfundierungsvariable <code>livingArea</code></a></li>
  <li><a href="#konfundierer-kontrollieren" id="toc-konfundierer-kontrollieren" class="nav-link" data-scroll-target="#konfundierer-kontrollieren"><span class="header-section-number">12.5.3</span> Konfundierer kontrollieren</a></li>
  <li><a href="#m1-und-m2-passen-nicht-zu-den-daten-wenn-km1-stimmt" id="toc-m1-und-m2-passen-nicht-zu-den-daten-wenn-km1-stimmt" class="nav-link" data-scroll-target="#m1-und-m2-passen-nicht-zu-den-daten-wenn-km1-stimmt"><span class="header-section-number">12.5.4</span> <code>m1</code> und <code>m2</code> passen nicht zu den Daten, wenn <code>km1</code> stimmt</a></li>
  <li><a href="#kausalmodell-2-km2" id="toc-kausalmodell-2-km2" class="nav-link" data-scroll-target="#kausalmodell-2-km2"><span class="header-section-number">12.5.5</span> Kausalmodell 2, <code>km2</code></a></li>
  <li><a href="#dons-kausalmodell-km3" id="toc-dons-kausalmodell-km3" class="nav-link" data-scroll-target="#dons-kausalmodell-km3"><span class="header-section-number">12.5.6</span> Dons Kausalmodell, <code>km3</code></a></li>
  <li><a href="#unabh%C3%A4ngigkeiten-laut-der-kausalmodelle" id="toc-unabhängigkeiten-laut-der-kausalmodelle" class="nav-link" data-scroll-target="#unabh%C3%A4ngigkeiten-laut-der-kausalmodelle"><span class="header-section-number">12.5.7</span> Unabhängigkeiten laut der Kausalmodelle</a></li>
  </ul>
</li>
  <li>
<a href="#dags-directed-acyclic-graphs" id="toc-dags-directed-acyclic-graphs" class="nav-link" data-scroll-target="#dags-directed-acyclic-graphs"><span class="header-section-number">12.6</span> DAGs: Directed Acyclic Graphs</a>
  <ul class="collapse">
<li><a href="#leider-passen-potenziell-viele-dags-zu-einer-datenlage" id="toc-leider-passen-potenziell-viele-dags-zu-einer-datenlage" class="nav-link" data-scroll-target="#leider-passen-potenziell-viele-dags-zu-einer-datenlage"><span class="header-section-number">12.6.1</span> Leider passen potenziell viele DAGs zu einer Datenlage</a></li>
  <li><a href="#was-ist-eigentlich-eine-ursache" id="toc-was-ist-eigentlich-eine-ursache" class="nav-link" data-scroll-target="#was-ist-eigentlich-eine-ursache"><span class="header-section-number">12.6.2</span> Was ist eigentlich eine Ursache?</a></li>
  <li><a href="#zwischenfazit-1" id="toc-zwischenfazit-1" class="nav-link" data-scroll-target="#zwischenfazit-1"><span class="header-section-number">12.6.3</span> Zwischenfazit</a></li>
  <li><a href="#schoki-macht-nobelpreis" id="toc-schoki-macht-nobelpreis" class="nav-link" data-scroll-target="#schoki-macht-nobelpreis"><span class="header-section-number">12.6.4</span> Schoki macht Nobelpreis! (?)</a></li>
  </ul>
</li>
  <li>
<a href="#kollision" id="toc-kollision" class="nav-link" data-scroll-target="#kollision"><span class="header-section-number">12.7</span> Kollision</a>
  <ul class="collapse">
<li><a href="#kein-zusammenhang-von-intelligenz-und-sch%C3%B6nheit" id="toc-kein-zusammenhang-von-intelligenz-und-schönheit" class="nav-link" data-scroll-target="#kein-zusammenhang-von-intelligenz-und-sch%C3%B6nheit"><span class="header-section-number">12.7.1</span> Kein Zusammenhang von Intelligenz und Schönheit (?)</a></li>
  <li><a href="#aber-ihre-dates-sind-entweder-schlau-oder-sch%C3%B6n" id="toc-aber-ihre-dates-sind-entweder-schlau-oder-schön" class="nav-link" data-scroll-target="#aber-ihre-dates-sind-entweder-schlau-oder-sch%C3%B6n"><span class="header-section-number">12.7.2</span> Aber Ihre Dates sind entweder schlau oder schön</a></li>
  </ul>
</li>
  <li>
<a href="#dag-zur-rettung" id="toc-dag-zur-rettung" class="nav-link" data-scroll-target="#dag-zur-rettung"><span class="header-section-number">12.8</span> DAG zur Rettung</a>
  <ul class="collapse">
<li><a href="#was-ist-eine-kollision" id="toc-was-ist-eine-kollision" class="nav-link" data-scroll-target="#was-ist-eine-kollision"><span class="header-section-number">12.8.1</span> Was ist eine Kollision?</a></li>
  <li><a href="#einfaches-beispiel-zur-kollision" id="toc-einfaches-beispiel-zur-kollision" class="nav-link" data-scroll-target="#einfaches-beispiel-zur-kollision"><span class="header-section-number">12.8.2</span> Einfaches Beispiel zur Kollision</a></li>
  <li><a href="#noch-ein-einfaches-beispiel-zur-kollision" id="toc-noch-ein-einfaches-beispiel-zur-kollision" class="nav-link" data-scroll-target="#noch-ein-einfaches-beispiel-zur-kollision"><span class="header-section-number">12.8.3</span> Noch ein einfaches Beispiel zur Kollision</a></li>
  <li><a href="#durch-kontrollieren-entsteht-eine-verzerrung-bei-der-kollision" id="toc-durch-kontrollieren-entsteht-eine-verzerrung-bei-der-kollision" class="nav-link" data-scroll-target="#durch-kontrollieren-entsteht-eine-verzerrung-bei-der-kollision"><span class="header-section-number">12.8.4</span> Durch Kontrollieren entsteht eine Verzerrung bei der Kollision</a></li>
  <li><a href="#iq-fleiss-und-eignung-f%C3%BCrs-studium" id="toc-iq-fleiss-und-eignung-fürs-studium" class="nav-link" data-scroll-target="#iq-fleiss-und-eignung-f%C3%BCrs-studium"><span class="header-section-number">12.8.5</span> IQ, Fleiss und Eignung fürs Studium</a></li>
  <li><a href="#schlagzeile-schlauheit-macht-studentis-faul" id="toc-schlagzeile-schlauheit-macht-studentis-faul" class="nav-link" data-scroll-target="#schlagzeile-schlauheit-macht-studentis-faul"><span class="header-section-number">12.8.6</span> Schlagzeile “Schlauheit macht Studentis faul!”</a></li>
  <li><a href="#kollisionsverzerrung-nur-bei-stratifizierung" id="toc-kollisionsverzerrung-nur-bei-stratifizierung" class="nav-link" data-scroll-target="#kollisionsverzerrung-nur-bei-stratifizierung"><span class="header-section-number">12.8.7</span> Kollisionsverzerrung nur bei Stratifizierung</a></li>
  <li><a href="#einfluss-von-gro%C3%9Feltern-und-eltern-auf-kinder" id="toc-einfluss-von-großeltern-und-eltern-auf-kinder" class="nav-link" data-scroll-target="#einfluss-von-gro%C3%9Feltern-und-eltern-auf-kinder"><span class="header-section-number">12.8.8</span> Einfluss von Großeltern und Eltern auf Kinder</a></li>
  <li><a href="#der-gespenster-dag" id="toc-der-gespenster-dag" class="nav-link" data-scroll-target="#der-gespenster-dag"><span class="header-section-number">12.8.9</span> Der Gespenster-DAG</a></li>
  </ul>
</li>
  <li>
<a href="#die-hintert%C3%BCr-schlie%C3%9Fen" id="toc-die-hintertür-schließen" class="nav-link" data-scroll-target="#die-hintert%C3%BCr-schlie%C3%9Fen"><span class="header-section-number">12.9</span> Die Hintertür schließen</a>
  <ul class="collapse">
<li><a href="#zur-erinnerung-konfundierung" id="toc-zur-erinnerung-konfundierung" class="nav-link" data-scroll-target="#zur-erinnerung-konfundierung"><span class="header-section-number">12.9.1</span> Zur Erinnerung: Konfundierung</a></li>
  <li><a href="#gute-experimente-zeigen-den-echten-kausalen-effekt" id="toc-gute-experimente-zeigen-den-echten-kausalen-effekt" class="nav-link" data-scroll-target="#gute-experimente-zeigen-den-echten-kausalen-effekt"><span class="header-section-number">12.9.2</span> Gute Experimente zeigen den echten kausalen Effekt</a></li>
  <li><a href="#hintert%C3%BCr-schlie%C3%9Fen-auch-ohne-experimente" id="toc-hintertür-schließen-auch-ohne-experimente" class="nav-link" data-scroll-target="#hintert%C3%BCr-schlie%C3%9Fen-auch-ohne-experimente"><span class="header-section-number">12.9.3</span> Hintertür schließen auch ohne Experimente</a></li>
  <li><a href="#die-vier-atome-der-kausalanalyse" id="toc-die-vier-atome-der-kausalanalyse" class="nav-link" data-scroll-target="#die-vier-atome-der-kausalanalyse"><span class="header-section-number">12.9.4</span> Die vier Atome der Kausalanalyse</a></li>
  <li><a href="#mediation" id="toc-mediation" class="nav-link" data-scroll-target="#mediation"><span class="header-section-number">12.9.5</span> Mediation</a></li>
  </ul>
</li>
  <li>
<a href="#der-nachfahre" id="toc-der-nachfahre" class="nav-link" data-scroll-target="#der-nachfahre"><span class="header-section-number">12.10</span> Der Nachfahre</a>
  <ul class="collapse">
<li><a href="#kochrezept-zur-analyse-von-dags" id="toc-kochrezept-zur-analyse-von-dags" class="nav-link" data-scroll-target="#kochrezept-zur-analyse-von-dags"><span class="header-section-number">12.10.1</span> Kochrezept zur Analyse von DAGs</a></li>
  </ul>
</li>
  <li>
<a href="#schlie%C3%9Fen-sie-die-hintert%C3%BCr-wenn-m%C3%B6glich-bsp1" id="toc-schließen-sie-die-hintertür-wenn-möglich-bsp1" class="nav-link" data-scroll-target="#schlie%C3%9Fen-sie-die-hintert%C3%BCr-wenn-m%C3%B6glich-bsp1"><span class="header-section-number">12.11</span> Schließen Sie die Hintertür (wenn möglich)!, <code>bsp1</code></a>
  <ul class="collapse">
<li><a href="#schlie%C3%9Fen-sie-die-hintert%C3%BCr-wenn-m%C3%B6glich-bsp2" id="toc-schließen-sie-die-hintertür-wenn-möglich-bsp2" class="nav-link" data-scroll-target="#schlie%C3%9Fen-sie-die-hintert%C3%BCr-wenn-m%C3%B6glich-bsp2"><span class="header-section-number">12.11.1</span> Schließen Sie die Hintertür (wenn möglich)!, <code>bsp2</code></a></li>
  <li><a href="#implizierte-bedingte-unabh%C3%A4ngigkeiten-von-bsp2" id="toc-implizierte-bedingte-unabhängigkeiten-von-bsp2" class="nav-link" data-scroll-target="#implizierte-bedingte-unabh%C3%A4ngigkeiten-von-bsp2"><span class="header-section-number">12.11.2</span> Implizierte bedingte Unabhängigkeiten von <code>bsp2</code></a></li>
  </ul>
</li>
  <li><a href="#fazit" id="toc-fazit" class="nav-link" data-scroll-target="#fazit"><span class="header-section-number">12.12</span> Fazit</a></li>
  <li><a href="#aufgaben" id="toc-aufgaben" class="nav-link" data-scroll-target="#aufgaben"><span class="header-section-number">12.13</span> Aufgaben</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"><span class="header-section-number">12.14</span> —</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-kausal" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Kausalinferenz</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="lernsteuerung" class="level2" data-number="12.1"><h2 data-number="12.1" class="anchored" data-anchor-id="lernsteuerung">
<span class="header-section-number">12.1</span> Lernsteuerung</h2>
<section id="r-pakete" class="level3" data-number="12.1.1"><h3 data-number="12.1.1" class="anchored" data-anchor-id="r-pakete">
<span class="header-section-number">12.1.1</span> R-Pakete</h3>
<p>Für dieses Kapitel benötigen Sie folgende R-Pakete:</p>
<div class="cell" data-hash="1100-kausal_cache/html/libs_6ee6ff618f729826172b29102403ae54">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.dagitty.net">dagitty</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstanarm/">rstanarm</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/easystats/">easystats</a></span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="lernziele" class="level3" data-number="12.1.2"><h3 data-number="12.1.2" class="anchored" data-anchor-id="lernziele">
<span class="header-section-number">12.1.2</span> Lernziele</h3>
<p>Nach Absolvieren des jeweiligen Kapitels sollen folgende Lernziele erreicht sein.</p>
<p>Sie können …</p>
<ul>
<li>erklären, wann eine Kausalaussage gegeben eines DAGs berechtigt ist</li>
<li>die “Atome” der Kausalität eines DAGs benennen</li>
<li>“kausale Hintertüren” schließen</li>
</ul></section></section><section id="statistik-was-soll-ich-tun" class="level2" data-number="12.2"><h2 data-number="12.2" class="anchored" data-anchor-id="statistik-was-soll-ich-tun">
<span class="header-section-number">12.2</span> Statistik, was soll ich tun?</h2>
<section id="studie-a-östrogen" class="level3" data-number="12.2.1"><h3 data-number="12.2.1" class="anchored" data-anchor-id="studie-a-östrogen">
<span class="header-section-number">12.2.1</span> Studie A: Östrogen</h3>
<section id="medikament-einnehmen" class="level4" data-number="12.2.1.1"><h4 data-number="12.2.1.1" class="anchored" data-anchor-id="medikament-einnehmen">
<span class="header-section-number">12.2.1.1</span> Medikament einnehmen?</h4>
<p>Mit Blick auf <a href="#tbl-studie-a">Tabelle&nbsp;<span>12.1</span></a>: Was raten Sie dem Arzt? Medikament einnehmen, ja oder nein?</p>
<p></p>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-studie-a_6339e8e809fa8c461a48f30c93b609fb">
<div class="cell-output-display">
<div id="tbl-studie-a" class="anchored">

<div id="xrhqmrxhre" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#xrhqmrxhre table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#xrhqmrxhre thead, #xrhqmrxhre tbody, #xrhqmrxhre tfoot, #xrhqmrxhre tr, #xrhqmrxhre td, #xrhqmrxhre th {
  border-style: none;
}

#xrhqmrxhre p {
  margin: 0;
  padding: 0;
}

#xrhqmrxhre .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xrhqmrxhre .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#xrhqmrxhre .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xrhqmrxhre .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xrhqmrxhre .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xrhqmrxhre .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xrhqmrxhre .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xrhqmrxhre .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xrhqmrxhre .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xrhqmrxhre .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xrhqmrxhre .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xrhqmrxhre .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xrhqmrxhre .gt_spanner_row {
  border-bottom-style: hidden;
}

#xrhqmrxhre .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#xrhqmrxhre .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xrhqmrxhre .gt_from_md > :first-child {
  margin-top: 0;
}

#xrhqmrxhre .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xrhqmrxhre .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xrhqmrxhre .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#xrhqmrxhre .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#xrhqmrxhre .gt_row_group_first td {
  border-top-width: 2px;
}

#xrhqmrxhre .gt_row_group_first th {
  border-top-width: 2px;
}

#xrhqmrxhre .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xrhqmrxhre .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#xrhqmrxhre .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#xrhqmrxhre .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xrhqmrxhre .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xrhqmrxhre .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xrhqmrxhre .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#xrhqmrxhre .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xrhqmrxhre .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xrhqmrxhre .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xrhqmrxhre .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xrhqmrxhre .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xrhqmrxhre .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#xrhqmrxhre .gt_left {
  text-align: left;
}

#xrhqmrxhre .gt_center {
  text-align: center;
}

#xrhqmrxhre .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xrhqmrxhre .gt_font_normal {
  font-weight: normal;
}

#xrhqmrxhre .gt_font_bold {
  font-weight: bold;
}

#xrhqmrxhre .gt_font_italic {
  font-style: italic;
}

#xrhqmrxhre .gt_super {
  font-size: 65%;
}

#xrhqmrxhre .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#xrhqmrxhre .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#xrhqmrxhre .gt_indent_1 {
  text-indent: 5px;
}

#xrhqmrxhre .gt_indent_2 {
  text-indent: 10px;
}

#xrhqmrxhre .gt_indent_3 {
  text-indent: 15px;
}

#xrhqmrxhre .gt_indent_4 {
  text-indent: 20px;
}

#xrhqmrxhre .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<caption>Tabelle&nbsp;12.1:  <p>Daten zur Studie A</p> </caption>
  <thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Gruppe">Gruppe</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Mit Medikament">Mit Medikament</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Ohne Medikament">Ohne Medikament</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="Gruppe" class="gt_row gt_left">Männer</td>
<td headers="Mit Medikament" class="gt_row gt_left">81/87 überlebt (93%)</td>
<td headers="Ohne Medikament" class="gt_row gt_left">234/270 überlebt (87%)</td>
</tr>
<tr>
<td headers="Gruppe" class="gt_row gt_left">Frauen</td>
<td headers="Mit Medikament" class="gt_row gt_left">192/263 überlebt (73%)</td>
<td headers="Ohne Medikament" class="gt_row gt_left">55/80 überlebt (69%)</td>
</tr>
<tr>
<td headers="Gruppe" class="gt_row gt_left">Gesamt</td>
<td headers="Mit Medikament" class="gt_row gt_left">273/350 überlebt (78%)</td>
<td headers="Ohne Medikament" class="gt_row gt_left">289/350 überlebt (83%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p></p>
<p>Die Daten stammen aus einer (fiktiven) klinischen Studie, <span class="math inline">\(n=700\)</span>, hoher Qualität (Beobachtungsstudie). Bei Männern scheint das Medikament zu helfen; bei Frauen auch. Aber <em>insgesamt</em> (Summe von Frauen und Männern) <em>nicht</em>?! Was sollen wir den Arzt raten? Soll er das Medikament verschreiben? Vielleicht nur dann, wenn er das Geschlecht kennt <span class="citation" data-cites="pearl_causal_2016">(<a href="references.html#ref-pearl_causal_2016" role="doc-biblioref">Pearl, Glymour, und Jewell 2016</a>)</span>?</p>
</section><section id="kausalmodell-zur-studie-a" class="level4" data-number="12.2.1.2"><h4 data-number="12.2.1.2" class="anchored" data-anchor-id="kausalmodell-zur-studie-a">
<span class="header-section-number">12.2.1.2</span> Kausalmodell zur Studie A</h4>
<p>In Wahrheit sehe die kausale Struktur so aus: Das Geschlecht (Östrogen) hat einen Einfluss (+) auf Einnahme des Medikaments und auf Heilung (-). Das Medikament hat einen Einfluss (+) auf Heilung. Betrachtet man die Gesamt-Daten zur Heilung, so ist der Effekt von Geschlecht (Östrogen) und Medikament <em>vermengt</em> (konfundiert, confounded). Die kausale Struktur, also welche Variable beeinflusst bzw. nicht, ist in <a href="#fig-dag-studie-a">Abbildung&nbsp;<span>12.1</span></a> dargestellt.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-studie-a_d8a799fb292fa7e14ded2f3ba3f4041b">
<div class="cell-output-display">
<div id="fig-dag-studie-a" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-studie-a-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.1: Zwei direkte Effekte (gender, drug) und ein indirekter Effekt (gender über drug) auf recovery</figcaption></figure>
</div>
</div>
</div>
<p>Betrachtung der Gesamtdaten zeigt in diesem Fall einen <em>konfundierten</em> Effekt: Geschlecht konfundiert den Zusammenhang von Medikament und Heilung.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wichtig
</div>
</div>
<div class="callout-body-container callout-body">
<p>Betrachtung der Teildaten (d.h. stratifiziert pro Gruppe) zeigt in diesem Fall den wahren, kausalen Effekt. Stratifizieren ist also in diesem Fall der korrekte, richtige Weg. Achtung: Das Stratifizieren ist nicht immer und nicht automatisch die richtige Lösung. Stratifizieren bedeutet, den Gesamtdatensatz in Gruppen oder “Schichten” (“Strata”)</p>
</div>
</div>
</section></section><section id="studie-b-blutdruck" class="level3" data-number="12.2.2"><h3 data-number="12.2.2" class="anchored" data-anchor-id="studie-b-blutdruck">
<span class="header-section-number">12.2.2</span> Studie B: Blutdruck</h3>
<section id="medikament-einnehmen-1" class="level4" data-number="12.2.2.1"><h4 data-number="12.2.2.1" class="anchored" data-anchor-id="medikament-einnehmen-1">
<span class="header-section-number">12.2.2.1</span> Medikament einnehmen?</h4>
<p>Mit Blick auf <a href="#tbl-studie-b">Tabelle&nbsp;<span>12.2</span></a>: Was raten Sie dem Arzt? Medikament einnehmen, ja oder nein?</p>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-studie-b_dcc1199a8818ec5696a957cebb6e7819">
<div class="cell-output-display">
<div id="tbl-studie-b" class="anchored">

<div id="qhpfyhwahi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#qhpfyhwahi table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#qhpfyhwahi thead, #qhpfyhwahi tbody, #qhpfyhwahi tfoot, #qhpfyhwahi tr, #qhpfyhwahi td, #qhpfyhwahi th {
  border-style: none;
}

#qhpfyhwahi p {
  margin: 0;
  padding: 0;
}

#qhpfyhwahi .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#qhpfyhwahi .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#qhpfyhwahi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#qhpfyhwahi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#qhpfyhwahi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qhpfyhwahi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qhpfyhwahi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qhpfyhwahi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#qhpfyhwahi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#qhpfyhwahi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#qhpfyhwahi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#qhpfyhwahi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#qhpfyhwahi .gt_spanner_row {
  border-bottom-style: hidden;
}

#qhpfyhwahi .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#qhpfyhwahi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#qhpfyhwahi .gt_from_md > :first-child {
  margin-top: 0;
}

#qhpfyhwahi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#qhpfyhwahi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#qhpfyhwahi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#qhpfyhwahi .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#qhpfyhwahi .gt_row_group_first td {
  border-top-width: 2px;
}

#qhpfyhwahi .gt_row_group_first th {
  border-top-width: 2px;
}

#qhpfyhwahi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qhpfyhwahi .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#qhpfyhwahi .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#qhpfyhwahi .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qhpfyhwahi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qhpfyhwahi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#qhpfyhwahi .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#qhpfyhwahi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#qhpfyhwahi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qhpfyhwahi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qhpfyhwahi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qhpfyhwahi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qhpfyhwahi .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qhpfyhwahi .gt_left {
  text-align: left;
}

#qhpfyhwahi .gt_center {
  text-align: center;
}

#qhpfyhwahi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#qhpfyhwahi .gt_font_normal {
  font-weight: normal;
}

#qhpfyhwahi .gt_font_bold {
  font-weight: bold;
}

#qhpfyhwahi .gt_font_italic {
  font-style: italic;
}

#qhpfyhwahi .gt_super {
  font-size: 65%;
}

#qhpfyhwahi .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#qhpfyhwahi .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#qhpfyhwahi .gt_indent_1 {
  text-indent: 5px;
}

#qhpfyhwahi .gt_indent_2 {
  text-indent: 10px;
}

#qhpfyhwahi .gt_indent_3 {
  text-indent: 15px;
}

#qhpfyhwahi .gt_indent_4 {
  text-indent: 20px;
}

#qhpfyhwahi .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<caption>Tabelle&nbsp;12.2:  <p>Daten zur Wirksamkeit eines Medikaments (Studie B)</p> </caption>
  <thead><tr class="gt_col_headings">
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Gruppe">Gruppe</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Ohne Medikament">Ohne Medikament</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Mit Medikament">Mit Medikament</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td headers="Gruppe" class="gt_row gt_left">geringer Blutdruck</td>
<td headers="Ohne Medikament" class="gt_row gt_left">81/87 überlebt (93%)</td>
<td headers="Mit Medikament" class="gt_row gt_left">234/270 überlebt (87%)</td>
</tr>
<tr>
<td headers="Gruppe" class="gt_row gt_left">hoher Blutdruck</td>
<td headers="Ohne Medikament" class="gt_row gt_left">192/263 überlebt (73%)</td>
<td headers="Mit Medikament" class="gt_row gt_left">55/80 überlebt (69%)</td>
</tr>
<tr>
<td headers="Gruppe" class="gt_row gt_left">Gesamt</td>
<td headers="Ohne Medikament" class="gt_row gt_left">273/350 überlebt (78%)</td>
<td headers="Mit Medikament" class="gt_row gt_left">289/350 überlebt (83%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>Die Daten stammen aus einer (fiktiven) klinischen Studie, <span class="math inline">\(n=700\)</span>, hoher Qualität (Beobachtungsstudie). Bei geringem Blutdruck scheint das Medikament zu schaden. Bei hohem Blutdrck scheint das Medikamenet auch zu schaden. Aber <em>insgesamt</em> (Summe über beide Gruppe) <em>nicht</em>, da scheint es zu nutzen?! Was sollen wir den Arzt raten? Soll er das Medikament verschreiben? Vielleicht nur dann, wenn er den Blutdruck nicht kennt? <span class="citation" data-cites="pearl_causal_2016">Pearl, Glymour, und Jewell (<a href="references.html#ref-pearl_causal_2016" role="doc-biblioref">2016</a>)</span></p>
</section><section id="kausalmodell-zur-studie-b" class="level4" data-number="12.2.2.2"><h4 data-number="12.2.2.2" class="anchored" data-anchor-id="kausalmodell-zur-studie-b">
<span class="header-section-number">12.2.2.2</span> Kausalmodell zur Studie B</h4>
<p>Das Medikament hat einen (absenkenden) Einfluss auf den Blutdruck. Gleichzeitig hat das Medikament einen (toxischen) Effekt auf die Heilung. Verringerter Blutdruck hat einen positiven Einfluss auf die Heilung. Sucht man innerhalb der Leute mit gesenktem Blutdruck nach Effekten, findet man nur den toxischen Effekt: Gegeben diesen Blutdruck ist das Medikament schädlich aufgrund des toxischen Effekts. Der positive Effekt der Blutdruck-Senkung ist auf diese Art nicht zu sehen.</p>
<p>Das Kausalmodell ist in <a href="#fig-dag-studie-b">Abbildung&nbsp;<span>12.2</span></a> dargestellt.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-studie-b_94e80b58317f340ae9fccb38fbd1f138">
<div class="cell-output-display">
<div id="fig-dag-studie-b" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-studie-b-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.2: Drug hat keinen direkten, aber zwei indirekte Effekt auf recovery, einer davon ist heilsam, einer schädlich</figcaption></figure>
</div>
</div>
</div>
<p>Betrachtung der Teildaten zeigt nur den toxischen Effekt des Medikaments, nicht den nützlichen (Reduktion des Blutdrucks).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wichtig
</div>
</div>
<div class="callout-body-container callout-body">
<p>Betrachtung der Gesamtdaten zeigt in diesem Fall den wahren, kausalen Effekt. Stratifizieren wäre falsch, da dann nur der toxische Effekt, aber nicht der heilsame Effekt sichtbar wäre.</p>
</div>
</div>
</section></section><section id="studie-a-und-b-gleiche-daten-unterschiedliches-kausalmodell" class="level3" data-number="12.2.3"><h3 data-number="12.2.3" class="anchored" data-anchor-id="studie-a-und-b-gleiche-daten-unterschiedliches-kausalmodell">
<span class="header-section-number">12.2.3</span> Studie A und B: Gleiche Daten, unterschiedliches Kausalmodell</h3>
<p>Vergleichen Sie die DAGs <a href="#fig-dag-studie-a">Abbildung&nbsp;<span>12.1</span></a> und <a href="#fig-dag-studie-b">Abbildung&nbsp;<span>12.2</span></a>, die die <em>Kausalmodelle</em> der Studien A und B darstellen: Sie sind <em>unterschiedlich</em>. Aber: Die <em>Daten</em> sind <em>identisch</em>.</p>
<p>Kausale Interpretation - und damit Entscheidungen für Handlungen - war nur möglich, da das Kausalmodell bekannt ist. Die Daten alleine reichen nicht. Gut merken.</p>
</section><section id="sorry-statistik-du-allein-schaffst-es-nicht" class="level3" data-number="12.2.4"><h3 data-number="12.2.4" class="anchored" data-anchor-id="sorry-statistik-du-allein-schaffst-es-nicht">
<span class="header-section-number">12.2.4</span> Sorry, Statistik: Du allein schaffst es nicht</h3>
<p>Statistik alleine reicht nicht für Kausalschlüsse. 🧟 Statistik plus Theorie erlaubt Kausalschlüsse. 📚➕📊 🟰 🤩</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wichtig
</div>
</div>
<div class="callout-body-container callout-body">
<p>Für Entscheidungen (“Was soll ich tun?”) braucht man kausales Wissen. Kausales Wissen basiert auf einer Theorie (Kausalmodell) plus Daten.</p>
</div>
</div>
</section><section id="vertiefung" class="level3" data-number="12.2.5"><h3 data-number="12.2.5" class="anchored" data-anchor-id="vertiefung">
<span class="header-section-number">12.2.5</span> Vertiefung<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>
</h3>
<section id="studie-c-nierensteine" class="level4" data-number="12.2.5.1"><h4 data-number="12.2.5.1" class="anchored" data-anchor-id="studie-c-nierensteine">
<span class="header-section-number">12.2.5.1</span> Studie C: Nierensteine</h4>
<p>Nehmen wir an, es gibt zwei Behandlungsvarianten bei Nierensteinen, Behandlung A und B. Ärzte tendieren zu Behandlung A bei großen Steinen (die einen schwereren Verlauf haben); bei kleineren Steinen tendieren die Ärzte zu Behandlung B.</p>
<p>Sollte ein Patient, der nicht weiß, ob sein Nierenstein groß oder klein ist, die Wirksamkeit in der Gesamtpopulation (Gesamtdaten) oder in den stratifizierten Daten (Teildaten nach Steingröße) betrachten, um zu entscheiden, welche Behandlungsvariante er (oder sie) wählt?</p>
<p>Die Größe der Nierensteine hat einen Einfluss auf die Behandlungsmethode. Die Behandlung hat einen Einfluss auf die Heilung. Damit gibt es eine Mediation (“Kette”) von Größe <span class="math inline">\(\rightarrow\)</span> Behandlung <span class="math inline">\(\rightarrow\)</span> Heilung. Darüber hinaus gibt es noch einen Einfluss von Größe der Nierensteine auf die Heilung.</p>
<p>Das Kausalmodell ist in <a href="#fig-dag-studie-c">Abbildung&nbsp;<span>12.3</span></a> dargestellt; <a href="#fig-dag-studie-c2">Abbildung&nbsp;<span>12.4</span></a> visualisiert alternativ.</p>
<p>Sollte man hier <code>size</code> kontrollieren, wenn man den Kausaleffekt von <code>treatment</code> schätzen möchte? Oder lieber nicht kontrollieren?</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-studie-c_0229b5178de2f26c4dd56998548e0ba6">
<div class="cell-output-display">
<div id="fig-dag-studie-c" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-studie-c-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.3: DAG zur Nierenstein-Studie</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-studie-c2_90d1b998543d3fa3da377da62d49a696">
<div class="cell-output-display">
<div id="fig-dag-studie-c2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-studie-c2-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.4: DAG zur Nierenstein-Studie in zweiter Darstellungsform</figcaption></figure>
</div>
</div>
</div>
<p>Ja: In diesem Fall sollte man <code>size</code> kontrollieren, denn man ist am Effekt des <code>treatments</code> interessiert. Würde man nicht <code>size</code> kontrollieren, bekäme man den “vermengten” Effekt von <code>size</code> und <code>treatment</code>, also keine (belastbare) Aussage über den Effekt der Behandlung.</p>
</section><section id="mehr-beispiele" class="level4" data-number="12.2.5.2"><h4 data-number="12.2.5.2" class="anchored" data-anchor-id="mehr-beispiele">
<span class="header-section-number">12.2.5.2</span> Mehr Beispiele</h4>
<p>Nehmen Sie Bezug zu folgenden Aussagen:</p>
<blockquote class="blockquote">
<p>Studien zeigen, dass Einkommen und Heiraten (bzw. verheiratete sein) hoch korrelieren. Daher wird sich dein Einkommen erhöhen, wenn du heiratest.</p>
</blockquote>
<blockquote class="blockquote">
<p>Studien zeigen, dass Leute, die sich beeilen, zu spät zu ihrer Besprechung kommen. Daher lieber nicht beeilen, oder du kommst zu spät zu deiner Besprechung.</p>
</blockquote>
</section></section><section id="zwischenfazit" class="level3" data-number="12.2.6"><h3 data-number="12.2.6" class="anchored" data-anchor-id="zwischenfazit">
<span class="header-section-number">12.2.6</span> Zwischenfazit</h3>
<p>Bei <em>Beobachtungsstudien</em> ist aus den Daten alleine nicht herauszulesen, ob eine Intervention wirksam ist, ob es also einen kausalen Effekt von der Intervention (angenommen Ursache) auf eine AV (Wirkung) gibt. Damit ist auch nicht zu erkennen, welche Entscheidung zu treffen ist. Nur Kenntnis des Kausalmodells zusätzlich zu den Daten erlaubt, eine Entscheidung sinnvoll zu treffen.</p>
<p>Bei <em>experimentellen Daten</em> ist die Kenntnis des Kausalmodells nicht nötig (wenn das Experiment handwerklich gut gestaltet ist): Das Randomisieren der Versuchspersonen zu Gruppen und das Kontrollieren der Versuchsbedingungen sorgen dafür, dass es keine Konfundierung gibt.</p>
</section></section><section id="konfundierung" class="level2" data-number="12.3"><h2 data-number="12.3" class="anchored" data-anchor-id="konfundierung">
<span class="header-section-number">12.3</span> Konfundierung</h2>
<section id="datensatz-hauspreise-im-saratoga-county" class="level3" data-number="12.3.1"><h3 data-number="12.3.1" class="anchored" data-anchor-id="datensatz-hauspreise-im-saratoga-county">
<span class="header-section-number">12.3.1</span> Datensatz ‘Hauspreise im Saratoga County’</h3>
<p>Wir nutzen den Datensatz <a href="https://vincentarelbundock.github.io/Rdatasets/csv/mosaicData/SaratogaHouses.csv">Saratoga County</a>; s. <a href="#tbl-saratoga">Tabelle&nbsp;<span>12.3</span></a>. Hier gibt es eine <a href="https://vincentarelbundock.github.io/Rdatasets/doc/mosaicData/SaratogaHouses.html">Beschreibung des Datensatzes</a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/data-saratoga_d321ef418a3326481e8e114f9aa4c40e">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">d_path</span> <span class="op">&lt;-</span> <span class="st">"https://vincentarelbundock.github.io/Rdatasets/csv/mosaicData/SaratogaHouses.csv"</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-saratoga_f679e04d34c01a926f43796c3fd90a23">
<div class="cell-output-display">
<div id="tbl-saratoga" class="anchored">

<div data-pagedtable="false"> <div class="table-caption">Tabelle&nbsp;12.3:  <p>Saratoga-County-Datensatz</p> </div>
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["price"],"name":[1],"type":["int"],"align":["right"]},{"label":["livingArea"],"name":[2],"type":["int"],"align":["right"]},{"label":["bedrooms"],"name":[3],"type":["int"],"align":["right"]},{"label":["waterfront"],"name":[4],"type":["chr"],"align":["left"]}],"data":[{"1":"132500","2":"906","3":"2","4":"No"},{"1":"181115","2":"1953","3":"3","4":"No"},{"1":"109000","2":"1944","3":"4","4":"No"},{"1":"155000","2":"1944","3":"3","4":"No"},{"1":"86060","2":"840","3":"2","4":"No"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div>
</section><section id="immobilienpreise-in-einer-schicken-wohngegend-vorhersagen" class="level3" data-number="12.3.2"><h3 data-number="12.3.2" class="anchored" data-anchor-id="immobilienpreise-in-einer-schicken-wohngegend-vorhersagen">
<span class="header-section-number">12.3.2</span> Immobilienpreise in einer schicken Wohngegend vorhersagen</h3>
<blockquote class="blockquote">
<p>“Finden Sie den Wert meiner Immobilie heraus! Die Immobilie muss viel wert sein!”</p>
</blockquote>
<p>🧑 Das ist Don, Immobilienmogul, Auftraggeber.</p>
<blockquote class="blockquote">
<p>Das finde ich heraus. Ich mach das wissenschaftlich.</p>
</blockquote>
<p>👩 🔬 Das ist Angie, Data Scientistin.</p>
</section><section id="modell-1-preis-als-funktion-der-anzahl-der-zimmer" class="level3" data-number="12.3.3"><h3 data-number="12.3.3" class="anchored" data-anchor-id="modell-1-preis-als-funktion-der-anzahl-der-zimmer">
<span class="header-section-number">12.3.3</span> Modell 1: Preis als Funktion der Anzahl der Zimmer</h3>
<blockquote class="blockquote">
<p>“Hey Don! Mehr Zimmer, mehr Kohle!” 👩 🔬</p>
</blockquote>
<p>Modell 1 (<code>m1</code>) modelliert den Hauspreis als Funktion der Zimmerzahl, s. <a href="#fig-m1">Abbildung&nbsp;<span>12.5</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-m1_27cd804463d6baf270fed451087b9bab">
<div class="cell-output-display">
<div id="fig-m1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-m1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.5: Modell m1</figcaption></figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>“Jedes Zimmer mehr ist knapp 50 Tausend wert. Dein Haus hat einen Wert von etwa 150 Tausend Dollar, Don.”</p>
</blockquote>
<p>👩</p>
<blockquote class="blockquote">
<p>Zu wenig! 🤬</p>
</blockquote>
<p>🧑</p>
<p>Berechnen wir das Modell <code>m1</code>; der Punktschätzer des Parameters <code>bedroom</code> steht in <a href="#tbl-m1-hdi">Tabelle&nbsp;<span>12.4</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/m1_8d182f7713acc3f7dcb1776752848418">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">price</span> <span class="op">~</span> <span class="va">bedrooms</span>,</span>
<span>               refresh <span class="op">=</span> <span class="fl">0</span>,</span>
<span>               seed <span class="op">=</span> <span class="fl">42</span>,</span>
<span>               data <span class="op">=</span> <span class="va">d</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">point_estimate</span><span class="op">(</span><span class="va">m1</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m1-hdi_d63f2325db8fa40fd4dade71a4f3cb94">
<div class="cell-output-display">
<div id="tbl-m1-hdi" class="anchored">

<div data-pagedtable="false"> <div class="table-caption">Tabelle&nbsp;12.4:  <p>Parameter für m1</p> </div>
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Parameter"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Median"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Mean"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["MAP"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["Effects"],"name":[5],"type":["chr"],"align":["left"]},{"label":["Component"],"name":[6],"type":["chr"],"align":["left"]}],"data":[{"1":"(Intercept)","2":"60009.99","3":"59849.74","4":"60664.24","5":"fixed","6":"conditional","_rn_":"1"},{"1":"bedrooms","2":"48158.27","3":"48216.77","4":"47909.81","5":"fixed","6":"conditional","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div>
<p><code>point_estimates(modell)</code> gibt die Punktschätzer der Parameter eines Modells zurück, aber nicht die Schätzbereiche. Möchten Sie beides, können Sie die Funktion <code>parameters(modell)</code> nutzen.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Mit <code>estimate_predictions</code> können wir Vorhersagen berechnen (bzw. schätzen; die Vorhersagen sind ja mit Ungewissheit verbunden, daher ist “schätzen” vielleicht das treffendere Wort). <a href="#tbl-m1-pred">Tabelle&nbsp;<span>12.5</span></a> zeigt den laut <code>m1</code> vorhergesagten Hauspreis für ein Haus mit 2 Zimmern.</p>
<div class="cell" data-hash="1100-kausal_cache/html/unnamed-chunk-3_28322a3e0ebbddb7e227e3e15de62233">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dons_house</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>bedrooms <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu">estimate_prediction</span><span class="op">(</span><span class="va">m1</span>, data <span class="op">=</span> <span class="va">dons_house</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m1-pred_0ece710180cbb0babd380bdd55869945">
<div class="cell-output-display">
<div id="tbl-m1-pred" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;12.5: Vorhersage des Hauspreises für ein Haus mit 2 Zimmern</caption>
<thead><tr class="header">
<th style="text-align: left;">bedrooms</th>
<th style="text-align: right;">Predicted</th>
<th style="text-align: left;">SE</th>
<th style="text-align: left;">95% CI</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">2.00</td>
<td style="text-align: right;">1.58e+05</td>
<td style="text-align: left;">89053.60</td>
<td style="text-align: left;">(-11396.62, 3.36e+05)</td>
</tr></tbody>
</table>
</div>
<p>Variable predicted: price</p>
</div>
</div>
</section><section id="don-hat-eine-idee" class="level3" data-number="12.3.4"><h3 data-number="12.3.4" class="anchored" data-anchor-id="don-hat-eine-idee">
<span class="header-section-number">12.3.4</span> Don hat eine Idee</h3>
<blockquote class="blockquote">
<p>“Ich bau eine Mauer! Genial! An die Arbeit, Angie!” 🧑</p>
</blockquote>
<p>Don hofft, durch Verdopplung der Zimmerzahl den doppelten Verkaufspreis zu erzielen. Ob das klappt?</p>
<blockquote class="blockquote">
<p>“Das ist keine gute Idee, Don.”</p>
</blockquote>
<p>👩</p>
<p>Berechnen wir die Vorhersagen für Dons neues Haus (mit den durch Mauern halbierten Zimmern), s. <a href="#tbl-m1-pred2a">Tabelle&nbsp;<span>12.6</span></a>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell" data-hash="1100-kausal_cache/html/unnamed-chunk-5_490508ccdd62af124bd905ecadee0d69">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dons_new_house</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>bedrooms <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span>
<span><span class="fu">estimate_prediction</span><span class="op">(</span><span class="va">m1</span>, <span class="va">dons_new_house</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m1</span>, newdata <span class="op">=</span> <span class="va">dons_new_house</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m1-pred2a_783b374e23659a7be78a388f7200ed94">
<div class="cell-output-display">
<div id="tbl-m1-pred2a" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;12.6: Vorhergesagter Hauspreis laut m1 für ein Haus mit 4 Zimmern</caption>
<thead><tr class="header">
<th style="text-align: left;">bedrooms</th>
<th style="text-align: right;">Predicted</th>
<th style="text-align: left;">SE</th>
<th style="text-align: left;">95% CI</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">4.00</td>
<td style="text-align: right;">2.51e+05</td>
<td style="text-align: left;">88063.92</td>
<td style="text-align: left;">(79913.23, 4.27e+05)</td>
</tr></tbody>
</table>
</div>
<p>Variable predicted: price</p>
</div>
</div>
<p>Mit 4 statt 2 Schlafzimmer steigt der Wert auf 250k, laut <code>m1</code>, <a href="#fig-m1">Abbildung&nbsp;<span>12.5</span></a>.</p>
<blockquote class="blockquote">
<p>“Volltreffer! Jetzt verdien ich 100 Tausend mehr! 🤑 Ich bin der Größte!” 🧑</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Zur Erinnerung: “4e+05” ist die Kurzform der wissenschaftlichen Schreibweise und bedeutet: <span class="math inline">\(4 \cdot 100000 = 4\cdot10^5 = 400000\)</span></p>
</div>
</div>
</section><section id="r-funktionen-um-beobachtungen-vorhersagen" class="level3" data-number="12.3.5"><h3 data-number="12.3.5" class="anchored" data-anchor-id="r-funktionen-um-beobachtungen-vorhersagen">
<span class="header-section-number">12.3.5</span> R-Funktionen, um Beobachtungen vorhersagen</h3>
<p><code>estimate_prediction(m1, dons_new_house)</code> erstellt <em>Vorhersageintervalle</em>, berücksichtigt also <em>zwei Quellen</em> von Ungewissheit:</p>
<ul>
<li>Ungewissheiten in den Parametern (Modellkoeffizienten, <span class="math inline">\(\beta_0, \beta_1, ...\)</span>)</li>
<li>Ungewissheit im “Strukturmodell”: Wenn also z.B. in unserem Modell ein wichtiger Prädiktor fehlt, so kann die Vorhersagen nicht präzise sein. Fehler im Strukturmodell schlagen sich in breiten Schätzintervallen (bedingt durch ein großes <span class="math inline">\(\sigma\)</span>) nieder.</li>
</ul>
<p><code>estimate_expectation(m1, dons_new_house)</code> erstellt <em>Konfidenzintervalle</em>. berücksichtigt also nur <em>eine Quelle</em> von Ungewissheit:</p>
<ul>
<li>Ungewissheiten in den Parametern (Modellkoeffizienten, <span class="math inline">\(\beta_0, \beta_1, ...\)</span>)</li>
</ul>
<p>Die Schätzbereiche sind in dem Fall deutlich kleiner, s. <a href="#tbl-m1-dons-new">Tabelle&nbsp;<span>12.7</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/plot-m1-dons-new-house_583c9aa1d216cecf8a1cb6734c56867d">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">estimate_expectation</span><span class="op">(</span><span class="va">m1</span>, <span class="va">dons_new_house</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tbl-m1-dons-new" class="cell tbl-parent quarto-layout-panel anchored" data-hash="1100-kausal_cache/html/tbl-m1-dons-new_9874de785d9390979c90175f32e32d4c">
<div class="panel-caption table-caption">
<p>Tabelle&nbsp;12.7: <strong>?(caption)</strong></p>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div id="tbl-m1-dons-new-1" class="quarto-layout-cell quarto-layout-cell-subref anchored" data-ref-parent="tbl-m1-dons-new" style="flex-basis: 100.0%;justify-content: center;">
<table class="table table-sm table-striped small">
<caption>(a) Model-based Expectation</caption>
<thead><tr class="header">
<th style="text-align: left;">bedrooms</th>
<th style="text-align: right;">Predicted</th>
<th style="text-align: left;">SE</th>
<th style="text-align: left;">95% CI</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">4.00</td>
<td style="text-align: right;">2.53e+05</td>
<td style="text-align: left;">3097.48</td>
<td style="text-align: left;">(2.47e+05, 2.59e+05)</td>
</tr></tbody>
</table>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p>Variable predicted: price</p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p>Ungewissheit für die Parameter, also die Regressionsgerade, nicht die Beobachtungen</p>
</div>
</div>
</div>
</section><section id="modell-2" class="level3" data-number="12.3.6"><h3 data-number="12.3.6" class="anchored" data-anchor-id="modell-2">
<span class="header-section-number">12.3.6</span> Modell 2</h3>
<p>Berechnen wir das Modell <code>m2: price ~ bedrooms + livingArea</code>. <a href="#tbl-m2">Tabelle&nbsp;<span>12.8</span></a> gibt den Punktschätzer für die Koeffizienten wider.</p>
<div class="cell" data-hash="1100-kausal_cache/html/unnamed-chunk-7_ee08d2bcb225afea174b628bc38474f9">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">price</span> <span class="op">~</span> <span class="va">bedrooms</span> <span class="op">+</span> <span class="va">livingArea</span>, </span>
<span>               data <span class="op">=</span> <span class="va">d</span>, </span>
<span>               seed <span class="op">=</span> <span class="fl">42</span>,</span>
<span>               refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">point_estimate</span><span class="op">(</span><span class="va">m2</span>, centrality <span class="op">=</span> <span class="st">"median"</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m2_da5c890da17758766754bf0fa461d002">
<div class="cell-output-display">
<div id="tbl-m2" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;12.8: Parameter (Punktschätzer, keine Schätzung der Ungewissheit) von m2</caption>
<thead><tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Median</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">36780.69</td>
</tr>
<tr class="even">
<td style="text-align: left;">bedrooms</td>
<td style="text-align: right;">-14238.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">livingArea</td>
<td style="text-align: right;">125.41</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Was sind die Vorhersagen des Modell? <a href="#tbl-m2-pred">Tabelle&nbsp;<span>12.9</span></a> gibt Aufschluss für den laut <code>m2</code> vorhersagten Kaufpreis eines Hauses mit 4 Zimmern und 1200 Quadratfuß Wohnfläche; <a href="#tbl-m2-pred2">Tabelle&nbsp;<span>12.10</span></a> gibt die Schätzung (laut <code>m2</code>) für den Preis eines Hauses mit 2 Zimmern (und der gleichen Wohnfläche). Die Vorhersage erhält man mit dem Befehl <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code>:</p>
<div class="cell" data-hash="1100-kausal_cache/html/unnamed-chunk-9_0102294ae0895638b42c38f7bf7167e8">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m2</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>bedrooms <span class="op">=</span> <span class="fl">4</span>, livingArea <span class="op">=</span> <span class="fl">1200</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">##        1 </span></span>
<span><span class="co">## 130335.6</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m2-pred_ce543162f27915ce79c8587844960c82">
<div class="cell-output-display">
<div id="tbl-m2-pred" class="anchored">

<div data-pagedtable="false"> <div class="table-caption">Tabelle&nbsp;12.9:  <p>Vorhersage von m2 für ein Haus mit <em>4</em> Zimmern und 1200
Einheiten Wohnfläche</p> </div>
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["bedrooms"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["livingArea"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Predicted"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["SE"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["CI_low"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["CI_high"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"4","2":"1200","3":"129911.4","4":"67927.32","5":"787.9515","6":"266296.2","_rn_":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m2-pred2_aada06275c26baa2e6a5c01964c2eaa4">
<div class="cell-output-display">
<div id="tbl-m2-pred2" class="anchored">

<div data-pagedtable="false"> <div class="table-caption">Tabelle&nbsp;12.10:  <p>Vorhersage von m2 für ein Haus mit <em>2</em> Zimmern und 1200
Einheiten Wohnfläche</p> </div>
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["bedrooms"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["livingArea"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Predicted"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["SE"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["CI_low"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["CI_high"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"1200","3":"159677.7","4":"68454.54","5":"22870.85","6":"298352.2","_rn_":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div>
<p>Andere, aber ähnliche Frage: Wieviel kostet ein Haus mit sagen wir 4 Zimmer <em>gemittelt</em> über die verschiedenen Größen von <code>livingArea</code>? Stellen Sie sich alle Häuser mit 4 Zimmern vor (also mit verschiedenen Wohnflächen). Wir möchten nur wissen, was so ein Haus “im Mittel” kostet. Wir möchten also die Mittelwerte pro <code>bedroom</code> schätzen, gemittelt für jeden Wert von <code>bedroom</code> über <code>livingArea</code>. Die Ergebnisse stehen in <a href="#tbl-m2-estimate-pred2">Tabelle&nbsp;<span>12.11</span></a> und sind in <a href="#fig-m2-preds">Abbildung&nbsp;<span>12.6</span></a> visualisiert.</p>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m2-estimate-pred2_c38888873db3332e51447009b1de02e8">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">estimate_means</span><span class="op">(</span><span class="va">m2</span>, at <span class="op">=</span> <span class="st">"bedrooms"</span>, length <span class="op">=</span> <span class="fl">7</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-m2-estimate-pred2" class="anchored">

<div data-pagedtable="false"> <div class="table-caption">Tabelle&nbsp;12.11:  <p>Vorhersagen des Preises von Häusern mit verschiedener Zimmerzahl
gemittelt über die verschiedenen Werte der Wohnfläche; basierend auf
m2.</p> </div>
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["bedrooms"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Mean"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["CI_low"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["CI_high"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["pd"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"242651.0","3":"230896.5","4":"254355.9","5":"1"},{"1":"2","2":"228388.9","3":"221591.6","4":"235187.0","5":"1"},{"1":"3","2":"214204.4","3":"210892.6","4":"217394.7","5":"1"},{"1":"4","2":"199922.2","3":"194505.8","4":"205326.3","5":"1"},{"1":"5","2":"185698.8","3":"175731.2","4":"195701.2","5":"1"},{"1":"6","2":"171469.8","3":"156519.4","4":"186377.2","5":"1"},{"1":"7","2":"157206.9","3":"137108.9","4":"177051.6","5":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
</div>
<div class="cell" data-fig.asp="0.3" data-hash="1100-kausal_cache/html/fig-m2-preds_6eed27dcaee63be8a236a9d7611b8e64">
<div class="cell-output-display">
<div id="fig-m2-preds" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-m2-preds-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.6: Hauspreis als Funktion der Zimmerzahl, laut m2</figcaption></figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>“Die Zimmer zu halbieren, hat den Wert des Hauses <em>verringert</em>, Don!”</p>
</blockquote>
<p>👩</p>
<blockquote class="blockquote">
<p>“Verringert!? Weniger Geld?! Oh nein!”</p>
</blockquote>
<p>🧑</p>
</section><section id="die-zimmerzahl-ist-negativ-mit-dem-preis-korreliert" class="level3" data-number="12.3.7"><h3 data-number="12.3.7" class="anchored" data-anchor-id="die-zimmerzahl-ist-negativ-mit-dem-preis-korreliert">
<span class="header-section-number">12.3.7</span> Die Zimmerzahl ist negativ mit dem Preis korreliert</h3>
<p>… wenn man die Wohnfläche (Quadratmeter) kontrolliert, s. <a href="#fig-m2-negativ">Abbildung&nbsp;<span>12.7</span></a>.</p>
<blockquote class="blockquote">
<p><strong>“Ne-Ga-Tiv!”</strong></p>
</blockquote>
<p>👩</p>
<div id="fig-m2-negativ" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="img/hauspreis1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.7: Hauspreis stratifizieren</figcaption></figure>
</div>
<p><a href="https://github.com/sebastiansauer/QM2-Folien/blob/main/Themen/children/Hauspreis-stratifizieren.Rmd">Quellcode</a></p>
</section></section><section id="kontrollieren-von-variablen" class="level2" data-number="12.4"><h2 data-number="12.4" class="anchored" data-anchor-id="kontrollieren-von-variablen">
<span class="header-section-number">12.4</span> Kontrollieren von Variablen</h2>
<p>💡 Durch das Aufnehmen von Prädiktoren in die multiple Regression werden die Prädiktoren <em>kontrolliert</em> (adjustiert, konditioniert):</p>
<p>Die Koeffizienten einer multiplen Regression zeigen den Zusammenhang <span class="math inline">\(\beta\)</span> des einen Prädiktors mit <span class="math inline">\(y\)</span>, wenn man den (oder die) anderen Prädiktoren statistisch <em>konstant hält</em>.</p>
<p>Man nennt die Koeffizienten einer multiplen Regression daher auch <em>parzielle Regressionskoeffizienten</em>. Manchmal spricht man, eher umgangssprachlich, auch vom “Netto-Effekt” eines Prädiktors, oder davon, dass ein Prädiktor “bereinigt” wurde vom (linearen) Einfluss der anderen Prädiktoren auf <span class="math inline">\(y\)</span>.</p>
<p>Damit kann man die Regressionskoeffizienten so interpretieren, dass Sie den Effekt des Prädiktors <span class="math inline">\(x_1\)</span> auf <span class="math inline">\(y\)</span> anzeigen <em>unabhängig</em> vom Effekt der anderen Prädiktoren, <span class="math inline">\(x_2,x_3,...\)</span> auf <span class="math inline">\(y\)</span>.</p>
<p>Man kann sich dieses Konstanthalten vorstellen als eine Aufteilung in Gruppen: Der Effekt eines Prädiktors <span class="math inline">\(x_1\)</span> wird für jede Ausprägung (Gruppe) des Prädiktors <span class="math inline">\(x_2\)</span> berechnet.</p>
<section id="das-hinzufügen-von-prädiktoren-kann-die-gewichte-der-übrigen-prädiktoren-ändern" class="level3" data-number="12.4.1"><h3 data-number="12.4.1" class="anchored" data-anchor-id="das-hinzufügen-von-prädiktoren-kann-die-gewichte-der-übrigen-prädiktoren-ändern">
<span class="header-section-number">12.4.1</span> Das Hinzufügen von Prädiktoren kann die Gewichte der übrigen Prädiktoren ändern</h3>
<blockquote class="blockquote">
<p>Aber welche und wie viele Prädiktoren soll ich denn jetzt in mein Modell aufnehmen?! Und welches Modell ist jetzt richtig?!</p>
</blockquote>
<p>🧑</p>
<blockquote class="blockquote">
<p>Leider kann die Statistik keine Antwort darauf geben.</p>
</blockquote>
<p>👩</p>
<blockquote class="blockquote">
<p>Wozu ist sie dann gut?!</p>
</blockquote>
<p>🧑</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wichtig
</div>
</div>
<div class="callout-body-container callout-body">
<p>In Beobachtungsstudien hilft nur ein (korrektes) Kausalmodell. Ohne Kausalmodell ist es nutzlos, die Regressionskoeffizienten (oder eine andere Statistik) zur Erklärung der Ursachen heranzuziehen: Die Regressionskoeffizienten können sich wild ändern, wenn man Prädiktoren hinzufügt oder weglässt. Es können sich sogar die Vorzeichen der Regressionsgewichte ändern; in dem Fall spricht man von einem Simpson-Paradox.</p>
</div>
</div>
</section></section><section id="welches-modell-richtig-ist-kann-die-statistik-nicht-sagen" class="level2" data-number="12.5"><h2 data-number="12.5" class="anchored" data-anchor-id="welches-modell-richtig-ist-kann-die-statistik-nicht-sagen">
<span class="header-section-number">12.5</span> Welches Modell richtig ist, kann die Statistik nicht sagen</h2>
<blockquote class="blockquote">
<p>Often people want statistical modeling to do things that statical modeling cannot do. For example, we’d like to know wheter an effect is “real” or rather spurios. Unfortunately, modeling merely quantifies uncertainty in the precise way that the model understands the problem. Usually answers to lage world questions about truth and causation depend upon information not included in the model. For example, any observed correlation between an outcome and predictor could be eliminated or reversed once another predictor is added to the model. But if we cannot think of the right variable, we might never notice. Therefore all statical models are vulnerable to and demand critique, regardless of the precision of their estimates and apparaent accuracy of their predictions. Rounds of model criticism and revision embody the real tests of scientific hypotheses. A true hypothesis will pass and fail many statistical “tests” on its way to acceptance.</p>
</blockquote>
<p><span class="citation" data-cites="mcelreath_statistical_2020">McElreath (<a href="references.html#ref-mcelreath_statistical_2020" role="doc-biblioref">2020</a>)</span>, S. 139</p>
<section id="kausalmodell-für-konfundierung-km1" class="level3" data-number="12.5.1"><h3 data-number="12.5.1" class="anchored" data-anchor-id="kausalmodell-für-konfundierung-km1">
<span class="header-section-number">12.5.1</span> Kausalmodell für Konfundierung, <code>km1</code>
</h3>
<p>Das Kausalmodell <code>km1</code> ist in <a href="#fig-km1">Abbildung&nbsp;<span>12.8</span></a> dargestellt; vgl. <a href="#fig-m2-negativ">Abbildung&nbsp;<span>12.7</span></a>.</p>
<div class="cell" data-fig.asp="0.33" data-hash="1100-kausal_cache/html/fig-km1_d596c335dece3f87eef16e8138780042">
<div class="cell-output-display">
<div id="fig-km1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-km1-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.8: Kausalmodell km1 - Eine Erklärung (von mehreren) für m1 bzw. die Daten, die m1 zugrunde liegen</figcaption></figure>
</div>
</div>
</div>
<p>Wenn dieses Kausalmodell stimmt, findet man eine <em>Scheinkorrelation</em> zwischen <code>price</code> und <code>bedrooms</code>.</p>
<p>Eine Scheinkorrelation ist ein Zusammenhang, der <em>nicht</em> auf eine kausalen Einfluss beruht.</p>
<p><code>d_connected</code> heißt, dass die betreffenden Variablen “verbunden” sind durch einen gerichteten (<code>d</code> wie directed) Pfad, durch den die Assoziation (Korrelation) wie durch einen Fluss fließt 🌊. <code>d_separated</code> heißt, dass sie nicht <code>d_connected</code> sind.</p>
</section><section id="m2-kontrolliert-die-konfundierungsvariable-livingarea" class="level3" data-number="12.5.2"><h3 data-number="12.5.2" class="anchored" data-anchor-id="m2-kontrolliert-die-konfundierungsvariable-livingarea">
<span class="header-section-number">12.5.2</span> <code>m2</code> kontrolliert die Konfundierungsvariable <code>livingArea</code>
</h3>
<p>Wenn das Kausalmodell stimmt, dann zeigt <code>m2</code> den kausalen Effekt von <code>livingArea</code>.</p>
<blockquote class="blockquote">
<p>Was tun wir jetzt bloß?! Oh jeh!</p>
</blockquote>
<p>🧑</p>
<blockquote class="blockquote">
<p>Wir müssen die Konfundierungsvariable kontrollieren.</p>
</blockquote>
<p>👩</p>
<p><a href="#fig-km1-controlled">Abbildung&nbsp;<span>12.9</span></a> zeigt, dass <code>bedrooms</code> und <code>price</code> <em>unkorreliert</em> werden (<code>d_separated</code>), wenn man <code>living area</code> kontrolliert.</p>
<div class="cell" data-fig.asp="0.45" data-hash="1100-kausal_cache/html/fig-km1-controlled_bf5152d3065ddeca70fc18f062a22d13">
<div class="cell-output-display">
<div id="fig-km1-controlled" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-km1-controlled-1.png" class="img-fluid figure-img" width="2700"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.9: Durch Kontrolle von living area wird die Assoziation von price und bedrooms aufgehoben.</figcaption></figure>
</div>
</div>
</div>
<p>Durch das Kontrollieren (“adjustieren”), sind <code>bedrooms</code> und <code>price</code> nicht mehr korreliert, nicht mehr <code>d_connected</code>, sondern jetzt <code>d_separeted</code>.</p>
</section><section id="konfundierer-kontrollieren" class="level3" data-number="12.5.3"><h3 data-number="12.5.3" class="anchored" data-anchor-id="konfundierer-kontrollieren">
<span class="header-section-number">12.5.3</span> Konfundierer kontrollieren</h3>
<p>Gehen wir in diesem Abschnitt davon aus, dass <code>km1</code> richtig ist.</p>
<p><em>Ohne</em> Kontrollieren der Konfundierungsvariablen: Regressionsmodell <code>y ~ x</code>, <a href="#fig-p-konf1">Abbildung&nbsp;<span>12.10</span></a>, links: Es wird (fälschlich) eine Korrelation zwischen <code>x</code> und <code>y</code> angezeigt: Scheinkorrelation. <em>Mit</em> Kontrollieren der Konfundierungsvariablen: Regressionsmodell <code>y ~ x + group</code>, <a href="#fig-p-konf1">Abbildung&nbsp;<span>12.10</span></a>, rechts.</p>
<div id="fig-p-konf1" class="cell quarto-layout-panel" data-hash="1100-kausal_cache/html/fig-p-konf1_8479c21619c9acb67dd36e9e60acec9d">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-p-konf1-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-p-konf1-1.png" class="img-fluid figure-img" data-ref-parent="fig-p-konf1" width="672"></p>
<figcaption class="figure-caption">(a) Ohne Kontrolle der Konfundierungsvariablen: Konfundierung tritt auf.</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-p-konf1-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-p-konf1-2.png" class="img-fluid figure-img" data-ref-parent="fig-p-konf1" width="672"></p>
<figcaption class="figure-caption">(b) Mit Kontrolle der Konfundierungsvariablen: Konfundierung tritt nicht auf.</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Abbildung&nbsp;12.10: Konfundierung von y und x!</figcaption><p></p>
</figure>
</div>
<p><a href="#fig-p-konf1">Abbildung&nbsp;<span>12.10</span></a>, rechts, zeigt korrekt, dass es keine Korrelation zwischen <code>x</code> und <code>y</code> gibt, wenn <code>group</code> kontrolliert wird. Außerdem sieht man im rechten Teildiagramm, dass es ein Kontrollieren der Variable <code>group</code> durch Aufnahme als Prädiktor in die Regressionsgleichung einem Stratifizieren entspricht (getrennte Berechnung der Regressionsgerade pro Gruppe).</p>
<p><a href="https://github.com/sebastiansauer/QM2-Folien/blob/main/Themen/children/Konfundierer-kontrollieren.Rmd">Quellcode</a></p>
</section><section id="m1-und-m2-passen-nicht-zu-den-daten-wenn-km1-stimmt" class="level3" data-number="12.5.4"><h3 data-number="12.5.4" class="anchored" data-anchor-id="m1-und-m2-passen-nicht-zu-den-daten-wenn-km1-stimmt">
<span class="header-section-number">12.5.4</span> <code>m1</code> und <code>m2</code> passen nicht zu den Daten, wenn <code>km1</code> stimmt</h3>
<p>Laut <code>km1</code> dürfte es keine Assoziation (Korrelation) zwischen <code>bedrooms</code> und <code>price</code> geben, wenn man <code>livingArea</code> kontrolliert, wie in <a href="#fig-km1">Abbildung&nbsp;<span>12.8</span></a> dargestellt. Es gibt aber noch eine Assoziation zwischen <code>bedrooms</code> und <code>price</code> geben, wenn man <code>livingArea</code> kontrolliert. Daher sind sowohl <code>m1</code> und <code>m2</code> nicht mit dem Kausalmodell <code>km1</code> vereinbar.</p>
</section><section id="kausalmodell-2-km2" class="level3" data-number="12.5.5"><h3 data-number="12.5.5" class="anchored" data-anchor-id="kausalmodell-2-km2">
<span class="header-section-number">12.5.5</span> Kausalmodell 2, <code>km2</code>
</h3>
<p>Unser Modell <code>m2</code> sagt uns, dass beide Prädiktoren jeweils einen eigenen Beitrag zur Erklärung der AV haben.</p>
<p>Daher könnte das folgende Kausalmodell, <code>km2</code> besser passen.</p>
<p>In diesem Modell gibt es eine <em>Wirkkette</em>: <span class="math inline">\(a \rightarrow b \rightarrow p\)</span>.</p>
<p>Insgesamt gibt es zwei Kausaleinflüsse von <code>a</code> auf <code>p</code>: - <span class="math inline">\(a \rightarrow p\)</span> - <span class="math inline">\(a \rightarrow b \rightarrow p\)</span></p>
<p>Man nennt die mittlere Variable einer Wirkkette auch einen <em>Mediator</em> und den Pfad von der UV (<code>a</code>) über den Mediator (<code>b</code>) zur AV (<code>p</code>) auch <em>Mediation</em>, s. <a href="#fig-m1-mediation">Abbildung&nbsp;<span>12.11</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-m1-mediation_487852e9e1bce452796d6ffc17f74f61">
<div class="cell-output-display">
<div id="fig-m1-mediation" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-m1-mediation-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.11: Der Effekt von livingArea wird über den Mediator bedrooms auf price vermittelt.</figcaption></figure>
</div>
</div>
</div>
</section><section id="dons-kausalmodell-km3" class="level3" data-number="12.5.6"><h3 data-number="12.5.6" class="anchored" data-anchor-id="dons-kausalmodell-km3">
<span class="header-section-number">12.5.6</span> Dons Kausalmodell, <code>km3</code>
</h3>
<p>So sieht Dons Kausalmodell aus, s. <a href="#fig-km3">Abbildung&nbsp;<span>12.12</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-km3_f3206f682f169c6f5d2934d2eb4beb2b">
<div class="cell-output-display">
<div id="fig-km3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-km3-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.12: Dons Kausalmodell</figcaption></figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>“Ich glaube aber an mein Kausalmodell. Mein Kausalmodell ist das größte! Alle anderen Kausalmodelle sind ein Disaster!”</p>
</blockquote>
<p>🧑</p>
<p></p>
<blockquote class="blockquote">
<p>“Don, nach deinem Kausalmodell müssten <code>bedrooms</code> und <code>livingArea</code> unkorreliert sein. Sind sie aber nicht.”</p>
</blockquote>
<p>🧑</p>
<p>Rechne doch selber die Korrelation aus, Don:</p>
<blockquote class="blockquote">
<p>“Äh, wie ging das nochmal?”</p>
</blockquote>
<p>🧑</p>
<p>So könntest du das rechnen, Don: <code>correlation(d, select = c("bedrooms", "livingArea"))</code>. Oder z.B. so:</p>
<div class="cell" data-hash="1100-kausal_cache/html/unnamed-chunk-13_92b7be68840e03fc243bf41cf36a04c5">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dons_r</span> <span class="op">&lt;-</span> <span class="va">d</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">bedrooms</span>, <span class="va">livingArea</span><span class="op">)</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Die Korrelation liegt also bei 0.66</p>
<blockquote class="blockquote">
<p>“Bitte, gerne hab ich dir geholfen, Don.”</p>
</blockquote>
<p>👩</p>
</section><section id="unabhängigkeiten-laut-der-kausalmodelle" class="level3" data-number="12.5.7"><h3 data-number="12.5.7" class="anchored" data-anchor-id="unabhängigkeiten-laut-der-kausalmodelle">
<span class="header-section-number">12.5.7</span> Unabhängigkeiten laut der Kausalmodelle</h3>
<p><code>km1</code>: <code>b</code>: bedrooms, <code>p</code>: price, <code>a</code> area (living area), s. <a href="#fig-km1">Abbildung&nbsp;<span>12.8</span></a>.</p>
<p>Das Kausalmodell <code>km1</code> behauptet: <span class="math inline">\(b \perp \!\!\! \perp p \, |\, a\)</span>: <code>bedrooms</code> sind unabhängig von <code>price</code>, wenn man <code>livingArea</code> kontrolliert.</p>
<p><em>Kontrollieren</em> einer Variable <span class="math inline">\(Z\)</span> erreicht man auf einfache Art, indem man sie in zusätzlich zur vermuteten Ursache <span class="math inline">\(X\)</span> in die Regressionsgleichung mit aufnimmt, also <code>y ~ x + z</code>.</p>
<p>Aber diese behauptete Unabhängigkeit findet sich <em>nicht</em> in den Daten wieder, s. <a href="#tbl-m2">Tabelle&nbsp;<span>12.8</span></a>. Also: ⛈️ Passt nicht zu den Daten!</p>
<p><code>km2</code> <code>b</code>: bedrooms, <code>p</code>: price, <code>a</code> area (living area), s. <a href="#fig-m1-mediation">Abbildung&nbsp;<span>12.11</span></a>.</p>
<p>Das Kausalmodell <code>km2</code> postuliert <em>keine</em> Unabhängigkeiten: Laut <code>km2</code>sind alle Variablen des Modells miteinander assoziiert (korreliert).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ein Modell, in dem alle Variablen miteinander korreliert sind, nennt man auch <em>satuiert</em> oder saturiertes Modell. So ein Modell ist empirisch <em>schwach</em>. Denn: Behauptet ein Modell, dass die Korrelation zwischen zwei Variablen irgendeinen Wert zwischen -1 und +1 beträgt (nur nicht exakt Null), so ist das eine sehr schwache Aussage (und kaum zu falsifizieren). So ein Modell ist wissenschaftlich wenig wert. Das ist so ähnlich wie ein Modell, das voraussagt, dass es morgen irgendeine Temperatur hat zwischen -30 und +30 Grad (nur nicht exakt Null). Trifft diese Temperaturvorhersage ein, so werden wir nicht gerade beeindruckt sein. 🥱</p>
</div>
</div>
<p>Fazit: <code>km2</code> passt zu den Daten, aber wir sind nicht gerade beeindruckt vom Modell.</p>
<p><code>km3</code>: <code>b</code>: bedrooms, <code>p</code>: price, <code>a</code> area (living area), s. <a href="#fig-km3">Abbildung&nbsp;<span>12.12</span></a>.</p>
<p><span class="math inline">\(b \perp \!\!\! \perp a\)</span>: <code>bedrooms</code> sind unabhängig von <code>livingArea</code> (<code>a</code>)</p>
<p>⛈️ <code>km3</code> passt nicht zu den Daten/zum Modell!</p>
</section></section><section id="dags-directed-acyclic-graphs" class="level2" data-number="12.6"><h2 data-number="12.6" class="anchored" data-anchor-id="dags-directed-acyclic-graphs">
<span class="header-section-number">12.6</span> DAGs: Directed Acyclic Graphs</h2>
<p>Was sind DAGs? Wir haben in diesem Kapitel schon viele Beispiele gesehen, z.B. <a href="#fig-km3">Abbildung&nbsp;<span>12.12</span></a>.</p>
<ul>
<li><p>DAGs sind eine bestimmte Art von Graphen zur Analyse von Kausalstrukturen.</p></li>
<li><p>Ein <em>Graph</em> besteht aus Knoten (Variablen) und Kanten (Linien), die die Knoten verbinden.</p></li>
<li><p>DAGs sind <em>gerichtet</em>; die Pfeile zeigen immer in eine Richtung (und zwar von Ursache zu Wirkung).</p></li>
<li><p>DAGs sind <em>azyklisch</em>; die Wirkung eines Knoten darf nicht wieder auf ihn zurückführen.</p></li>
<li><p>Ein <em>Pfad</em> ist ein Weg durch den DAG, von Knoten zu Knoten über die Kanten, unabhängig von der Pfeilrichtung.</p></li>
</ul>
<p>Der DAG von <code>km1</code> ist in <a href="#fig-km1">Abbildung&nbsp;<span>12.8</span></a> zu sehen.</p>
<section id="leider-passen-potenziell-viele-dags-zu-einer-datenlage" class="level3" data-number="12.6.1"><h3 data-number="12.6.1" class="anchored" data-anchor-id="leider-passen-potenziell-viele-dags-zu-einer-datenlage">
<span class="header-section-number">12.6.1</span> Leider passen potenziell viele DAGs zu einer Datenlage</h3>
<p><code>b</code>: bedrooms, <code>p</code>: price, <code>a</code> area (living area)</p>
<p>Ja, der Job der Wissenschaft ist kein Zuckerschlecken. Aber wenn es einfach wäre, die Kausalstruktur der Phänomene zu entdecken, wären sie längst erkannt, und alle Probleme der Menschheit gelöst.</p>
<p>In <a href="#fig-kms">Abbildung&nbsp;<span>12.13</span></a> sind mögliche Kausalmodelle für Dons Studie dargestellt.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-kms_3a0dcceb43c8e93a36d9176400f30b87">
<div class="cell-output-display">
<div id="fig-kms" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-kms-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.13: Kausalmodelle, die potenziell geeignet sind für Dons Fragestellung</figcaption></figure>
</div>
</div>
</div>
<p>Alle diese DAgs in <a href="#fig-km1">Abbildung&nbsp;<span>12.8</span></a> haben die <em>gleichen</em> Implikationen hinsichtlich der (Un-)Abhängigkeiten zwischen der Variablen. Wir können also leider empirisch nicht bestimmen, welcher der DAGs der richtige ist. Um den richtigen DAG zu identifizieren, bräuchten wir z.B. einen reichhaltigeren DAG, also mit mehr Variablen.</p>
</section><section id="was-ist-eigentlich-eine-ursache" class="level3" data-number="12.6.2"><h3 data-number="12.6.2" class="anchored" data-anchor-id="was-ist-eigentlich-eine-ursache">
<span class="header-section-number">12.6.2</span> Was ist eigentlich eine Ursache?</h3>
<p>Etwas verursachen kann man auch (hochtrabend) als “Kausation” bezeichnen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Weiß man, was die Wirkung <span class="math inline">\(W\)</span> einer Handlung <span class="math inline">\(H\)</span> (Intervention) ist, so hat man <span class="math inline">\(H\)</span> als Ursache von <span class="math inline">\(W\)</span> erkannt.</p>
</div>
</div>
<p><span class="citation" data-cites="mcelreath_statistical_2020">McElreath (<a href="references.html#ref-mcelreath_statistical_2020" role="doc-biblioref">2020</a>)</span></p>
<p>Viele Menschen denken - fälschlich - dass Korrelation Kausation bedeuten muss, s. <a href="#fig-xkcd-causation">Abbildung&nbsp;<span>12.14</span></a>.</p>
<div class="cell" data-layout-align="center" data-hash="1100-kausal_cache/html/fig-xkcd-causation_f61a1a266b88aa4e99c9c42fff8502d2">
<div class="cell-output-display">
<div id="fig-xkcd-causation" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="img/correlation.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.14: xkcd zum Thema Kausation</figcaption></figure>
</div>
</div>
</div>
<p><a href="https://xkcd.com/552/">Quelle</a> und <a href="https://www.explainxkcd.com/wiki/index.php/552:_Correlation">Erklärung</a></p>
</section><section id="zwischenfazit-1" class="level3" data-number="12.6.3"><h3 data-number="12.6.3" class="anchored" data-anchor-id="zwischenfazit-1">
<span class="header-section-number">12.6.3</span> Zwischenfazit</h3>
<p>Sind zwei Variablen korreliert (abhängig, assoziiert), so kann es dafür zwei Gründe geben:</p>
<ul>
<li>Kausaler Zusammenhang</li>
<li>Nichtkausaler Zusammenhang (“Scheinkorrelation”)</li>
</ul>
<p>Eine mögliche Ursache einer Scheinkorrelation ist Konfundierung.</p>
<p>Konfundierung kann man entdecken, indem man die angenommene Konfundierungsvariable kontrolliert (adjustiert), z.B. indem man ihn als Prädiktor in eine Regression aufnimmt.</p>
<p>Ist die Annahme einer Konfundierung korrekt, so löst sich der Scheinzusammenhang nach dem Adjustieren auf.</p>
<p>Löst sich der Scheinzusammenhang nicht auf, sondern drehen sich die Vorzeichen der Zusammenhänge nach Adjustieren um, so spricht man einem <em>Simpson-Paradox</em>.</p>
<p>Die Daten alleine können nie sagen, welches Kausalmodell der Fall ist in einer Beobachtungsstudie. Fachwissen (inhaltliches wissenschaftliches Wissen) ist nötig, um DAGs auszuschließen.</p>
</section><section id="schoki-macht-nobelpreis" class="level3" data-number="12.6.4"><h3 data-number="12.6.4" class="anchored" data-anchor-id="schoki-macht-nobelpreis">
<span class="header-section-number">12.6.4</span> Schoki macht Nobelpreis! (?)</h3>
<p>🏎️ Vertiefung 🏎️</p>
<p>Eine Studie fand eine starke Korrelation, <span class="math inline">\(r=0.79\)</span> zwischen (Höhe des) Schokoladenkonsums eines Landes und (Anzahl der) Nobelpreise eines Landes <span class="citation" data-cites="messerli_chocolate_2012">(<a href="references.html#ref-messerli_chocolate_2012" role="doc-biblioref">Messerli 2012</a>)</span>, s. <a href="#fig-schoki">Abbildung&nbsp;<span>12.15</span></a>.</p>
<div class="cell" data-layout-align="center" data-hash="1100-kausal_cache/html/fig-schoki_3c2236eba1380c1a17541a8a9de439a4">
<div class="cell-output-display">
<div id="fig-schoki" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="img/correlation_550.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.15: Je mehr Schoki, desto mehr Nobelpreise</figcaption></figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wichtig
</div>
</div>
<div class="callout-body-container callout-body">
<p>Korrelation ungleich Kausation! Korrelation <em>kann</em> bedeuten, dass eine Kausation vorliegt, aber es muss auch nicht sein, dass Kausation vorliegt. Liegt Korrelation ohne Kausation vor, so spricht man von einer <em>Scheinkorrelation</em>. Um Scheinkorrelation von echter Assoziation (auf Basis von Kausation) abzugrenzen, muss man die Kausalmodelle überprüfen, so wie wir das hier tun.</p>
</div>
</div>
<p>Der “Schoki-DAG” in <a href="#fig-schoki-dag">Abbildung&nbsp;<span>12.16</span></a> zeigt den DAG für das Schokoloaden-Nobelpreis-Modell.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-schoki-dag_29f186447bd471d29ad2e7ae93b74925">
<div class="cell-output-display">
<div id="fig-schoki-dag" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-schoki-dag-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.16: Macht Schokolade Nobelpreise?</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="kollision" class="level2" data-number="12.7"><h2 data-number="12.7" class="anchored" data-anchor-id="kollision">
<span class="header-section-number">12.7</span> Kollision</h2>
<section id="kein-zusammenhang-von-intelligenz-und-schönheit" class="level3" data-number="12.7.1"><h3 data-number="12.7.1" class="anchored" data-anchor-id="kein-zusammenhang-von-intelligenz-und-schönheit">
<span class="header-section-number">12.7.1</span> Kein Zusammenhang von Intelligenz und Schönheit (?)</h3>
<p>Gott ist gerecht (?)</p>
<p>Zumindest findet sich in folgenden Daten kein Zusammenhang von Intelligenz (<code>talent</code>) und Schönheit (<code>looks</code>), wie <a href="#fig-iq-schoen">Abbildung&nbsp;<span>12.17</span></a> illustriert. Für geringe Intelligenzwerte gibt es eine breites Spektrum von Schönheitswerten und für hohe Intelligenzwerte sieht es genauso aus.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-iq-schoen_06e07a437e4e0523baf757378dc1c56c">
<div class="cell-output-display">
<div id="fig-iq-schoen" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-iq-schoen-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.17: Kein Zusammenhang von Intelligenz und Schönheit in den Daten</figcaption></figure>
</div>
</div>
</div>
<p><a href="https://twitter.com/TheTweetOfGod/status/1462594155176026123">Gott ist gerecht (?)</a></p>
</section><section id="aber-ihre-dates-sind-entweder-schlau-oder-schön" class="level3" data-number="12.7.2"><h3 data-number="12.7.2" class="anchored" data-anchor-id="aber-ihre-dates-sind-entweder-schlau-oder-schön">
<span class="header-section-number">12.7.2</span> Aber Ihre Dates sind entweder schlau oder schön</h3>
<p>Seltsamerweise beobachten Sie, dass die Menschen, die Sie daten (Ihre Dates), entweder schön sind oder schlau - aber seltens beides gleichzeitig (schade), s. <a href="#fig-dates-beauty">Abbildung&nbsp;<span>12.18</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dates-beauty_f415ff992584605cf5be6855a8ce9457">
<div class="cell-output-display">
<div id="fig-dates-beauty" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dates-beauty-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.18: Ihre Datingpartner sind komischerweise entweder schlau oder schön (aber nicht beides), zumindest in der Tendenz.</figcaption></figure>
</div>
</div>
</div>
<p>Wie kann das sein?</p>
</section></section><section id="dag-zur-rettung" class="level2" data-number="12.8"><h2 data-number="12.8" class="anchored" data-anchor-id="dag-zur-rettung">
<span class="header-section-number">12.8</span> DAG zur Rettung</h2>
<p>🦹 🦸</p>
<p>Der DAG in <a href="#fig-coll1-dag">Abbildung&nbsp;<span>12.19</span></a> bietet eine rettende Erklärung.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-coll1-dag_735eb80cf90dfef8dad6edefd08e9b2d">
<div class="cell-output-display">
<div id="fig-coll1-dag" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-coll1-dag-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.19: Date als gemeinsame Wirkung von Schönheit und Intelligenz. Stratifiziert man die gemeinsame Wirkung (dates), so kommt es zu einer Scheinkorrelation zwischen Schönheit und Intelligenz.</figcaption></figure>
</div>
</div>
</div>
<p>Eine ähnliche Visualisierung des gleichen Sachverhalts zeigt <a href="#fig-coll2-dag">Abbildung&nbsp;<span>12.20</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-coll2-dag_b5a0bae7ed9727ed731cd75f10ecb91a">
<div class="cell-output-display">
<div id="fig-coll2-dag" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-coll2-dag-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.20: Durch Kontrolle der gemeinsamen Wirkung entsteht eine Scheinkorrelation zwischen den Ursachen</figcaption></figure>
</div>
</div>
</div>
<section id="was-ist-eine-kollision" class="level3" data-number="12.8.1"><h3 data-number="12.8.1" class="anchored" data-anchor-id="was-ist-eine-kollision">
<span class="header-section-number">12.8.1</span> Was ist eine Kollision?</h3>
<p>Als <em>Kollision</em> (Kollisionsverzerrung, Auswahlverzerrung, engl. collider) bezeichnet man einen DAG, bei dem eine Wirkung zwei Ursachen hat (eine gemeinsame Wirkung zweier Ursachen). Kontrolliert man die <em>Wirkung</em> <code>m</code>, so entsteht eine Scheinkorrelation zwischen den Ursachen <code>x</code> und <code>y</code>. Kontrolliert man die Wirkung nicht, so entsteht keine Scheinkorrelation zwischen den Ursachen, s. <a href="#fig-coll1-dag">Abbildung&nbsp;<span>12.19</span></a>, vgl. <span class="citation" data-cites="rohrer_thinking_2018">Rohrer (<a href="references.html#ref-rohrer_thinking_2018" role="doc-biblioref">2018</a>)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wichtig
</div>
</div>
<div class="callout-body-container callout-body">
<p>Man kann also zu viele oder falsche Prädiktoren einer Regression hinzufügen, so dass die Koeffizienten nicht die kausalen Effekte zeigen, sondern durch Scheinkorrelation verzerrte Werte.</p>
</div>
</div>
</section><section id="einfaches-beispiel-zur-kollision" class="level3" data-number="12.8.2"><h3 data-number="12.8.2" class="anchored" data-anchor-id="einfaches-beispiel-zur-kollision">
<span class="header-section-number">12.8.2</span> Einfaches Beispiel zur Kollision</h3>
<p>In der Zeitung <em>Glitzer</em> werden nur folgende Menschen gezeigt:</p>
<ul>
<li>Schöne Menschen</li>
<li>Reiche Menschen</li>
</ul>
<p>Sehen wir davon aus, dass Schönheit und Reichtum unabhängig voneinander sind.</p>
<p>Wenn ich Ihnen sage, dass Don nicht schön ist, aber in der Glitzer häufig auftaucht, was lernen wir dann über seine finanzielle Situation?<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<blockquote class="blockquote">
<p>“Ich bin schön, unglaublich schön, und groß, großartig, tolle Gene!!!” 🧑</p>
</blockquote>
</section><section id="noch-ein-einfaches-beispiel-zur-kollision" class="level3" data-number="12.8.3"><h3 data-number="12.8.3" class="anchored" data-anchor-id="noch-ein-einfaches-beispiel-zur-kollision">
<span class="header-section-number">12.8.3</span> Noch ein einfaches Beispiel zur Kollision</h3>
<blockquote class="blockquote">
<p>“So langsam check ich’s!” 🧑</p>
</blockquote>
<p>Sei Z = X + Y, wobei X und Y unabhängig sind.</p>
<p>Wenn ich Ihnen sage, X = 3, lernen Sie nichts über Y, da die beiden Variablen unabhängig sind Aber: Wenn ich Ihnen zuerst sage, Z = 10, und dann sage, X = 3, wissen Sie sofort, was Y ist (Y = 7).</p>
<p>Also: X und Y sind abhängig, gegeben Z: <span class="math inline">\(X \not\perp \!\!\! \perp Y \,|\, Z\)</span>.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</section><section id="durch-kontrollieren-entsteht-eine-verzerrung-bei-der-kollision" class="level3" data-number="12.8.4"><h3 data-number="12.8.4" class="anchored" data-anchor-id="durch-kontrollieren-entsteht-eine-verzerrung-bei-der-kollision">
<span class="header-section-number">12.8.4</span> Durch Kontrollieren entsteht eine Verzerrung bei der Kollision</h3>
<p><a href="#fig-coll1-dag">Abbildung&nbsp;<span>12.19</span></a> zeigt: Durch Kontrollieren entsteht eine Kollision, eine Scheinkorrelation zwischen den Ursachen.</p>
<p><em>Kontrollieren</em> kann z.B. bedeuten:</p>
<ul>
<li>
<em>Stratifizieren</em>: Aufteilen von <code>date</code> in zwei Gruppen und dann Analyse des Zusammenhangs von <code>talent</code> und <code>looks</code> in jeder Teilgruppe von <code>date</code>
</li>
<li>
<em>Kontrollieren mit Regression</em>: Durch Aufnahme von <code>date</code> als Prädiktor in eine Regression zusätzlich zu <code>looks</code> mit <code>talent</code> als Prädikotr</li>
</ul>
<p><em>Ohne</em> Kontrolle von <code>date</code> entsteht <em>keine</em> Scheinkorrelation zwischen <code>Looks</code> und <code>Talent</code>. Der Pfad (“Fluss”) von <code>Looks</code> über <code>date</code> nach <code>Talent</code> ist blockiert.</p>
<p>Kontrolliert man <code>date</code>, so <em>öffnet</em> sich der Pfad <code>Looks -&gt; date -&gt; talent</code> und die Scheinkorrelation entsteht: Der Pfad ist nicht mehr “blockiert”, die Korrelation kann “fließen” - was sie hier nicht soll, denn es handelt sich um Scheinkorrelation.</p>
<p>Das Kontrollieren von <code>date</code> geht zumeist durch Bilden einer Auswahl einer Teilgruppe von sich.</p>
</section><section id="iq-fleiss-und-eignung-fürs-studium" class="level3" data-number="12.8.5"><h3 data-number="12.8.5" class="anchored" data-anchor-id="iq-fleiss-und-eignung-fürs-studium">
<span class="header-section-number">12.8.5</span> IQ, Fleiss und Eignung fürs Studium</h3>
<p>Sagen wir, über die <em>Eignung</em> für ein Studium würden nur (die individuellen Ausprägungen) von Intelligenz (IQ) und Fleiss entscheiden, s. den DAG in <a href="#fig-coll3-dag">Abbildung&nbsp;<span>12.21</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-coll3-dag_5454e9527168a6e9a71b65fb45145077">
<div class="cell-output-display">
<div id="fig-coll3-dag" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-coll3-dag-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.21: Kollisionsstruktur im Dag zur Studiumseignung</figcaption></figure>
</div>
</div>
</div>
<p>Bei positiver <code>eignung</code> wird ein Studium aufgenommen (<code>studium = 1</code>) ansonsten nicht (<code>studium = 0)</code>.</p>
<p><a href="https://data-se.netlify.app/2020/04/16/simulation-berkson-s-paradox/">Quelle</a></p>
<p><code>eignung</code> (fürs Studium) sei definiert als die Summe von <code>iq</code> und <code>fleiss</code>, plus etwas Glück:</p>
<div class="cell" data-hash="1100-kausal_cache/html/d-eignung_1302ba28a5905294c11c7fe53511d13c">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span>  <span class="co"># Reproduzierbarkeit</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">1e03</span>  </span>
<span></span>
<span><span class="va">d_eignung</span> <span class="op">&lt;-</span></span>
<span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  iq <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,  <span class="co"># normalverteilt mit MW=0, sd=1</span></span>
<span>  fleiss <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span>,</span>
<span>  glueck <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span>,</span>
<span>  eignung <span class="op">=</span> <span class="fl">1</span><span class="op">/</span><span class="fl">2</span> <span class="op">*</span> <span class="va">iq</span> <span class="op">+</span> <span class="fl">1</span><span class="op">/</span><span class="fl">2</span> <span class="op">*</span> <span class="va">fleiss</span> <span class="op">+</span> <span class="va">glueck</span>,</span>
<span>  <span class="co"># nur wer geeignet ist, studiert (in unserem Modell):</span></span>
<span>  studium <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">eignung</span> <span class="op">&gt;</span> <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0</span><span class="op">)</span> </span>
<span>  <span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Laut unserem Modell setzt sich Eignung zur Hälfte aus Intelligenz und zur Hälfte aus Fleiss zusammen, plus etwas Glück.</p>
</section><section id="schlagzeile-schlauheit-macht-studentis-faul" class="level3" data-number="12.8.6"><h3 data-number="12.8.6" class="anchored" data-anchor-id="schlagzeile-schlauheit-macht-studentis-faul">
<span class="header-section-number">12.8.6</span> Schlagzeile “Schlauheit macht Studentis faul!”</h3>
<p>Eine Studie untersucht den Zusammenhang von Intelligenz (iq) und Fleiß (f) bei Studentis (s). Ergebnis: Ein <em>negativer</em> Zusammenhang!?</p>
<p>Berechnen wir das “Eignungsmodell”, aber nur mit Studis (<code>studium == 1</code>, also ohne Nicht-Studis), s. <a href="#tbl-m-eignung">Tabelle&nbsp;<span>12.12</span></a>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/unnamed-chunk-16_0223744fb7b393b6da2e10f9526ca52b">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_eignung</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">iq</span> <span class="op">~</span> <span class="va">fleiss</span>, data <span class="op">=</span> <span class="va">d_eignung</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">studium</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span>, refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">hdi</span><span class="op">(</span><span class="va">m_eignung</span><span class="op">)</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/tbl-m-eignung_95cf5a6b79792979a50421fe78091fc2">
<div class="cell-output-display">
<div id="tbl-m-eignung" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabelle&nbsp;12.12: Zum Zusammenhang von Fleiss und Talent</caption>
<thead><tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">95% HDI</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">[ 0.70, 0.86]</td>
</tr>
<tr class="even">
<td style="text-align: left;">fleiss</td>
<td style="text-align: left;">[-0.53, -0.36]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><a href="#fig-eignung">Abbildung&nbsp;<span>12.22</span></a> zeigt das Modell und die Daten.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-eignung_2a370f0db986f17ac8e0990c1055603a">
<div class="cell-output-display">
<div id="fig-eignung" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-eignung-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.22: Der Zusammenhang von Fleiss und IQ</figcaption></figure>
</div>
</div>
</div>
<p>IQ ist <em>nicht</em> unabhängig von Fleiß in unseren Daten, sondern abhängig.</p>
<p>Nichtwissenschaftliche Berichte, etwa in einigen Medien, greifen gerne Befunde über Zusammenhänge auf und interpretieren die Zusammenhänge – oft vorschnell – als kausal.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
</section><section id="kollisionsverzerrung-nur-bei-stratifizierung" class="level3" data-number="12.8.7"><h3 data-number="12.8.7" class="anchored" data-anchor-id="kollisionsverzerrung-nur-bei-stratifizierung">
<span class="header-section-number">12.8.7</span> Kollisionsverzerrung nur bei Stratifizierung</h3>
<p>Nur durch das Stratifizieren (Aufteilen in Subgruppen, Kontrollieren, Adjustieren) tritt die Scheinkorrelation auf, s. <a href="#fig-eignung-strat">Abbildung&nbsp;<span>12.23</span></a>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Ohne</em> Stratifizierung tritt <em>keine</em> Scheinkorrelation auf. <em>Mit</em> Stratifizierung tritt Scheinkorrelation auf.</p>
</div>
</div>
<div class="cell" data-hash="1100-kausal_cache/html/fig-eignung-strat_7c8cc4608fad758d48df8c2ee3d049af">
<div class="cell-output-display">
<div id="fig-eignung-strat" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-eignung-strat-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.23: Stratifizierung und Scheinkorrelation</figcaption></figure>
</div>
</div>
</div>
<p>Wildes Kontrollieren einer Variablen - Aufnehmen in die Regression - kann genausog ut schaden wie nützen.</p>
<p><em>Nur</em> Kenntnis des DAGs verrät die richtige Entscheidung: ob man eine Variable kontrolliert oder nicht.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nimmt man eine Variable als zweiten Prädiktor auf, so “kontrolliert” man diese Variable. Das Regressiongewicht des ersten Prädiktors wird “bereinigt” um den Einfluss des zweiten Prädiktors; insofern ist der zweite Prädiktor dann “kontrolliert”.</p>
</div>
</div>
</section><section id="einfluss-von-großeltern-und-eltern-auf-kinder" class="level3" data-number="12.8.8"><h3 data-number="12.8.8" class="anchored" data-anchor-id="einfluss-von-großeltern-und-eltern-auf-kinder">
<span class="header-section-number">12.8.8</span> Einfluss von Großeltern und Eltern auf Kinder</h3>
<p>Wir wollen hier den (kausalen) Einfluss der Eltern <code>E</code> und Großeltern <code>G</code> auf den <em>Bildungserfolg</em> der Kinder <code>K</code> untersuchen.</p>
<p>Wir nehmen folgende Effekte an:</p>
<ul>
<li>indirekter Effekt von <code>G</code> auf <code>K</code>: <span class="math inline">\(G \rightarrow E \rightarrow K\)</span>
</li>
<li>direkter Effekt von <code>E</code> auf <code>K</code>: <span class="math inline">\(E \rightarrow K\)</span>
</li>
<li>direkter Effekt von <code>G</code> auf <code>K</code>: <span class="math inline">\(G \rightarrow K\)</span>
</li>
</ul>
<p>Wir sind v.a. interessiert an <span class="math inline">\(G \rightarrow K\)</span>, dem <em>direkten kausalen</em> Effekt von Großeltern auf ihre Enkel, s. <a href="#fig-dag-grannies">Abbildung&nbsp;<span>12.24</span></a>, <span class="math inline">\(G \rightarrow K\)</span>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-grannies_ce96684319c408bcdf9a4ef82755323d">
<div class="cell-output-display">
<div id="fig-dag-grannies" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-grannies-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.24: Der kausale Effekt von Großeltern auf Enkel. Ein verlorener Fall, zumindest was den DAG betrifft</figcaption></figure>
</div>
</div>
</div>
<p>Aber was ist, wenn wir vielleicht eine <em>u</em>nbekannte Variable übersehen haben? (S. nächster Abschnitt). 👻</p>
</section><section id="der-gespenster-dag" class="level3" data-number="12.8.9"><h3 data-number="12.8.9" class="anchored" data-anchor-id="der-gespenster-dag">
<span class="header-section-number">12.8.9</span> Der Gespenster-DAG</h3>
<p>👻</p>
<p>Es gibt “unheilbare” DAGs, nennen wir sie “Gespenster-DAGs”, in denen es nicht möglich ist, einen (unverzerrten) Kausaleffekt zu bestimmen, s. <a href="#fig-dag-ghost">Abbildung&nbsp;<span>12.25</span></a>. Letztlich sagt uns der DAG bzw. unsere Analyse zum DAG: “Deine Theorie ist nicht gut, zurück an den Schreibtisch und denk noch mal gut nach. Oder sammele mehr Daten.”</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-ghost_5c4aebce7fd9c88df83eb49a06f4b104">
<div class="cell-output-display">
<div id="fig-dag-ghost" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-ghost-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.25: Der Gespenster-DAG: Eine Identifikation der Kausaleffekt ist nicht (vollständig) möglich.</figcaption></figure>
</div>
</div>
</div>
<ul>
<li><p><code>U</code> könnte ein ungemessener Einfluss sein, der auf <code>E</code> und <code>K</code> wirkt, etwa <em>Nachbarschaft</em>.</p></li>
<li><p>Die Großeltern wohnen woanders (in Spanien), daher wirkt die Nachbarschaft der Eltern und Kinder nicht auf sie.</p></li>
<li><p><code>E</code> ist sowohl für <code>G</code> als auch für <code>U</code> eine Wirkung, also eine Kollisionsvariable auf diesem Pfad.</p></li>
<li><p>Wenn wir <code>E</code> kontrollieren, wird es den Pfad <span class="math inline">\(G \rightarrow K\)</span> verzerren, auch wenn wir niemals <code>U</code> messen.</p></li>
</ul>
<p>Die Sache ist in diesem Fall chancenlos. Wir müssen diesen DAG verloren geben, <span class="citation" data-cites="mcelreath_statistical_2020">McElreath (<a href="references.html#ref-mcelreath_statistical_2020" role="doc-biblioref">2020</a>)</span>, S. 180.</p>
</section></section><section id="die-hintertür-schließen" class="level2" data-number="12.9"><h2 data-number="12.9" class="anchored" data-anchor-id="die-hintertür-schließen">
<span class="header-section-number">12.9</span> Die Hintertür schließen</h2>
<section id="zur-erinnerung-konfundierung" class="level3" data-number="12.9.1"><h3 data-number="12.9.1" class="anchored" data-anchor-id="zur-erinnerung-konfundierung">
<span class="header-section-number">12.9.1</span> Zur Erinnerung: Konfundierung</h3>
<p><em>Forschungsfrage</em>: Wie groß ist der (kausale) Einfluss der Schlafzimmerzahl auf den Verkaufspreis des Hauses?</p>
<p><code>a:</code> livingArea, <code>b</code>: bedrooms, <code>p</code>: prize</p>
<p>UV: <code>b</code>, AV: <code>p</code></p>
<p>Das Kausalmodell ist in <a href="#fig-dag-don1">Abbildung&nbsp;<span>12.26</span></a> dargestellt.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-don1_b7fb914c593423edd5d6c704eda96282">
<div class="cell-output-display">
<div id="fig-dag-don1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-don1-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.26: Der Preis wird sowohl von der Zimmerzahl als auch der Wohnfläche beeinflusst</figcaption></figure>
</div>
</div>
</div>
<p>Im Regressionsmodell <code>p ~ b</code> wird der kausale Effekt verzerrt sein durch die Konfundierung mit <code>a</code>. Der Grund für die Konfundierung sind die zwei Pfade zwischen <code>b</code> und <code>p</code>:</p>
<ol type="1">
<li><span class="math inline">\(b \rightarrow p\)</span></li>
<li><span class="math inline">\(b \rightarrow a \rightarrow p\)</span></li>
</ol>
<p>Beide Pfade erzeugen (statistische) Assoziation zwischen <code>b</code> und <code>p</code>. Aber nur der erste Pfad ist kausal; der zweite ist nichtkausal. Gäbe es nur nur den zweiten Pfad und wir würden <code>b</code> ändern, so würde sich <code>p</code> nicht ändern.</p>
</section><section id="gute-experimente-zeigen-den-echten-kausalen-effekt" class="level3" data-number="12.9.2"><h3 data-number="12.9.2" class="anchored" data-anchor-id="gute-experimente-zeigen-den-echten-kausalen-effekt">
<span class="header-section-number">12.9.2</span> Gute Experimente zeigen den echten kausalen Effekt</h3>
<p><a href="#fig-dag-tuer-zu">Abbildung&nbsp;<span>12.27</span></a> zeigt eine erfreuliche Situation: Die “Hintertür” zu unserer UV (Zimmerzahl) ist geschlossen!</p>
<p>Ist die Hintertür geschlossen - führen also keine Pfeile in unserer UV - so kann eine Konfundierung ausgeschlossen werden.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-tuer-zu_44379991248dcc09ecaa6cc48704be36">
<div class="cell-output-display">
<div id="fig-dag-tuer-zu" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-tuer-zu-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.27: Unverzerrte Schätzung des kausalen Effekts unserer UV (Zimmerzahl). Das Regressionsgewicht ist hier der unverzerrte Kausaleffekt. Es spielt keine Rolle, ob der andere Prädiktor im Modell enthalten ist. Da die beiden Prädiktoren unkorreliert sind, hat die Aufnahme des einen Prädiktors keinen Einfluss auf das Regressionsgewicht des anderen.</figcaption></figure>
</div>
</div>
</div>
<p>Die “Hintertür” der UV (<code>b</code>) ist jetzt zu! Der einzig verbleibende, erste Pfad ist der kausale Pfad und die Assoziation zwischen <code>b</code> und <code>p</code> ist jetzt komplett kausal.</p>
<p>Eine berühmte Lösung, den kausalen Pfad zu isolieren, ist ein (randomsiertes, kontrolliertes) Experiment. Wenn wir den Häusern zufällig (randomisiert) eine Anzahl von Schlafzimmern (<code>b</code>) zuweisen könnten (unabhängig von ihrer Quadratmeterzahl, <code>a</code>), würde sich der Graph so ändern. Das Experiment <em>entfernt</em> den Einfluss von <code>a</code> auf <code>b</code>. Wenn wir selber die Werte von <code>b</code> einstellen im Rahmen des Experiments, so kann <code>a</code> keine Wirkung auf <code>b</code> haben. Damit wird der zweite Pfad, <span class="math inline">\(b \rightarrow a \rightarrow p\)</span> geschlossen (“blockiert”).</p>
</section><section id="hintertür-schließen-auch-ohne-experimente" class="level3" data-number="12.9.3"><h3 data-number="12.9.3" class="anchored" data-anchor-id="hintertür-schließen-auch-ohne-experimente">
<span class="header-section-number">12.9.3</span> Hintertür schließen auch ohne Experimente</h3>
<p>Konfundierende Pfade zu blockieren zwischen der UV und der AV nennt man auch <em>die Hintertür schließen</em> (backdoor criterion).</p>
<p>Wir wollen die Hintertüre schließen, da wir sonst nicht den wahren, kausalen Effekt bestimmen können.</p>
<p>Zum Glück gibt es neben Experimenten noch andere Wege, die Hintertür zu schließen, wie die Konfundierungsvariable <code>a</code> in eine Regression mit aufzunehmen.</p>
<p>Warum blockt das Kontrollieren von <code>a</code>den Pfad <span class="math inline">\(b \leftarrow a \rightarrow p\)</span>? Stellen Sie sich den Pfad als eigenen Modell vor. Sobald Sie <code>a</code> kennen, bringt Ihnen Kenntnis über <code>b</code> kein zusätzliches Wissen über <code>p</code>. Wissen Sie hingegen nichts über <code>a</code>, lernen Sie bei Kenntnis von <code>b</code> auch etwas über <code>p</code>. Konditionieren ist wie “gegeben, dass Sie <code>a</code> schon kennen…”.</p>
<p><span class="math inline">\(b \perp \!\!\! \perp p \,|\,a\)</span></p>
</section><section id="die-vier-atome-der-kausalanalyse" class="level3" data-number="12.9.4"><h3 data-number="12.9.4" class="anchored" data-anchor-id="die-vier-atome-der-kausalanalyse">
<span class="header-section-number">12.9.4</span> Die vier Atome der Kausalanalyse</h3>
<p><a href="#fig-four-atoms">Abbildung&nbsp;<span>12.28</span></a> stellt die vier “Atome” der Kausalinferenz dar. Mehr gibt es nicht! Kennen Sie diese vier Grundbausteine, so können Sie jedes beliebige Kausalsystem (DAG) entschlüsseln.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-four-atoms_f204f040e2bd0ae664d0a9822c668b50">
<div class="cell-output-display">
<div id="fig-four-atoms" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-four-atoms-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.28: Die vier Atome der Kausalinferenz</figcaption></figure>
</div>
</div>
</div>
</section><section id="mediation" class="level3" data-number="12.9.5"><h3 data-number="12.9.5" class="anchored" data-anchor-id="mediation">
<span class="header-section-number">12.9.5</span> Mediation</h3>
<p>Die <em>Mediation</em> (synonym: Wirkkette, Rohr, Kette, chain) beschreibt Pfade, in der die Kanten (eines Pfades) die gleiche Wirkrichtung haben: <span class="math inline">\(x \rightarrow m \rightarrow y\)</span>. Anders gesagt: Eine Mediation ist eine Kausalabfolge der Art <span class="math inline">\(x \rightarrow m \rightarrow y\)</span>, s. <a href="#fig-med1">Abbildung&nbsp;<span>12.29</span></a>. Die Variable in der Mitte <span class="math inline">\(m\)</span> der Kette wird auch <em>Mediator</em> genannt, weil sei die Wirkung von X auf Y “vermittelt” oder überträgt. Die Erforschung von Mediation spielt eine recht wichtige Rolle in einigen Wissenschaften, wie der Psychologie.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-med1_d9a36cbc7a62dc7c9d8fa4190a8de215">
<div class="cell-output-display">
<div id="fig-med1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-med1-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.29: Das Kausalmodell der Mediation.</figcaption></figure>
</div>
</div>
</div>
<p>Ohne Kontrollieren ist der Pfad offen: Die Assoziation “fließt” den Pfad entlang (in beide Richtungen). Kontrollieren blockt (schließt) die Kette (genau wie bei der Gabel).</p>
<p>Es kann auch angenommen werden, dass der Mediator nicht der einzige Weg von X zu Y ist, s. <a href="#fig-part-med">Abbildung&nbsp;<span>12.30</span></a>. In <a href="#fig-part-med">Abbildung&nbsp;<span>12.30</span></a> gibt es zwei kausale Pfade von X zu Y: <span class="math inline">\(x\rightarrow m \rightarrow y\)</span> und <span class="math inline">\(x \rightarrow y\)</span>. Die Summe der Effekte beider Pfade nennt man den <em>totalen (kausalen) Effekt</em>. Den Effekt über den Mediatorpfad nennt man den <em>indirekten (kausalen) Effekt</em> und den Pfad <span class="math inline">\(x\rightarrow y\)</span> nennt man den <em>direkten (kaudalen) Effekt</em>.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-part-med_b62b4c5981e20ad0a29c67010bb4d3de">
<div class="cell-output-display">
<div id="fig-part-med" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-part-med-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.30: Partielle Mediation</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="der-nachfahre" class="level2" data-number="12.10"><h2 data-number="12.10" class="anchored" data-anchor-id="der-nachfahre">
<span class="header-section-number">12.10</span> Der Nachfahre</h2>
<p>Ein <em>Nachfahre</em> (descendent) ist eine Variable die von einer anderen Variable beeinflusst wird, s. <a href="#fig-dag-nachfahre">Abbildung&nbsp;<span>12.31</span></a>. Kontrolliert man einen Nachfahren <code>d</code>, so kontrolliert man damit zum Teil den Vorfahren (die Ursache), <code>m</code>. Der Grund ist, dass <code>d</code> Information beinhaltet über <code>m</code>. Hier wird das Kontrollieren von <code>d</code> den Pfad von <code>x</code> nach <code>y</code> teilweise öffnen, da <code>m</code> eine Kollisionsvariable ist.</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-nachfahre_41dda96c9a2ef92faef491c5a7bc1a65">
<div class="cell-output-display">
<div id="fig-dag-nachfahre" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-nachfahre-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.31: Ein Nachfahre verhält sich ähnlich wie sein Vorfahre…</figcaption></figure>
</div>
</div>
</div>
<section id="kochrezept-zur-analyse-von-dags" class="level3" data-number="12.10.1"><h3 data-number="12.10.1" class="anchored" data-anchor-id="kochrezept-zur-analyse-von-dags">
<span class="header-section-number">12.10.1</span> Kochrezept zur Analyse von DAGs</h3>
<p>Wie kompliziert ein DAG auch aussehen mag, er ist immer aus diesen vier Atomen aufgebaut.</p>
<p>Hier ist ein Rezept, das garantiert, dass Sie welche Variablen Sie kontrollieren sollten und welche nicht:</p>
<ol type="1">
<li>Listen Sie alle Pfade von UV (<code>X</code>) zu AV (<code>Y</code>) auf.</li>
<li>Beurteilen Sie jeden Pfad, ob er gerade geschlossen oder geöffnet ist.</li>
<li>Beurteilen Sie für jeden Pfad, ob er ein Hintertürpfad ist (Hintertürpfade haben einen Pfeil, der zur UV führt).</li>
<li>Wenn es geöffnete Hinterpfade gibt, prüfen Sie, welche Variablen mann kontrollieren muss, um den Pfad zu schließen (falls möglich).</li>
</ol></section></section><section id="schließen-sie-die-hintertür-wenn-möglich-bsp1" class="level2" data-number="12.11"><h2 data-number="12.11" class="anchored" data-anchor-id="schließen-sie-die-hintertür-wenn-möglich-bsp1">
<span class="header-section-number">12.11</span> Schließen Sie die Hintertür (wenn möglich)!, <code>bsp1</code>
</h2>
<p>UV: <span class="math inline">\(X\)</span>, AV: <span class="math inline">\(Y\)</span>, drei Covariaten (A, B, C) und ein ungemessene Variable, U</p>
<div class="cell" data-hash="1100-kausal_cache/html/fig-dag-fancy_a3368fcd8823bc3a9dd274d9d15197b2">
<div class="cell-output-display">
<div id="fig-dag-fancy" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-fancy-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.32: Puh, ein schon recht komplizierter DAG</figcaption></figure>
</div>
</div>
</div>
<p>Es gibt zwei Hintertürpfade in <a href="#fig-dag-fancy">Abbildung&nbsp;<span>12.32</span></a>:</p>
<ol type="1">
<li>
<span class="math inline">\(X \leftarrow U \leftarrow A \rightarrow C \rightarrow Y\)</span>, offen</li>
<li>
<span class="math inline">\(X \leftarrow U \rightarrow B \leftarrow C \rightarrow Y\)</span>, geschlossen</li>
</ol>
<p>Kontrollieren von <span class="math inline">\(A\)</span> oder (auch) <span class="math inline">\(C\)</span> schließt die offene Hintertür.</p>
<p><span class="citation" data-cites="mcelreath_statistical_2020">McElreath (<a href="references.html#ref-mcelreath_statistical_2020" role="doc-biblioref">2020</a>)</span>, <span class="citation" data-cites="kurz_statistical_2021">Kurz (<a href="references.html#ref-kurz_statistical_2021" role="doc-biblioref">2021</a>)</span>, s.S. 186.</p>
<section id="schließen-sie-die-hintertür-wenn-möglich-bsp2" class="level3" data-number="12.11.1"><h3 data-number="12.11.1" class="anchored" data-anchor-id="schließen-sie-die-hintertür-wenn-möglich-bsp2">
<span class="header-section-number">12.11.1</span> Schließen Sie die Hintertür (wenn möglich)!, <code>bsp2</code>
</h3>
<p>S. DAG in <a href="#fig-dag-bsp2">Abbildung&nbsp;<span>12.33</span></a>: UV: <span class="math inline">\(W\)</span>, AV: <span class="math inline">\(D\)</span></p>
<div class="cell" data-fig.asp="0.5" data-hash="1100-kausal_cache/html/fig-dag-bsp2_7669a19da70f2b230361b3d550e7a108">
<div class="cell-output-display">
<div id="fig-dag-bsp2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="1100-kausal_files/figure-html/fig-dag-bsp2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Abbildung&nbsp;12.33: Welche Variablen muss man kontrollieren, um den Effekt von W auf D zu bestimmen?</figcaption></figure>
</div>
</div>
</div>
<p>Kontrollieren Sie diese Variablen, um die offenen Hintertüren zu schließen:</p>
<ul>
<li>entweder <span class="math inline">\(A\)</span> und <span class="math inline">\(M\)</span>
</li>
<li>oder <span class="math inline">\(S\)</span>
</li>
</ul>
<p><a href="https://bookdown.org/content/4857/the-haunted-dag-the-causal-terror.html#backdoor-waffles.">Mehr Infos</a></p>
<p>Details finden sich bei <span class="citation" data-cites="mcelreath_statistical_2020">McElreath (<a href="references.html#ref-mcelreath_statistical_2020" role="doc-biblioref">2020</a>)</span> oder <span class="citation" data-cites="kurz_statistical_2021">Kurz (<a href="references.html#ref-kurz_statistical_2021" role="doc-biblioref">2021</a>)</span>, ‚S. 188.</p>
</section><section id="implizierte-bedingte-unabhängigkeiten-von-bsp2" class="level3" data-number="12.11.2"><h3 data-number="12.11.2" class="anchored" data-anchor-id="implizierte-bedingte-unabhängigkeiten-von-bsp2">
<span class="header-section-number">12.11.2</span> Implizierte bedingte Unabhängigkeiten von <code>bsp2</code>
</h3>
<p>Ein Graph ohne <code>U</code>s ist eine starke - oft zu starke (unrealistisch optimistische) - Annahme. Auch wenn die Daten nicht sagen können, welcher DAG der richtige ist, können wir zumindest lernen, welcher DAG falsch ist. Die vom Modell implizierten bedingten Unabhängigkeiten geben uns Möglichkeiten, zu prüfen, ob wir einen DAG verwerfen (ausschließen) können. Bedingten Unabhängigkeit zwischen zwei Variablen sind Variablen, die nicht assoziiert (also stochastisch unabhängig) sind, wenn wir eine bestimmte Menge an Drittvariablen kontrollieren.</p>
<p><code>bsp2</code> impliziert folgende bedingte Unabhängigkeiten:</p>
<div class="cell" data-hash="1100-kausal_cache/html/bsp2-cond-independence_13d1530e332e6d458363883a0c966ade">
<pre><code>## A _||_ W | S
## D _||_ S | A, M, W
## M _||_ W | S</code></pre>
</div>
</section></section><section id="fazit" class="level2" data-number="12.12"><h2 data-number="12.12" class="anchored" data-anchor-id="fazit">
<span class="header-section-number">12.12</span> Fazit</h2>
<p>Wie (und sogar ob) Sie statistische Ergebnisse (z.B. eines Regressionsmodells) interpretieren können, hängt von der <em>epistemologischen Zielrichtung</em> der Forschungsfrage ab:</p>
<ul>
<li>Bei <em>deskriptiven</em> Forschungsfragen können die Ergebnisse (z.B. Regressionskoeffizienten) direkt interpretiert werden. Z.B. “Der Unterschied zwischen beiden Gruppen beträgt etwa …”. Allerdings ist eine kausale Interpretation nicht zulässig.</li>
<li>Bei <em>prognostischen</em> Fragestellungen (Vorhersagen) spielen die Modellkoeffizienten keine Rolle, stattdessen geht es um vorhergesagten Werte, <span class="math inline">\(\hat{y}_i\)</span>, z.B. auf Basis der PPV. Kausalaussagen sind zwar nicht möglich, aber auch nicht von Interesse.</li>
<li>Bei <em>kausalen</em> Forschungsfragen dürfen die Modellkoeffizienten nur auf Basis eines Kausalmodells (DAG) oder eines (gut gemachten) Experiments interpretiert werden.</li>
</ul>
<p>Modellkoeffizienten ändern sich (oft), wenn man Prädiktoren zum Modell hinzufügt oder wegnimmt. Entgegen der verbreiteten Annahme ist es falsch, möglichst viele Prädiktoren in das Modell aufzunehmen, wenn das Ziel eine Kausalaussage ist. Kenntnis der “kausalen Atome” ist Voraussetzung zur Ableitung von Kausalschlüsse in Beobachtungsstudien.</p>
</section><section id="aufgaben" class="level2" data-number="12.13"><h2 data-number="12.13" class="anchored" data-anchor-id="aufgaben">
<span class="header-section-number">12.13</span> Aufgaben</h2>
<ul>
<li><a href="https://datenwerk.netlify.app/#category=causal">Sammlung “kausal”</a></li>
</ul></section><section id="section" class="level2" data-number="12.14"><h2 data-number="12.14" class="anchored" data-anchor-id="section">
<span class="header-section-number">12.14</span> —</h2>
<p><img src="img/outro-11.jpg" class="img-fluid" style="width:100.0%"></p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-kurz_statistical_2021" class="csl-entry" role="listitem">
Kurz, A. Solomon. 2021. <em>Statistical Rethinking with Brms, Ggplot2, and the Tidyverse: <span>Second</span> Edition</em>. <a href="https://bookdown.org/content/4857/">https://bookdown.org/content/4857/</a>.
</div>
<div id="ref-mcelreath_statistical_2020" class="csl-entry" role="listitem">
McElreath, Richard. 2020. <em>Statistical Rethinking: A <span>Bayesian</span> Course with Examples in <span>R</span> and <span>Stan</span></em>. 2. Aufl. <span>CRC</span> Texts in Statistical Science. <span>Boca Raton</span>: <span>Taylor and Francis, CRC Press</span>.
</div>
<div id="ref-messerli_chocolate_2012" class="csl-entry" role="listitem">
Messerli, Franz H. 2012. <span>„Chocolate <span>Consumption</span>, <span>Cognitive Function</span>, and <span>Nobel Laureates</span>“</span>. <em>New England Journal of Medicine</em> 367 (16): 1562–64. <a href="https://doi.org/10.1056/NEJMon1211064">https://doi.org/10.1056/NEJMon1211064</a>.
</div>
<div id="ref-pearl_causal_2016" class="csl-entry" role="listitem">
Pearl, Judea, Madelyn Glymour, und Nicholas P. Jewell. 2016. <em>Causal Inference in Statistics: A Primer</em>. <span>Chichester, West Sussex</span>: <span>Wiley</span>.
</div>
<div id="ref-rohrer_thinking_2018" class="csl-entry" role="listitem">
Rohrer, Julia M. 2018. <span>„Thinking <span>Clearly About Correlations</span> and <span>Causation</span>: <span>Graphical Causal Models</span> for <span>Observational Data</span>“</span>. <em>Advances in Methods and Practices in Psychological Science</em> 1 (1): 27–42. <a href="https://doi.org/10.1177/2515245917745629">https://doi.org/10.1177/2515245917745629</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>Dieser Abschnitt ist prüfungsrelevant, birgt aber nichts Neues.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>In aller Regel macht es mehr Sinn, die Schätzbereiche der Punktschätzer auch zu betrachten. Nur die Punktschätzer zu betrachten vernachlässigt wesentliche Information.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Anstelle von <code>estimate_relation()</code> kann man auch (einfacher vielleicht) <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> verwenden: <code>predict(m1, newdata = dons_new_house)</code>. Allerdings gibt <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> nur den vorhergesagten Wert aus. <code>estimate_prediction()</code> gibt noch zusätzlich das <em>Vorhersageintervall</em> aus, berücksichtigt also die (doppelte) Ungewissheit der Vorhersage. Mit anderen Worten: <code>estimate_prediction</code> gibt die PPV aus.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Don muss reich sein.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Der horizontale Balken “|” bedeutet “gegeben, dass”. Ein Beispiel lautet <span class="math inline">\(Pr(A|B)\)</span>: “Die Wahrscheinlichkeit von A, gegeben dass B der Fall ist.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Ehrlicherweise muss man zugeben, dass auch wissenschaftliche Berichte Daten über Zusammenhänge gerne kausal interpretieren, oft vorschnell.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./1000-metrische-AV.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Forschungsfragen mit metrischer AV</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./1200-abschluss.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Abschluss</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>