


:::{#def-pd}
### Pobability of Direction (pd)
Der Kennwert *pd* variiert zwischen 50 und 100% und kann als Wahrscheinlichkeit verstanden werden,
dass ein Parameter streng positiv oder negativ ist (je nach dem, was von beiden wahrscheinlicher ist).
Der Kennwert ist definiert als der Anteil der Posteriori-Verteilung,
der das gleiche Vorzeichen hat wie der Median.
:::


:::{#exm-pd}
Im Modell `m6`, s. @tbl-m106-params in @sec-yg wird das mittlere Gewicht von drei Pinguinrassen verglichen. Das Modell resümiert, dass die Rasse *Gentoo* mit 100% Wahrscheinlichkeit einen höheren Gewichtsmittelwert hat als die Rasse *Adelie*: $pd = 1$. Mit Blick auf die Rasse *Chinstrap* geht das Modell von einer Wahrscheinlichkeit von von ca. 69% aus, $pd=.69$ (für ein höheres mittleres Gewicht im Vergleich zur Referenzgruppe, Chinstrap). $\square$
:::



### Praktisch bedeutsame Signifikanz

In vielen Forschungskontexten ist die Nullhypothese von vornhinein (apriori) als falsch bekannt, vgl. @gelman2021, S. 59: "In many problems we do not think the null hypothesis can be true", "just about every treament one might consider will have *some* effect (...) We do not find it particularly helpflul to formulate and tests null hypotheses that we know ahead of timme cannot be true".

Man bedenke, dass eine Aussage wie "der Effekt ist null" bedeutet, dass der Wert *exakt* null ist, also $0,00000000000000 \ldots$ und *nicht etwa $0,000000000001$.
Das ist eine sehr starke Aussage.

:::{#exm-nullistfalsch}
### Beispiele für Nullhypothesen, die (fast) sicher falsch apriori falsch sind

- Die Mittelwerte der beiden Gruppen sind (exakt) gleich.
- Die Trefferwahrscheinlichkeit der Münze beträgt (exakt) 50%.
- Patienten, die mit der neuen Therapie behandelt wurden, haben (exakt) die gleichen Heilungsraten (wie Patienten, die mit der alten Therapie behandelt wurden). $\square$
:::


Neuere Ansätze in der (Bayes-)Statistik erlauben daher anstelle von Exakt-Nullhypothesen auch Ungefähr-Nullhypothesen zu testen.

:::{#def-ungefährnull}
### Ungefähr-Nullhypothese

Eine Ungefähr-Nullhypothese definiert nicht nur null, sondern einen Bereich um die Null herum als "keinen" bzw. "nicht bedeutsamen" Effekt.
Findet sich ein Ergebnis, das in diesen Bereich nicht bedeutsamer Werte fällt,
so ist das Ergebnis nicht praktisch bedeutsam signifikant. Anders gesagt: Der Effekt ist vernachlässigbar klein. $\square$
:::

:::{#exm-ungefährnull}
### Beispiele für Ungefähr-Nullhypothesen

Eine Forschungsgruppe testet ein neues Krebsmedikament.
Es wird davon ausgegangen, dass das Medikament nur dann einen substanziellen Effekt hat, wenn die Heilungsrate sich um mindestens 5 Prozentpunkte erhöht.

Eine Psychologin testet die Akzeptanz von Robotern durch Testpersonen in Abhängigkeit davon, ob die Roboterstimme das gleiche Geschlecht aufweist wie die jeweilige Versuchsperson. Die Forscherin definiert einen Unterschied ab einer drittel Standardabweichung als substanziell. $\square$
:::






