


### Hypothesen testen

<!-- TODO Def Hypothese  -->

Um eine Hypothese zu testen, wird oft wie folgt vorgegangen:


1. Man stellt eine statistische Forschungshypothese ("Alternativhypothese" genannt, $H_A$) auf und eine korrespondieren Nullhypothese $H_0.

2. Man testet die $H_0$. Dafür prüft man statistisch, ob die Daten $D$ mit der $H_0$ konsistent sind, also zur $H_0$ passen.

3. Je nach Datenlagen trifft man eine Entscheidung:

  A) Passen die Daten nicht zur $H_0$, lehnt man die $H_0$ ab, man sagt, man "verwirft" die $H_0$ oder man "hat die $H_0$ falsifiziert. In diesem Fall akzeptiert man die $H_A$.

  B) Passen die Daten gut oder einigermaßen zur $H_0$, so behält man die $H_0$ bei. Man verwirft die $H_0$ *nicht*. Das heißt *nicht*, dass die $H_A$ sicher falsch ist. Wir haben nur keinen ausreichenden Grund, die $H_0$ auszuschließen.


Das Testen von Hypothesen lässt sich mit dem Urteil eines Gerichts vergleichen:


| Hypothesen testen  	| Urteil eines Gerichts                             	|
|--------------------	|---------------------------------------------------	|
| H0                 	| Angeklagter ist unschuldig                        	|
| HA                 	| Angeklagter ist schuldig                          	|
| Daten              	| Indizien der Anklage                              	|


Es gilt vorab die Unschuldsvermutung, also die $H_0$.
Die Beweislast ist also beim Kläger.

Das Gericht kann zu zwei Urteilen kommen: *Schuldig* ($H_0$ verwerfen) oder *nicht schuldig* ($H_0$ nicht verworfen).
Wichtig ist zu verstehen, dass *nicht schuldig* kein Beweis der Unschuld ist.
Es gibt nur nicht genug Indizien für einen Schuldspruch.

Daher sind zwei Fehler möglich:

*Fehler Typ 1*: Das Gericht spricht den Angeklagten *schuldig*, obwohl der Angeklagte in Wahrheit *unschuldig* ist. Die $H_0$ ist wahr, wird aber fälschlich verworfen.


*Fehler Typ 2*: Das Gericht spricht sich für *nicht schuldig* aus, obwohl der Angeklagte in Wahrheit *schuldig* ist. Die $H_0$ ist falsch, wird aber fälschlich beibehalten (nicht verworfen).


Diese Vorgehensweise ist eine Mischung aus den Ideen der Statistiker Ronald A. Fisher und den beiden Statistikern Jerzy Neyman und Karl Pearson [@gigerenzer2004].



