{
  "hash": "5436ee7211bd031291798eaa41f48e87",
  "result": {
    "engine": "knitr",
    "markdown": "# Gauss-Modelle\n\n![Bayes:Start!](img/Golem_hex.png){width=\"10%\"}\n\n## Lernsteuerung\n\n### Position im Modulverlauf\n\n@fig-modulverlauf gibt einen Überblick zum aktuellen Standort im Modulverlauf.\n\n### Lernziele\n\nNach Absolvieren des jeweiligen Kapitels sollen folgende Lernziele erreicht sein.\n\nSie können …\n\n-   ein Gaußmodell spezifizieren und in R berechnen\n-   an Beispielen verdeutlichen, wie sich eine vage bzw. eine informationsreiche Priori-Verteilung auf die Posteriori-Verteilung auswirkt\n\n### Begleitliteratur\n\nDer Stoff dieses Kapitels orientiert sich an @mcelreath2020, Kap. 4.1 bis 4.3.\n\n### Vorbereitung im Eigenstudium\n\n-   [Statistik1, Kap. \"Modellgüte\"](https://statistik1.netlify.app/060-modellguete)\n-   [Statistik1, Kap. \"Punktmodelle 2\"](https://statistik1.netlify.app/070-zusammenhaenge)\n-   [Statistik1, Abschnitt \"Normalverteilung\"](https://statistik1.netlify.app/040-verbildlichen#normalverteilung)\n\n### Benötigte R-Pakete\n\nFür `rstanarm` wird ggf. [weitere Software](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) benötigt.\n\n::: callout-note\nSoftware, und das sind R-Pakete, müssen Sie nur einmalig installieren. Aber bei jedem Start von R bzw. RStudio müssen Sie die (benötigten!) Pakete starten.\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)  # Datenjudo\nlibrary(rstanarm)  # Bayes-Modelle berechnen\nlibrary(easystats)  # Statistik-Komfort\nlibrary(DataExplorer)  # Daten verbildlichen\nlibrary(ggpubr)  # Daten verbildlichen\nlibrary(hexbin)  # stat_bin_hex ggplot2\n```\n:::\n\n\n::: callout-important\nAb diesem Kapitel benötigen Sie das R-Paket `rstanarm`. $\\square$\n:::\n\n### Benötigte Daten\n\nWir benötigen den Datensatz *!Kung*. Quelle der Daten ist @mcelreath2020 mit Bezug auf Howell.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nKung_path <-  \n  \"https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv\"  \n\nd <- read.csv(Kung_path) \n\nhead(d)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"height\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"weight\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"age\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"male\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"152\",\"2\":\"48\",\"3\":\"63\",\"4\":\"1\",\"_rn_\":\"1\"},{\"1\":\"140\",\"2\":\"36\",\"3\":\"63\",\"4\":\"0\",\"_rn_\":\"2\"},{\"1\":\"137\",\"2\":\"32\",\"3\":\"65\",\"4\":\"0\",\"_rn_\":\"3\"},{\"1\":\"157\",\"2\":\"53\",\"3\":\"41\",\"4\":\"1\",\"_rn_\":\"4\"},{\"1\":\"145\",\"2\":\"41\",\"3\":\"51\",\"4\":\"0\",\"_rn_\":\"5\"},{\"1\":\"164\",\"2\":\"63\",\"3\":\"35\",\"4\":\"1\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n[Datenquelle](https://raw.githubusercontent.com/sebastiansauer/2021-wise/main/Data/Howell1a.csv)\n\n{{< downloadthis data/Howell1a.csv dname=\"Howell1a\" >}}\n\n### Einstieg\n\n::: {#exm-gauss}\n### Was war noch mal eine Normalverteilung?\n\nIn diesem Kapitel benötigen Sie ein gutes Verständnis der Normalverteilung (die auch als Gauss-Verteilung bezeichnet wird). Fassen Sie daher die wesentlichen Aspekte der Normalverteilung (soweit im Unterricht behandelt) zusammen! $\\square$\n:::\n\n::: {#exm-post-gauss}\n### Was war noch mal eine Posteriori-Verteilung?\n\nIn diesem Kapitel befragen wir die Post-Verteilung für ein normalverteilte Zufallsvariable, nämlich die Körpergröße der !Kung San. Was war noch mal eine Post-Verteilung und wozu ist sie gut? $\\square$\n:::\n\n## Wie groß sind die !Kung San?\n\nDieser Abschnitt basiert auf @mcelreath2020, Kap. 4.3.\n\n### !Kung San\n\nIn diesem Abschnitt untersuchen wir eine Forschungsfrage in Zusammenhang mit dem Volk der !Kung, s. @fig-kungs.\n\n> The ǃKung are one of the San peoples who live mostly on the western edge of the Kalahari desert, Ovamboland (northern Namibia and southern Angola), and Botswana.The names ǃKung (ǃXun) and Ju are variant words for 'people', preferred by different ǃKung groups. This band level society used traditional methods of hunting and gathering for subsistence up until the 1970s. Today, the great majority of ǃKung people live in the villages of Bantu pastoralists and European ranchers.\n\n[Quelle](https://en.wikipedia.org/wiki/%C7%83Kung_people)\n\nWir interessieren uns für die Größe der erwachsenen !Kung, also filtern wir die Daten entsprechend und speichern die neue Tabelle als `d2`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd2 <- d %>% \n  filter(age >= 18)\n\nnrow(d2)\n## [1] 352\n```\n:::\n\n\n$N=352$.\n\nLassen wir uns einige typische deskriptive Statistiken zum Datensatz ausgeben. `{easystats`} macht das tatsächlich recht easy, s. @tbl-kung.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndescribe_distribution(d2)\n```\n:::\n\n\n\n::: {#tbl-kung .cell layout-align=\"center\" tbl-cap='Statistiken der metrischen Variablen im Kung-Datensatz'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qeayjdrzqo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qeayjdrzqo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qeayjdrzqo thead, #qeayjdrzqo tbody, #qeayjdrzqo tfoot, #qeayjdrzqo tr, #qeayjdrzqo td, #qeayjdrzqo th {\n  border-style: none;\n}\n\n#qeayjdrzqo p {\n  margin: 0;\n  padding: 0;\n}\n\n#qeayjdrzqo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qeayjdrzqo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qeayjdrzqo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qeayjdrzqo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qeayjdrzqo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qeayjdrzqo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qeayjdrzqo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qeayjdrzqo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qeayjdrzqo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qeayjdrzqo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qeayjdrzqo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qeayjdrzqo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qeayjdrzqo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qeayjdrzqo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qeayjdrzqo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qeayjdrzqo .gt_left {\n  text-align: left;\n}\n\n#qeayjdrzqo .gt_center {\n  text-align: center;\n}\n\n#qeayjdrzqo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qeayjdrzqo .gt_font_normal {\n  font-weight: normal;\n}\n\n#qeayjdrzqo .gt_font_bold {\n  font-weight: bold;\n}\n\n#qeayjdrzqo .gt_font_italic {\n  font-style: italic;\n}\n\n#qeayjdrzqo .gt_super {\n  font-size: 65%;\n}\n\n#qeayjdrzqo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qeayjdrzqo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qeayjdrzqo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qeayjdrzqo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qeayjdrzqo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qeayjdrzqo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qeayjdrzqo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qeayjdrzqo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qeayjdrzqo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Variable\">Variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Mean\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SD\">SD</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"IQR\">IQR</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Min\">Min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Max\">Max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Skewness\">Skewness</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Kurtosis\">Kurtosis</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_Missing\">n_Missing</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">height</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">154.60</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">7.74</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">12.06</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">136.53</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">179.07</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.15</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−0.48</td>\n<td headers=\"n\" class=\"gt_row gt_right\">352.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">weight</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">44.99</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">6.46</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">9.19</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">31.07</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">62.99</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.13</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−0.51</td>\n<td headers=\"n\" class=\"gt_row gt_right\">352.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">age</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">41.14</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">15.97</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">23.00</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">18.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">88.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.67</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−0.21</td>\n<td headers=\"n\" class=\"gt_row gt_right\">352.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">male</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">0.47</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">0.50</td>\n<td headers=\"IQR\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"Skewness\" class=\"gt_row gt_right\">0.13</td>\n<td headers=\"Kurtosis\" class=\"gt_row gt_right\">−2.00</td>\n<td headers=\"n\" class=\"gt_row gt_right\">352.00</td>\n<td headers=\"n_Missing\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nDie Verteilungen lassen sich mit `plot_density` (aus `{DataExplorer}`), s. @fig-kung-dens.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_density(d2)\n```\n\n::: {.cell-output-display}\n![Verteilungen der Variablen im Kung-Datensatz. Größe und Gewicht sind recht symmetrisch; Alter ist rechtsschief.](0800-gauss_files/figure-html/fig-kung-dens-1.png){#fig-kung-dens fig-align='center' width=75%}\n:::\n:::\n\n\n### Wir gehen apriori von normalverteilter Größe Der !Kung aus\n\n*Forschungsfrage:* Wie groß sind die erwachsenen !Kung im *Durchschnitt*?\n\nWir interessieren uns also für den Mittelwert der Körpergröße (erwachsene Person[^0800-gauss-1]), $\\mu$.\n\n[^0800-gauss-1]: Der Einfachheit halber gehen wir davon aus, dass Männer und Frauen im Schnitt gleich groß sind.\n\n![Mensch, [Wikimedia Commons](https://creativecommons.org/licenses/by-sa/3.0)[^0800-gauss-2]](img/human.png){width=\"5%\"}\n\n[^0800-gauss-2]: Bildquelle: Own alterations andFile:SVG_Human_With_All_Organs.svg by Madhero88, CC BY-SA, 3.0\n\n[^0800-gauss-3]: Bildquelle: Own alterations andFile:SVG_Human_With_All_Organs.svg by Madhero88, CC BY-SA, 3.0\n\nWir sind uns über diesen Mittelwert in der Population nicht sicher[^0800-gauss-4], und unsere Ungewissheit quantifizieren wir anhand einer Normalverteilung mit Mittelwert von 178 cm und Streuung von 20 cm, s. @eq-kung.\n\n[^0800-gauss-4]: Darum machen wir hier ja die ganz Show!\n\n\n$$\\mu \\sim \\mathcal{N}(178, 20)$$ {#eq-kung}\n\n\n@eq-kung definiert ein Modell: Unsere Vorstellung der mittleren (\"typischen\") Körpergröße der erwachsenen !Kung.\n\nWarum 178 cm? Kein besonderer Grund. Hier wollen wir den Effekt verschiedener Priori-Werte untersuchen.[^0800-gauss-5] In einer echten Untersuchung sollte man einen inhaltlichen Grund für einen Priori-Wert haben. *Oder* man wählt \"schwach informative\" Prioris, wie das `{rstanarm}` tut: Damit lässt man kaum Vorab-Information in das Modell einfließen, aber man verhindert extreme Prioris, die meistens unsinnig sind (so wie eine SD von 100 Metern bei der Körpergröße).\n\n[^0800-gauss-5]: Der Autor des zugrundeliegenden Fachbuchs, Richard McElreath gibt 178cm als seine Körpergröße an.\n\n::: callout-note\nWir haben zwar vorab nicht viel Wissen, aber auch nicht gar keines: Eine Gleichverteilung der Körpergrößen kommt nicht in Frage und ein vages Wissen zum Mittelwert haben wir auch. Darüber hinaus ist eine Normalverteilung nicht unplausibel.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Unser Gauss-Modell der !Kung\n\n📺 [Teil 1](https://youtu.be/cYHArln1DkM)\n\n### Modelldefinition\n\nWir nehmen an, dass die mittleren Größen, $\\mu$, und die tatsächlichen Größen, $h_i$, normalverteilt sind und $\\sigma$ exponentialverteilt ist (da notwendig positiv) ist:\n\nLikelihood: $h_i \\sim \\mathcal{N}(\\mu, \\sigma)$\n\nPrior für den Parameter $\\mu$: $\\mu \\sim \\mathcal{N}(178, 20)$\n\nPrior für den Parameter $\\sigma$: $\\sigma \\sim \\mathcal{E}(0, 0.1)$\n\nDaher: $95\\%KI( \\mu): 178 \\pm 40$\n\nIn @fig-kung-model sind unsere Priori-Verteilungen visualisiert.\n\n\n::: {#fig-kung-model .cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Priori der mittleren Körpergröße](0800-gauss_files/figure-html/fig-kung-model-1.png){#fig-kung-model-1 fig-align='center' width=75%}\n:::\n\n::: {.cell-output-display}\n![Priori der Schätzungenauigkeit](0800-gauss_files/figure-html/fig-kung-model-2.png){#fig-kung-model-2 fig-align='center' width=75%}\n:::\n\nPrioris unseres (ersten) Kung-Modells (`m_kung`)\n:::\n\n\n::: callout-note\nDieses Modell hat zwei Parameter, $\\mu$ und $\\sigma$. $\\square$\n:::\n\n### Priori gewichtet mit Likelihood ergibt Posteriori\n\nZu Erinnerung: Die Posteriori-Wahrscheinlichkeit ist das Ergebnis von Priori-Wahrscheinlichkeit und Likelihood.\n\nDie *Körpergrößen der einzelnen Personen* $h_i$ nehmen wir als normalverteilt an mit Mittelwert $\\mu$ und Streuung $\\sigma$:\n\n$$h_i \\sim \\mathcal{N}(\\color{blue}{\\mu},\\color{green}{\\sigma})   \\qquad{\\text{Likelihood}}$$\n\n### Prioris der Parameter\n\nDer Mittelwert der Körpergröße sei *normalverteilt* mit $\\mu=178$ und $\\sigma=20$:\n\n$$\\color{blue}{\\mu \\sim \\mathcal{N}(178, 20)} \\qquad{\\text{Prior}}$$\n\nDie Streuung $\\sigma$ der Größen sei *exponentialverteil* mit $\\lambda = 1/8$.\n\n$$\\color{green}{\\sigma \\sim \\mathcal{E}(1/8)} \\qquad{\\text{Prior}}$$\n\n### `m_kung`: fertig!\n\nJetzt haben wir unser Modell (`m_kung`) definiert!\n\nWeil es so schön ist, schreiben/zeichnen wir es hier noch einmal auf, @eq-mod-kung1, @fig-mod-kung1.\n\n$$\n\\begin{aligned}\nh_i &\\sim \\mathcal{N}(\\mu, \\sigma) & \\text{Likelihood}  \\\\\n\\mu &\\sim \\mathcal{N}(178, 20) & \\text{Prior} \\\\\n\\sigma &\\sim \\mathcal{E}(1/8) & \\text{Prior}\n\\end{aligned}\n$$ {#eq-mod-kung1}\n\n![Modellschema für das Modell `m_kung`](img/Kruschke-plot1.png){#fig-mod-kung1}\n\nZur Berechnung von `m_kung` nutzen wir jetzt dieses Mal aber *nicht* die Gittermethode (Bayes-Box), sondern lassen R die Arbeit verrichten.\n\nDa gibt es einen neuen Golem, ziemlich kräftig der Bursche, der soll die Arbeit für uns tun. Der Golem hört auf den Namen `rstanarm`[^0800-gauss-6].\n\n[^0800-gauss-6]: Hey, *ich* habe ihn diesen Namen nicht gegeben.\n\n::: {.content-visible when-format=\"html\"}\n## Zufällige Motivationsabschnitt\n\n![Gut gemacht!](img/pretty_good.gif){width=\"50%\"}\n:::\n\n## Posteriori-Verteilung des Größen-Modells, `m_kung`\n\nOkay, Golem, an die Arbeit! Berechne uns das Kung-Modell! Nennen wir das Modell `m_kung`[^0800-gauss-7].\n\n[^0800-gauss-7]: *m* wie Modell und 4, weil das Modell in Kapitel 4 von @mcelreath2020 in ähnlicher Form berichtet wird, und 1 weil es unsere erste Variante dieses Modells ist.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm_kung <- stan_glm(height ~ 1, data = d2, refresh = 0)  # <1>\nm41_post <- as_tibble(m_kung)    # <2>\nnames(m41_post) <- c(\"mu\", \"sigma\")  # <3>  \n```\n:::\n\n\n1.  Bayes-Regressionsmodell berechnen\n2.  Modellergebnis in Tabelle umwandeln\n3.  Schönere Namen für die Spalten geben\n\nDas Argument `refresh = 0` ist nur eine Nebensache, aber es ist praktisch, da es verhindert, dass die Details zum Ziehen der Stichproben am Bildschirm ausgegeben werden. Ich finde diese Ausgabe meist nicht informativ, so dass ich sie lieber unterdrücke. `stan_glm`[^0800-gauss-8] ist eine Funktion, mit der man Regressionsmodelle berechnen kann. Nun haben wir in diesem Fall kein \"richtiges\" Regressionsmodell. Man könnte sagen, wir haben eine AV (Körpergröße), aber keine UV (keine Prädiktoren). Glücklicherweise können wir auch solche \"armen\" Regressionsmodelle formulieren: `av ~ 1` bzw. in unserem Beispiel `height ~ 1` bedeutet, dass man nur die Verteilung der AV berechnen möchte, aber keine Prädiktoren hat (das soll die `1` symbolisieren). Für das Modell `m_kung` haben wir *keine* Prioris spezifiziert. Wir greifen damit auf die *Voreinstellung* (defaults) der Prioris von `rstanarm` zurück. Das ist ok, aber wenn Sie Vorab-Wissen haben, sollten Sie das an `rstanarm` weitergeben, weil es ja schade wäre, wenn Sie Wissen haben, das von Ihrem Modell nicht genutzt wird.\n\n[^0800-gauss-8]: aus dem R-Paket `rstanam`, das zuvor installiert und gestartet sein muss, bevor Sie den Befehl nutzen können\n\nPlotten wir mal die gemeinsame Posteriori-Verteilung von `m_kung`, s. @fig-m42-post-joint\n\n::: panel-tabset\n### Fliesendiagramm\n\nGemeinsame Post-Verteilung von Mittelwert und Streuung\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm41_post %>% \n  ggplot() +\n  aes(x = mu, y = sigma) %>% \n  geom_hex() +\n  scale_fill_viridis_c() \n```\n\n::: {.cell-output-display}\n![Die gemeinsame Post-Verteilung von Mittelwert und Streuung von m42](0800-gauss_files/figure-html/fig-m42-post-joint-1.png){#fig-m42-post-joint fig-align='center' width=75%}\n:::\n:::\n\n\nDa das Modell *zwei* Parameter hat, können wir auch beide gleichzeitig plotten. Wie man sieht, sind die beiden Parameter unkorreliert. In anderen Modellen können die Parameter korreliert sein.\n\n@fig-m42-post-joint erlaubt uns, für *jede Kombination von Mittelwert und Streuung* zu fragen, wie wahrscheinlich diese bestimmte Kombination ist.\n\n### Streudiagramm\n\nHier sind noch zwei andere Visualisierungen der Post-Verteilung von `m42`, s. @fig-m42-post-anders1.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Die Postverteilung in unterschiedlicher Darstellung](0800-gauss_files/figure-html/fig-m42-post-anders1-1.png){#fig-m42-post-anders1 fig-align='center' width=75%}\n:::\n:::\n\n\n### Histogramm\n\nUnd hier kommt die Post-Verteilung nur des Mittelwerts.\n\nNatürlich können wir auch nur von einem einzelnen Parameter (z.B. Mittelwert) die Verteilung untersuchen, s. @fig-m42-post-anders2.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Die Post-Verteilung von mu in m42; ein Balkendiagramm bietet sich an.](0800-gauss_files/figure-html/fig-m42-post-anders2-1.png){#fig-m42-post-anders2 fig-align='center' width=75%}\n:::\n:::\n\n:::\n\nFassen wir die Ergebnisse dieses Modells zusammen:\n\n-   Wir bekommen eine Wahrscheinlichkeitsverteilung für $\\mu$ und eine für $\\sigma$ (bzw. eine zweidimensionale Verteilung, für die $\\mu,\\sigma$-Paare).\n\n-   Trotz des eher vagen Priors ist die Streuung Posteriori-Werte für $\\mu$ und $\\sigma$ klein: Die große Stichprobe hat die Priori-Werte überstimmt.\n\n-   Ziehen wir Stichproben aus der Posteriori-Verteilung, so können wir interessante Fragen stellen.\n\n### Hallo, Posteriori-Verteilung\n\n... wir hätten da mal ein paar Fragen an Sie. 🕵\n\n1.  Mit welcher Wahrscheinlichkeit ist die *mittlere* !Kung-Person größer als 1,55m?\n2.  Welche mittlere Körpergröße wird mit 95% Wahrscheinlichkeit nicht überschritten, laut dem Modell?\n3.  In welchem 90%-PI liegt $\\mu$ vermutlich?\n4.  Mit welcher Unsicherheit ist die Schätzung der mittleren Körpergröße behaftet?\n5.  Was ist der mediane Schätzwert der mittleren Körpergröße, sozusagen der \"Best Guess\"?\n\nAntworten folgen etwas weiter unten.\n\nAbschließend, eigentlich nur Spielerei, noch eine andere Visualisierung der Post-Verteilung von $\\mu$ und von $\\sigma$, @fig-kung3.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Die beiden Randverteilungen der Post-Verteilungen, d.h. die Verteilungen für mu und für sigma](0800-gauss_files/figure-html/fig-kung3-1.png){#fig-kung3 fig-align='center' width=75%}\n:::\n:::\n\n\n### Posteriori-Stichproben mit `stan_glm()` berechnen\n\nMit `stan_glm()` können wir komfortabel die Posteriori-Verteilung berechnen. Die Gittermethode wird nicht verwendet, aber die Ergebnisse sind - in bestimmten Situationen - ähnlich. Es werden aber auch viele Stichproben simuliert (sog. MCMC-Methode). Gibt man keine Priori-Werte an, so greift die Funktion auf Standardwerte zurück.\n\nGrob gesagt berechnen wir die Post-Verteilung mit `stan_glm` so: `stan_glm(AV ~ UV, data = meine_daten)`.\n\nModelldefinition:\n\n$h_i \\sim \\mathcal{N}(\\mu, \\sigma)$, Likelihood\n\n$\\mu \\sim \\mathcal{N}(155, 19)$, Prior zum Größenmittelwert (von Stan übernommen)\n\n$\\sigma \\sim \\mathcal{E}(0.125)$, Prior zur Streuung der Größen (von Stan übernommen)\n\n### Ausgabe von `stan_glm()`\n\nWir können, wie wir es oben getan haben, uns die Stichproben der Post-Verteilung ausgeben lassen, und diese z.B. plotten.\n\nWir können es aber auch komfortabler haben ... Mit dem Befehl `parameters` kann man sich die geschätzten Parameterwerte einfach ausgeben lassen (s. @fig-m42-post-joint).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm_kung <- stan_glm(height ~ 1, data = d2, refresh = 0)  # aus Paket rstanarm\n\nparameters(m_kung)  # aus Paket `easystats`\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Parameter   | Median |           95% CI |   pd |  Rhat |  ESS |                    Prior |\n|:-----------|:------:|:----------------:|:----:|:-----:|:----:|:------------------------:|\n|(Intercept) | 154.60 | (153.76, 155.41) | 100% | 1.000 | 2655 | Normal (154.60 +- 19.36) |\n\n\n:::\n:::\n\n\nDas Wesentliche: Unser Golem schätzt den Größenmittelwert der Kung auf ca. 155cm bzw. auf einen Bereich von etwa 153.76 bis 155.41 schätzt. Informativ ist vielleicht noch, dass wir den `Prior` erfahren, der im Modell verwendet wurde. Dazu später mehr.\n\n::: callout-note\nIn dieser Ausgabe sind ein paar Angaben, die wir nicht verstehen, wie `pd`, `Rhat` und `ESS`. Kein Problem: Einfach ignorieren 🤓 Wer Näheres wissen will, findet [hier](https://easystats.github.io/easystats/) einen Anfang. Außerdem sei an @mcelreath2020 und @gelman2021 verwiesen. $\\square$\n:::\n\n## Wie tickt `stan_glm()`?\n\n\n::::: columns\n::: {.column width=\"20%\"}\n![](img/stanlogo.png){width=\"50%\"} [Quelle](https://mc-stan.org/)\n:::\n\n::: {.column width=\"80%\"}\nHier ein paar Kerninfos zu `stan_glm`:\n\n-   *Stan* ist eine Software zur Berechnung von Bayesmodellen; das Paket `rstanarm` stellt Stan für uns bereit.\n-   `stan_glm()` ist für die Berechnung von Regressionsmodellen ausgelegt.\n-   Will man nur die Verteilung einer Variablen (wie `heights`) schätzen, so hat man man ... eine Regression ohne Prädiktor.\n-   Eine Regression ohne Prädiktor schreibt man auf Errisch so: `y ~ 1`. Die `1` steht also für die nicht vorhandene UV; `y` meint die AV (`height`).\n-   `(Intercept)` (Achsenabschnitt) gibt den Mittelwert an.\n:::\n:::::\n\nMehr findet sich in der [Dokumentation von RstanArm](https://mc-stan.org/rstanarm/).\n\n### Schätzwerte zu den Modellparameter\n\nDie Parameter eines Modells sind die Größen, für die wir eine Priori-Verteilung annehmen. Außerdem wählen wir einen einen Likelihood-Funktion, so dass wir die Likelihood berechnen können. Auf dieser Basis schätzen wir dann die Post-Verteilung. Ich sage *schätzen*, um hervorzuheben, dass wir die wahren Werte nicht kennen, sondern nur eine Vermutung haben, unsere Ungewissheit vorab also (wie immer) in der Priori-Verteilung festnageln und unsere Ungewissheit nach Kenntnis der Daten in der Posteriori-Verteilung quantifizieren. Wie gerade gesehen, lassen sich die Modellparameter (bzw. genauer gesagt deren Schätzungen) einfach mit `parameters(modellname)` auslesen.\n\n### Stichproben aus der Posteriori-Verteilung ziehen\n\nWie wir es vom Globusversuch gewohnt sind, können wir aber auch Stichproben aus der Post-Verteilung ziehen.\n\nHier die ersten paar Zeilen von `post_m41`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npost_m41 <- as_tibble(m_kung)\nhead(post_m41)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"(Intercept)\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"154\",\"2\":\"7.7\"},{\"1\":\"154\",\"2\":\"7.3\"},{\"1\":\"154\",\"2\":\"8.4\"},{\"1\":\"154\",\"2\":\"7.9\"},{\"1\":\"155\",\"2\":\"8.1\"},{\"1\":\"155\",\"2\":\"7.7\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nIn einer Regression ohne Prädiktoren entspricht der Achsenabschnitt dem Mittelwert der AV, daher gibt uns die Spalte `(Intercept)` Aufschluss über unsere Schätzwerte zu $\\mu$ (der Körpergröße).\n\n:::: {#exr-kung1}\n## Mit welcher Wahrscheinlichkeit ist $\\mu>155$?\n\n::: {.callout-tip appearance=\"minimal\" collapse=\"true\"}\n### Lösung\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n\nnames(post_m41) <- \n  c(\"mu\", \"sigma\")  # den Namen \"(Intercept)\" durch \"mu\" ersetzen, ist prägnanter\n\npost_m41 %>% \n  count(mu > 155) %>% \n  mutate(prop = n/sum(n))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"mu > 155\"],\"name\":[1],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"prop\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"FALSE\",\"2\":\"3320\",\"3\":\"0.83\"},{\"1\":\"TRUE\",\"2\":\"680\",\"3\":\"0.17\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nDie Wahrscheinlichkeit ist nicht hoch, aber nicht auszuschließen, dass die Kung im Schnitt größer als 155 cm sind. Wahrscheinlicher ist jedoch, dass sie kleiner als 155 cm sind. $\\square$\n:::\n::::\n\n:::: {#exr-kung2}\n## Mit welcher Wahrscheinlichkeit ist $\\mu>165$?\n\n::: {.callout-tip appearance=\"minimal\" collapse=\"true\"}\n### Lösung\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnames(post_m41) <- \n  c(\"mu\", \"sigma\")  # den Namen \"(Intercept)\" durch \"mu\" ersetzen, ist prägnanter\n\npost_m41 %>% \n  count(mu > 165) %>% \n  mutate(prop = n/sum(n))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"mu > 165\"],\"name\":[1],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"prop\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"FALSE\",\"2\":\"4000\",\"3\":\"1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nOh, diese Hypothese können wir mit an Sicherheit grenzender Wahrscheinlichkeit ausschließen. Aber Achtung: Das war eine Kleine-Welt-Aussage! Die Wahrscheinlichkeit, die Hypothese $\\mu > 165$ auszuschließen ist *nur* dann hoch, wenn das Modell gilt! Wenn also der Golem keinen Mist gebaut hat. Und sind wir mal ehrlich, der Golem tut, was sein:e Herr:in und Meister:in ihm befiehlt. Letztlich liegt es an uns, den Golem auf Spur zu kriegen.\n:::\n::::\n\n:::: {#exm-kung3}\n## Welche mittlere Körpergröße wird mit 95% Wahrscheinlichkeit nicht überschritten, laut dem Modell `m_kung`?\n\n::: {.callout-tip appearance=\"minimal\" collapse=\"true\"}\n### Lösung\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npost_m41 %>% \n  summarise(q95 = quantile(mu, .95))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"q95\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"155\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n:::\n::::\n\n:::: {#exr-kung4}\n## In welchem 90%-PI liegt $\\mu$ vermutlich?\n\n::: {.callout-tip appearance=\"minimal\" collapse=\"true\"}\n### Lösung\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npost_m41 %>% \n  eti()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Parameter\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"CI\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_low\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"CI_high\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"mu\",\"2\":\"0.95\",\"3\":\"153.8\",\"4\":\"155.4\"},{\"1\":\"sigma\",\"2\":\"0.95\",\"3\":\"7.2\",\"4\":\"8.4\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nEin ETI ist synonym zu PI.\n:::\n::::\n\n:::: {#exr-kung5}\n## Mit welcher Unsicherheit ist die Schätzung der mittleren Körpergröße behaftet?\n\n::: {.callout-tip appearance=\"minimal\" collapse=\"true\"}\n### Lösung\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm_kung %>% \n  parameters()\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Parameter   | Median |           95% CI |   pd |  Rhat |  ESS |                    Prior |\n|:-----------|:------:|:----------------:|:----:|:-----:|:----:|:------------------------:|\n|(Intercept) | 154.60 | (153.76, 155.41) | 100% | 1.000 | 2655 | Normal (154.60 +- 19.36) |\n\n\n:::\n:::\n\n\nSeeing is believing, s. @fig-m_kung-params-intercept.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm_kung %>% \n  parameters() %>% \n  plot(show_intercept = TRUE)\n```\n\n::: {.cell-output-display}\n![Parameter von m_kung, nur einer: der Intercept](0800-gauss_files/figure-html/fig-m_kung-params-intercept-1.png){#fig-m_kung-params-intercept fig-align='center' width=75%}\n:::\n:::\n\n\nDas Modell ist sich recht sicher: die Ungewissheit der mittleren Körpergröße liegt bei nicht viel mehr als einem Zentimeter (95%-CI).\n:::\n::::\n\n:::: {#exr-kung6}\n## Was ist der mediane Schätzwert der mittleren Körpergröße, sozusagen der \"Best Guess\"?\n\n::: {.callout-tip appearance=\"minimal\" collapse=\"true\"}\n### Lösung\n\n`parameters(m_kung)` hat uns die Antwort schon gegeben: Ca. 155 cm.\n:::\n::::\n\n🏋️ Ähnliche Fragen bleiben als Übung für die Lesis. 🤓\n\n### Standard-Prioriwerte bei `stan_glm()`\n\n`stan_glm()` nimmt für uns Priori-Wert an. Welche das sind, kann man sich so anzeigen lassen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprior_summary(m_kung)\n## Priors for model 'm_kung' \n## ------\n## Intercept (after predictors centered)\n##   Specified prior:\n##     ~ normal(location = 155, scale = 2.5)\n##   Adjusted prior:\n##     ~ normal(location = 155, scale = 19)\n## \n## Auxiliary (sigma)\n##   Specified prior:\n##     ~ exponential(rate = 1)\n##   Adjusted prior:\n##     ~ exponential(rate = 0.13)\n## ------\n## See help('prior_summary.stanreg') for more details\n```\n:::\n\n\n`stan_glm()` verwendet (in der Voreinstellung) *schwach informative* Priori-Werte, die nur wenig Vorabwissen in das Modell geben. Es werden dafür die Stichproben-Daten als Priori-Daten verwendet: Mittelwerte und Streuungen der AV werden als Grundlage für die Priori-Verteilungen herangezogen. Strenggenommen ist das nicht \"pures Bayes\", weil die Priori-Werte ja *vorab*, also vor Kenntnis der Daten bestimmt werden sollen. Bitte reichen Sie Ihre Beschwerden bei Andrew Gelman ein.\n\nMan sollte diese Standardwerte als Minimalvorschlag sehen. Kennt man sich im Sachgebiet aus, kann man meist bessere Prioris finden. Die Voreinstellung ist nicht zwingend; andere Werte wären auch denkbar.\n\n::: callout-note\n### Standardwerte von `stan_glm`\n\n-   `Intercept`: $\\mu$, der Mittelwert der Verteilung $Y$\n    -   $\\mu \\sim \\mathcal{N}(\\bar{Y}, sd(Y)\\cdot 2.5)$\n    -   als Streuung von $\\mu$ wird die 2.5-fache Streuung der Stichprobe (für $Y$) angenommen.\n-   `Auxiliary (sigma)`: $\\sigma$, die Streuung der Verteilung $Y$\n    -   $\\sigma \\sim \\mathcal{E}(\\lambda=1/sd(Y))$\n    -   als \"Streuung\", d.h. $\\lambda$ von $h_i$ wird $\\frac{1}{sd(Y)}$ angenommen. $\\square$\n:::\n\nEine sinnvolle Strategie ist, einen Prior so zu wählen, dass man nicht übergewiss ist, also nicht zu sicher Dinge behauptet, die dann vielleicht doch passieren (also die Ungewissheit zu gering spezifiziert), andererseits sollte man extreme, unplausible Werte ausschließen.\n\n::: callout-important\nBei der Wahl der Prioris gibt es nicht die eine, richtige Wahl. Die beste Entscheidung ist auf transparente Art den Stand der Forschung einfließen zu lassen und eigene Entscheidungen zu begründen. Häufig sind mehrere Entscheidungen möglich. Möchte man lieber vorsichtig sein, weil man wenig über den Gegenstand weiß, dann könnte man z.B. auf die Voreinstellung von `rstanarm` vertrauen, die \"schwachinformativ\" ist, also nur wenig Priori-Information in das Modell einfließen lässt.\n:::\n\n### Wenn es schnell gehen muss\n\n`stan_glm()` ist deutlich langsamer als z.B. der befreundete Golem `lm()`. Der Grund für Stans Langsamkeit ist, dass er viele Stichproben zieht, also viel zu zählen hat. Außerdem wiederholt er das Stichprobenziehen (im Standard) 4 Mal, damit sein Meister prüfen kann, ob er (Stan) die Arbeit auch immer richtig gemacht hat. Die Idee dabei ist, wenn alle vier Durchführungen (auch \"Ketten\" engl., chains) genannt, zum etwa gleichen Ergebnis kommen, dann wird schon alles mit rechten Dingen zugegangen sein. Weichen die Ergebnisse der 4 Ketten voneinander ab, so ist Stan ein Fehler unterlaufen, oder, irgendetwas ist \"dumm gelaufen\". An dieser Stelle schauen wir uns die Ketten nicht näher an, aber es sei notiert, dass man die Anzahl der Ketten mit dem Argument `chains` steuern kann. Möchte man, dass Stan sich beeilt, so kann man `chains = 1` setzen, das spart Zeit.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm41a <- stan_glm(height ~ 1, \n                 data = d2, \n                 chains = 1,  # nur 1 Kette, anstelle von 4 im Default, spart Zeit\n                 refresh = 0) \n\nparameters(m41a)  \n```\n:::\n\n\n## Modell `m42`: unsere Priori-Werte\n\n📺 [Teil 2](https://youtu.be/qIuu-4qRT_0)\n\nIm Modell `m_kung` haben wir auf die Priori-Werte der Voreinstellung von `rstanarm` vertraut. Jetzt lassen wir mal unsere eigenen Priori-Werte einfließen, in unserem zweiten Kung-Modell, `m42`.\n\n### m42\n\nDann lassen wir `stan_glm()` (Stan) unser zweites Modell berechnen.[^0800-gauss-9] Dieses Mal geben wir die Priori-Werte explizit an, @tbl-m42-params.\n\n[^0800-gauss-9]: Hey Stan, los, an die Arbeit!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm42 <- \n  stan_glm(height ~ 1, \n           prior_intercept = normal(178, 20),  # mu\n           prior_aux = exponential(0.125),  # sigma\n           refresh = FALSE,  # bitte nicht so viel Ausgabe drucken\n           data = d2)\nparameters(m42)\n```\n:::\n\n\n\n::: {#tbl-m42-params .cell layout-align=\"center\" tbl-cap='Parameter von m42 mit eigenen Prioriwerten'}\n::: {.cell-output-display}\n\n\n|Parameter   | Median |           95% CI |   pd |  Rhat |     ESS |              Prior |\n|:-----------|:------:|:----------------:|:----:|:-----:|:-------:|:------------------:|\n|(Intercept) | 154.62 | (153.83, 155.42) | 100% | 1.000 | 2482.00 | Normal (178 +- 20) |\n\n\n:::\n:::\n\n\nWir haben noch nicht alle Informationen kennengelernt, die in @tbl-m42-params ausgegeben werden. Im Zweifel: Einfach ignorieren. Wichtige Fähigkeit im Studium. 🤓\n\n::: callout-important\nVergleichen Sie die Parameterwerte von `m_kung` und `m42`! Was fällt Ihnen auf? Nichts? Gut! Tatsächlich liefern beide Modelle sehr ähnliche Parameterwerte. Die Prioriwerte waren nicht so wichtig, weil wir genug Daten haben. Hat man einigermaßen viele Daten, so fallen Prioriwerte nicht mehr ins Gewicht, zumindest wenn sie moderat gewählt waren.\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n### Posteriori-Verteilung und Parameter plotten\n\nLeider liefert der Stan-Golem leider keinen braven Tibble (Tabelle) zurück.\n\n> 👨‍🏫 Böser Golem!\n\n> 🤖 Beim nächsten Mal strenge ich mich mehr an!\n\nDaher müssen wir die Ausgabe des Stan-Golemns erst in eine schöne Tabelle umwandeln:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm42_tibble <-\n  as_tibble(m42)\n\nhead(m42_tibble)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"(Intercept)\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"155\",\"2\":\"7.4\"},{\"1\":\"155\",\"2\":\"7.5\"},{\"1\":\"155\",\"2\":\"7.7\"},{\"1\":\"155\",\"2\":\"7.7\"},{\"1\":\"154\",\"2\":\"7.5\"},{\"1\":\"155\",\"2\":\"7.8\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nAußerdem ist der Name der ersten Spalte eigentlich unzulässig, da Spaltennamen in R nicht mit Sonderzeichen anfangen dürfen (sondern mit Buchstaben). Daher müssen wir den Namen mit \"Samthandschuhen\" anpacken. Auf Errisch sind das die Backticks, die wir um den Namen rumwickeln müssen, s. die folgende Syntax.\n\n::: panel-tabset\n### Mit `{ggpubr}`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm42_tibble |> \n  gghistogram(x = \"`(Intercept)`\")  # Aus dem Paket \"ggpubr\"\n```\n\n::: {.cell-output-display}\n![](0800-gauss_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n### Mit `{ggplot}`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm42_tibble |> \n  ggplot(aes(x = `(Intercept)`)) +  # Aus dem Paket `ggplot2`\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](0800-gauss_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=75%}\n:::\n:::\n\n:::\n\nAls Ausblick: Ein Vergleich mehrerer Priori-Werte wäre auch nützlich, um ein skeptisches Publikum von der Wahl (bzw. der Indifferenz) der gewählten Priori-Werte zu überzeugen.\n\n### Welche Körpergrößen erwartet unser Modell\n\nBisher haben wir untersucht, wie die Verteilung der *mittleren* Körpergrößen, $\\mu$, laut unserem Modell aussehen könnte; wir haben uns also mit der Post-Verteilung von $\\mu$ beschäftigt. Wir könnten aber auch an der Frage der Verteilung der *tatsächlichen* Körpergrößen, $h_i$, laut Modell, interessiert sein: Wie groß sind sie denn, die !Kung, laut unserem Modell?\n\nWie wir wissen, liefert unser Stan-Golem eine *Stichproben-Postverteilung*. Wenn wir das Ergebnisobjekt unserer Analyse, `m_kung` in eine Tabelle (Tibble) umwandeln und (die ersten paar Zeilen) betrachen, sehen wir diese Stichproben:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm_kung |> as_tibble() |> head()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"(Intercept)\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sigma\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"154\",\"2\":\"7.7\"},{\"1\":\"154\",\"2\":\"7.3\"},{\"1\":\"154\",\"2\":\"8.4\"},{\"1\":\"154\",\"2\":\"7.9\"},{\"1\":\"155\",\"2\":\"8.1\"},{\"1\":\"155\",\"2\":\"7.7\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nLaut unserem Modell sind die Körpergrößen, $h_i$, normalverteilt mit $\\mu$ und $\\sigma$. $\\mu$ wird von Stan, der in Begriffen der Regressionsanalyse denkt, schnöde als `(Intercept)` bezeichnet. Wir könnten jetzt also für jede Zeile eine Normalverteilung berechnen. Und daraus zufällig eine Zahl ziehen. Damit hätten wir dann unsere Verteilung von Körpergrößen laut Modell. Diese Verteilung nennt man auch *Posterior-Prädiktiv-Verteilung*. Prädiktiv daher, weil sie die Werte der Körpergrößen \"vorhersagt\".\n\nWir können uns diese Verteilung auch komfortabel von R ausgeben lassen, s. @fig-ppcheck.\n\n\n::: {#fig-ppcheck .cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\npp_check(m_kung)\npp_check(m_kung, \"stat\")\n```\n\n::: {.cell-output-display}\n![Die dunkle, dicke Dichtekurve zeigt die tatsächliche Verteilung der Körpergrößen im Datensatz. Die hellen, leichten Dichtekurven zeigen die Verteilungen laut der Post-Verteilung unseres Modells.](0800-gauss_files/figure-html/fig-ppcheck-1.png){#fig-ppcheck-1 fig-align='center' width=75%}\n:::\n\n::: {.cell-output-display}\n![Der wahre Wert einer Test-Statistik (T), hier der Mittelwert der Körpergrößen, wird mit der Verteilung der Körpergrößen in Bezug gesetzt.](0800-gauss_files/figure-html/fig-ppcheck-2.png){#fig-ppcheck-2 fig-align='center' width=75%}\n:::\n\nDie Posterior-Prädiktiv-Verteilung: Die Verteilung der tatsächlichen Körpergrößen auf Basis der Post-Verteilung. Unser Modell stellt die tatsächliche Verteilung ganz gut nach.\n:::\n\n\n## Fazit\n\n<!-- TODO: Die neuen Infosder Gauss-Modelle auf die formel von Bayes Theorem zurückühren. -->\n\n### Zusammenfassung\n\nWir haben die Posteriori-Verteilung für ein Gauss-Modell berechnet. Dabei hatten wir ein einfaches Modell mit metrischer Zielvariablen, ohne Prädiktoren, betrachtet. Die Zielvariable, Körpergröße (`height`), haben wir als normalverteilt mit den Parametern $\\mu$ und $\\sigma$ angenommen. Für $\\mu$ und $\\sigma$ haben wir jeweils keinen einzelnen (fixen) Wert angenommen, sondern eine Wahrscheinlichkeitsverteilung, der mit der Priori-Verteilung für $\\mu$ bzw. $\\sigma$ festgelegt ist.\n\n### Botschaft von einem Statistiker\n\n![🧡 Bleiben Sie dran!](img/chicken_standard_deviation.jpg)\n\n::: callout-important\nKontinuierliches Lernen ist der Schlüssel zum Erfolg.\n:::\n\n## Vertiefung: Wahl der Priori-Werte\n\n🏎️ Dieser Abschnitt ist eine VERTIEFUNG und nicht prüfungsrelevant. 🏎\n\n### Welche Beobachtungen sind auf Basis unseres Modells zu erwarten?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn <- 1e4\n\nsim <- tibble(sample_mu  = \n      rnorm(n, \n            mean = 178, \n            sd   = 20),\n    sample_sigma = \n      rexp(n, \n            rate = 0.1)) %>% \n  mutate(height  = \n      rnorm(n, \n            mean = sample_mu, \n            sd   = sample_sigma))\n\nheight_sim_sd <- \n  sd(sim$height) %>% round()\nheight_sim_mean <- \n  mean(sim$height) %>% round()\n\n```\n:::\n\n\n💭 Was denkt der Golem (`m_kung`) *apriori* von der Größe der !Kung?\n\n🦾 Ziehen wir mal ein paar Stichproben auf Basis des Modells. Voilà:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np3 <- \n  sim %>% \n  ggplot(aes(x = height)) +\n  geom_density(fill = \"grey33\") +\n  scale_x_continuous(breaks = c(0, 178-3*height_sim_sd, 178, 178+3*height_sim_sd)) +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"height ~ dnorm(mu, sigma)\",\n       caption = \"X-Achse zeigt MW±3SD\",\n       x = \"Größe\") +\n  theme(panel.grid = element_blank()) \n\np3\n```\n\n::: {.cell-output-display}\n![](0800-gauss_files/figure-html/Kung-12-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n[Quellcode](https://bookdown.org/content/4857/geocentric-models.html#a-gaussian-model-of-height)\n\n### Priori-Werte prüfen mit der Priori-Prädiktiv-Verteilung\n\n-   Die Priori-Prädiktiv-Verteilung (`sim`) simuliert Beobachtungen (nur) auf Basis der Priori-Annahmen: $h_i \\sim \\mathcal{N}(\\mu, \\sigma),$ $\\mu \\sim \\mathcal{N}(178, 20),$ $\\sigma \\sim \\mathcal{E}(0.1)$\n-   So können wir prüfen, ob die Priori-Werte vernünftig sind.\n\nDie Priori-Prädiktiv-Verteilung zeigt, dass unsere Priori-Werte ziemlich vage sind, also einen zu breiten Bereich an Größenwerten zulassen:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np3\n```\n\n::: {.cell-output-display}\n![](0800-gauss_files/figure-html/Kung-13-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nAnteil $h_i > 200$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanteil_großer_kung <- \nsim %>% \n  count( height > 200) %>% \n  mutate(prop = n/sum(n))\nanteil_großer_kung\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"height > 200\"],\"name\":[1],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"prop\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"FALSE\",\"2\":\"8313\",\"3\":\"0.83\"},{\"1\":\"TRUE\",\"2\":\"1687\",\"3\":\"0.17\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[5],\"max\":[5]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n🤔 Sehr große Buschleute? 17 Prozent sind größer als 2 Meter. Das ist diskutabel, muss aber nicht zwangsläufig ein schlechter Prior sein.\n\n### Vorhersagen der Priori-Werte\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](0800-gauss_files/figure-html/Kung-15-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n### Extrem vage Priori-Verteilung für die Streuung?\n\n$$\\sigma \\sim \\mathcal{E}(\\lambda=0.01)$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](0800-gauss_files/figure-html/Kung-16-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nDie Streuung der Größen ist weit:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd <- \n  tibble(x = seq(0,75, by =.01),\n         y = dexp(x, rate = .01))\n\nd %>% \n  ggplot(aes(x,y)) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](0800-gauss_files/figure-html/Kung-3-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n🤔 Das Modell geht apriori von ein paar Prozent Menschen mit *negativer* Größe aus. Ein Haufen Riesen 👹 werden auch erwartet.\n\n🤯 Vage (flache, informationslose, \"neutrale\", \"objektive\") Priori-Werte machen oft keinen Sinn, weil sie extreme, unplausible Werte zulassen.\n\n## Aufgaben\n\n### Papier-und-Bleistift-Aufgaben\n\n<!-- 3. [ReThink4e3](https://datenwerk.netlify.app/posts/ReThink4e3/ReThink4e3.html) -->\n\n1.  [exp-tab](https://datenwerk.netlify.app/posts/exp-tab/)\n2.  [exp-tab2](https://datenwerk.netlify.app/posts/exp-tab2/)\n3.  [norms-sd](https://datenwerk.netlify.app/posts/norms-sd/)\n4.  [small-wide-normal](https://datenwerk.netlify.app/posts/small-wide-normal/)\n5.  [exp1](https://datenwerk.netlify.app/posts/exp1/)\n6.  [distros](https://datenwerk.netlify.app/posts/distros/)\n7.  [mtcars-post_paper](https://datenwerk.netlify.app/posts/mtcars-post_paper/)\n8.  [groesse03](https://datenwerk.netlify.app/posts/groesse03/)\n9.  [pupil-size2](https://datenwerk.netlify.app/posts/pupil-size2/)\n10. [groesse04](https://datenwerk.netlify.app/posts/groesse04/)\n11. [ReThink4e2](https://datenwerk.netlify.app/posts/ReThink4e2/ReThink4e2.html)\n12. [Priorwahl1](https://datenwerk.netlify.app/posts/Priorwahl1/Priorwahl1.html)\n\n### Aufgaben, für die man einen Computer benötigt\n\n1.  [stan_glm01](https://datenwerk.netlify.app/posts/stan_glm01/stan_glm01.html)\n2.  [ReThink4e1](https://datenwerk.netlify.app/posts/rethink4e1/rethink4e1)\n3.  [ReThink4e3](https://datenwerk.netlify.app/posts/rethink4e3/rethink4e3)\n4.  [Kung-height](https://datenwerk.netlify.app/posts/kung-height/kung-height)\n5.  [Pupil-size](https://datenwerk.netlify.app/posts/pupil-size/pupil-size)\n6.  [IQ-Studentis](https://datenwerk.netlify.app/posts/iq-studentis/iq-studentis)\n7.  [Priori-Streuung](https://datenwerk.netlify.app/posts/priori-streuung/priori-streuung)\n\n## ---\n\n![](img/outro-08.jpg){width=\"100%\"}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}