{
  "hash": "27354c60476972a7377563efa20a3e4e",
  "result": {
    "markdown": "# Lineare Modelle\n\n\nIn diesem Kapitel benötigen Sie folgende R-Pakete.\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-1_5f0b6096177ec2436bb0b460f32c42cc'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(easystats)\nlibrary(rstanarm)\n```\n:::\n\n\n\n\n\n\n## Post-Verteilung der Regression\n\n\n### Einfache Regression\n\n\n\nDie (einfache) Regression prüft, inwieweit zwei Variablen, $Y$ und $X$ linear zusammenhängen.\nJe mehr sie zusammenhängen, desto besser kann man $X$ nutzen, um $Y$ vorherzusagen (und umgekehrt).\nHängen $X$ und $Y$ zusammen, heißt das nicht (unbedingt), dass es einen *kausalen* Zusammenhang zwischen $X$ und $Y$ gibt.\nLinear bedeutet, der Zusammenhang ist additiv und konstant: wenn $X$ um eine Einheit steigt, steigt $Y$ immer um $b$ Einheiten (nicht kausal, sondern deskriptiv gemeint).\n\n[Datenquelle](https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv), @mcelreath_statistical_2020.\n\nLaden wir die Daten und visualisieren wir uns den Zusammenhang.\n\n\n\n::: {.cell fig.asp='0.5' hash='lineare-modelle_cache/html/Post-Regression-2_e6b68585d8ccf4d79963321c0ac2694b'}\n\n```{.r .cell-code}\nKung_path <- \"https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv\"\n\nd <- read_csv(Kung_path)  \n\nd2 <- \n  d %>% \n  filter(age > 18) \n\nd2 %>% \n  #select(weight, height) %>% \n  #drop_na() %>% \n  ggplot(\n       aes(x = weight, y = height)) +\n  geom_point(alpha = .7) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-2-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n### Bei jedem Prädiktorwert eine Post-Verteilung für $\\mu$\n\n\nUnser Modell erlaubt uns für jeden beliebigen Wert des Prädiktors eine Post-Verteilung (von $mu$) zu berechnen.\n\nHier am Beispiel von `m42`: \n\n\n::: {.cell hash='lineare-modelle_cache/html/m42-read-from-disk_57177e4eaab260fccbd4c4f370dec730'}\n\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-10_36b6d41e08ea177410066f088f6ee17b'}\n\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-11_540dd945b64e28d4accc979bf6e4fde0'}\n\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/m3_f370ae9f3350cdd2bb8203aa46496877'}\n\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-2_9990246c4467211bc59c13f52151744a'}\n\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/m43-plot_6a7c166e1f92917fce226b91e184b5f2'}\n\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-12_a9c49c937e7acc079b671e4155bde183'}\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-12-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n\n### Statistiken zum !Kung-Datensatz\n\n[Datenquelle](https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv)\n\n\nHier sind die zentralen deskriptiven Statistiken zum !Kung-Datensatz.\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-3_5ac105b9a3e02230d99107e44c30f4ae'}\n\n```{.r .cell-code}\nKung_path <- \"https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv\"  \nd <- read_csv(Kung_path)  \n\nd2 <- d %>% filter(age > 18)\n\ndescribe_distribution(d2)\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-4_ceaaffc5b0ca5488a6a3b02c0f3f228a'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"huffblxjde\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#huffblxjde .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#huffblxjde .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#huffblxjde .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#huffblxjde .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#huffblxjde .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#huffblxjde .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#huffblxjde .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#huffblxjde .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#huffblxjde .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#huffblxjde .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#huffblxjde .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#huffblxjde .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#huffblxjde .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#huffblxjde .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#huffblxjde .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#huffblxjde .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#huffblxjde .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#huffblxjde .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#huffblxjde .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#huffblxjde .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#huffblxjde .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#huffblxjde .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#huffblxjde .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#huffblxjde .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#huffblxjde .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#huffblxjde .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#huffblxjde .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#huffblxjde .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#huffblxjde .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#huffblxjde .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#huffblxjde .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#huffblxjde .gt_left {\n  text-align: left;\n}\n\n#huffblxjde .gt_center {\n  text-align: center;\n}\n\n#huffblxjde .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#huffblxjde .gt_font_normal {\n  font-weight: normal;\n}\n\n#huffblxjde .gt_font_bold {\n  font-weight: bold;\n}\n\n#huffblxjde .gt_font_italic {\n  font-style: italic;\n}\n\n#huffblxjde .gt_super {\n  font-size: 65%;\n}\n\n#huffblxjde .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#huffblxjde .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#huffblxjde .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#huffblxjde .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#huffblxjde .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#huffblxjde .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#huffblxjde .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">q1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">q3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">iqr</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">mad</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">sd</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">se</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">ci</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">age</td>\n<td class=\"gt_row gt_right\">346.0</td>\n<td class=\"gt_row gt_right\">19.0</td>\n<td class=\"gt_row gt_right\">88.0</td>\n<td class=\"gt_row gt_right\">40.0</td>\n<td class=\"gt_row gt_right\">29.0</td>\n<td class=\"gt_row gt_right\">51.0</td>\n<td class=\"gt_row gt_right\">22.0</td>\n<td class=\"gt_row gt_right\">16.3</td>\n<td class=\"gt_row gt_right\">41.5</td>\n<td class=\"gt_row gt_right\">15.8</td>\n<td class=\"gt_row gt_right\">0.8</td>\n<td class=\"gt_row gt_right\">1.7</td></tr>\n    <tr><td class=\"gt_row gt_left\">height</td>\n<td class=\"gt_row gt_right\">346.0</td>\n<td class=\"gt_row gt_right\">136.5</td>\n<td class=\"gt_row gt_right\">179.1</td>\n<td class=\"gt_row gt_right\">154.3</td>\n<td class=\"gt_row gt_right\">148.6</td>\n<td class=\"gt_row gt_right\">160.7</td>\n<td class=\"gt_row gt_right\">12.1</td>\n<td class=\"gt_row gt_right\">8.5</td>\n<td class=\"gt_row gt_right\">154.6</td>\n<td class=\"gt_row gt_right\">7.8</td>\n<td class=\"gt_row gt_right\">0.4</td>\n<td class=\"gt_row gt_right\">0.8</td></tr>\n    <tr><td class=\"gt_row gt_left\">male</td>\n<td class=\"gt_row gt_right\">346.0</td>\n<td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">1.0</td>\n<td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">1.0</td>\n<td class=\"gt_row gt_right\">1.0</td>\n<td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">0.5</td>\n<td class=\"gt_row gt_right\">0.5</td>\n<td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">0.1</td></tr>\n    <tr><td class=\"gt_row gt_left\">weight</td>\n<td class=\"gt_row gt_right\">346.0</td>\n<td class=\"gt_row gt_right\">31.5</td>\n<td class=\"gt_row gt_right\">63.0</td>\n<td class=\"gt_row gt_right\">45.0</td>\n<td class=\"gt_row gt_right\">40.3</td>\n<td class=\"gt_row gt_right\">49.4</td>\n<td class=\"gt_row gt_right\">9.0</td>\n<td class=\"gt_row gt_right\">6.7</td>\n<td class=\"gt_row gt_right\">45.0</td>\n<td class=\"gt_row gt_right\">6.5</td>\n<td class=\"gt_row gt_right\">0.3</td>\n<td class=\"gt_row gt_right\">0.7</td></tr>\n    <tr><td class=\"gt_row gt_left\">weight_c</td>\n<td class=\"gt_row gt_right\">346.0</td>\n<td class=\"gt_row gt_right\">−13.5</td>\n<td class=\"gt_row gt_right\">17.9</td>\n<td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">−4.7</td>\n<td class=\"gt_row gt_right\">4.3</td>\n<td class=\"gt_row gt_right\">9.0</td>\n<td class=\"gt_row gt_right\">6.7</td>\n<td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">6.5</td>\n<td class=\"gt_row gt_right\">0.3</td>\n<td class=\"gt_row gt_right\">0.7</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\nDas mittlere Körpergewicht (`weight`) liegt bei ca. 45kg (sd 7 kg).\n\n\n### Etwas mehr EDA\n\n\n\n\nWir brauchen die EDA hier nicht wirklich, aber es ist praktisch. Das Paket `DataExplorer` hat ein paar nette Hilfen zur explorativen Datenanalyse.\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-3_9c1e2f6a07c003bb8524f54e787cc085'}\n\n```{.r .cell-code}\nlibrary(DataExplorer)\n```\n:::\n\n\n#### Gibt es fehlende Werte?\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-4_08d65f7a60293fc3bf1cc9da00018b2c'}\n\n```{.r .cell-code}\nd2 %>% plot_missing()\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n#### Verteilung der numerischen Variablen\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-5_3300ecf73041dc4c5e2ac348c1312375'}\n\n```{.r .cell-code}\nd2 %>% plot_histogram()\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n#### Verteilung der kategorialen Variablen\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-6_17354d75109255b30004eab494f35e0a'}\n\n```{.r .cell-code}\nd2 %>% plot_bar()\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n#### Korrelationen\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-7_dc5007fbe32aa1754cc342c64a5d071a'}\n\n```{.r .cell-code}\nd2 %>% plot_correlation()\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n#### Bonus\n\nProbieren Sie mal diese Funktion aus, die Ihnen einen Bericht zur EDA erstellt.\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-8_4b8a3be10c7cedae8513c8693f77a327'}\n\n```{.r .cell-code}\ncreate_report(d2)\n```\n:::\n\n\n\n\n\n<!-- ### Selbsgetrickte Visualisierung von `weight` und `height` -->\n\n\n<!-- ```{r Post-Regression-6} -->\n<!-- d2 %>%  -->\n<!--   select(weight, height) %>%  -->\n<!--   pivot_longer(everything()) %>%  -->\n<!--   ggplot(aes(x = value)) + -->\n<!--   geom_histogram() + -->\n<!--   facet_wrap(~ name, scales = \"free\") + -->\n<!--   geom_vline(data = d2_summary, -->\n<!--              aes(xintercept = avg)) + -->\n<!--   geom_segment(data = d2_summary, -->\n<!--               aes(x = avg-stdev, -->\n<!--                   xend = avg+stdev), -->\n<!--               y = 0, -->\n<!--               yend = 0, -->\n<!--               alpha = .7, -->\n<!--               color = \"blue\", -->\n<!--               size = 2) + -->\n<!--   labs(caption = \"Vertikale Linie: Mittelwert\\nhorizontale Linie: Standardabweichung\") -->\n<!-- ``` -->\n\n\n\n\n\n### Prädiktor zentrieren \n\n\n\n\nZieht man von jedem Gewichtswert den Mittelwert ab, so bekommt man die Abweichung des Gewichts vom Mittelwert (Prädiktor \"zentrieren\").\nWenn man den Prädiktor (`weight`) zentriert hat, ist der Achsenabschnitt, $\\alpha$, einfacher zu verstehen.\nIn einem Modell mit zentriertem Prädiktor (`weight`) gibt der Achsenabschnitt die Größe einer Person mit durchschnittlichem Gewicht an. \nWürde man `weight` nicht zentrieren, gibt der Achsenabschnitt die Größe einer Person mit `weight=0` an, was nicht wirklich sinnvoll zu interpretieren ist.\n\n\n\nVgl. @gelman_regression_2021, Kap. 10.4,  12.2.\n\n\n\n\nSo kann man das Zentrieren bewerkstelligen:\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-9_cf9d3f7146d7d53d739667cf12ceaa72'}\n\n```{.r .cell-code}\nd3 <- \n  d2 %>% \n  center(weight)\n```\n:::\n\n\nOder so, von Hand:\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-7_0746e9c78f8c6c31085d9ff8ddae6cba'}\n\n```{.r .cell-code}\nd3 <-\n  d2 %>% \n  mutate(weight_c = weight - mean(weight))\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-8_06629945b27e491eac92377ad3c952aa'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"qvztfzjzbf\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#qvztfzjzbf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qvztfzjzbf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qvztfzjzbf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qvztfzjzbf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qvztfzjzbf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qvztfzjzbf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qvztfzjzbf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qvztfzjzbf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qvztfzjzbf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qvztfzjzbf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qvztfzjzbf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qvztfzjzbf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qvztfzjzbf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvztfzjzbf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qvztfzjzbf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qvztfzjzbf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvztfzjzbf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qvztfzjzbf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvztfzjzbf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qvztfzjzbf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvztfzjzbf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qvztfzjzbf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qvztfzjzbf .gt_left {\n  text-align: left;\n}\n\n#qvztfzjzbf .gt_center {\n  text-align: center;\n}\n\n#qvztfzjzbf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qvztfzjzbf .gt_font_normal {\n  font-weight: normal;\n}\n\n#qvztfzjzbf .gt_font_bold {\n  font-weight: bold;\n}\n\n#qvztfzjzbf .gt_font_italic {\n  font-style: italic;\n}\n\n#qvztfzjzbf .gt_super {\n  font-size: 65%;\n}\n\n#qvztfzjzbf .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#qvztfzjzbf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qvztfzjzbf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qvztfzjzbf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qvztfzjzbf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qvztfzjzbf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qvztfzjzbf .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">height</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">weight</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">male</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">weight_c</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">152</td>\n<td class=\"gt_row gt_right\">48</td>\n<td class=\"gt_row gt_right\">63</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">3</td></tr>\n    <tr><td class=\"gt_row gt_right\">140</td>\n<td class=\"gt_row gt_right\">36</td>\n<td class=\"gt_row gt_right\">63</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">−9</td></tr>\n    <tr><td class=\"gt_row gt_right\">137</td>\n<td class=\"gt_row gt_right\">32</td>\n<td class=\"gt_row gt_right\">65</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">−13</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\nWie man sieht, ist die Verteilung \"zur Seite geschoben\": Der Mittelwert liegt jetzt eben bei 0.\n\n\n\n\n::: {.cell fig.asp='0.4' hash='lineare-modelle_cache/html/Post-Regression-9_7e0a9cbb623a44eddba9bd4f78c357bd'}\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-9-1.png){width=672}\n:::\n:::\n\n\n\n\nDas schwierigste ist dabei, nicht zu vergessen, dass `d3` die Tabelle mit zentriertem Prädiktor ist, nicht `d2`.\n\n\n## Modell m43: zentrierter Prädiktor\n\n\nEinige Regressionskoeffizienten, wie der Achsenabschnitt (Intercept) sind schwer zu interpretieren:\nBei einem (erwachsenen) Menschen mit *Gewicht 0*, was wäre wohl die Körpergröße?\nHm, Philosophie steht heute nicht auf der Tagesordnung.\n\nDa wäre es schön, wenn wir die Daten so umformen könnten, dass der Achsenabschnitt eine sinnvolle Aussage macht.\nZum Glück geht das leicht: Wir zentrieren den Prädiktor (Gewicht)!\n\n\n:::callout-important\nDurch Zentrieren kann man die Ergebnisse einer Regression einfacher interpretieren.\n:::\n\n\n\n\n\n### Modelldefinition von `m43`\n\n- Für jede Ausprägung des Prädiktors (`weight`), $h_i$, wird eine Post-Verteilung für die abhängige Variable (`height`) berechnet.\n- Der Mittelwert $\\mu$ für jede Post-Verteilung ergibt sich aus dem linearen Modell (unserer Regressionsformel).\n- Die Post-Verteilung berechnet sich auf Basis der Priori-Werte und des Likelihood (Bayes-Formel).\n- Wir brauchen Priori-Werte für die Steigung $\\beta$ und den Achsenabschnitt $\\alpha$ der Regressionsgeraden.\n- Außerdem brauchen wir einen Priori-Wert, der die Streuung $\\sigma$ der Größe (`height`) angibt; dieser Wert wird als exonentialverteilt angenommen.\n- Der Likelihood gibt an, wie wahrscheinlich ein Wert `height` ist, gegeben $\\mu$ und $\\sigma$.\n\n\n$$\n\\begin{align*}\n\\color{red}{\\text{height}_i} & \\color{red}\\sim \\color{red}{\\operatorname{Normal}(\\mu_i, \\sigma)} && \\color{red}{\\text{Likelihood}} \\\\\n\\color{green}{\\mu_i} & \\color{green}= \\color{green}{\\alpha + \\beta\\cdot \\text{weight}_i}  && \\color{green}{\\text{Lineares Modell} } \\\\\n\\color{blue}\\alpha & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(178, 20)} && \\color{blue}{\\text{Priori}} \\\\\n\\color{blue}\\beta  & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(0, 10)}  && \\color{blue}{\\text{Priori}}\\\\\n\\color{blue}\\sigma & \\color{blue}\\sim \\color{blue}{\\operatorname{Exp}(0.1)}  && \\color{blue}{\\text{Priori}}\n\\end{align*}\n$$\n\n\n\n\n### Likelihood, `m43`\n\n\n\n$$\n\\begin{aligned}\n\\color{red}{\\text{height}_i} & \\color{red}\\sim \\color{red}{\\operatorname{Normal}(\\mu_i, \\sigma)} && \\color{red}{\\text{Likelihood}}\n\\end{aligned}\n$$\n\n\n\n\n- Der Likelihood von `m43` ist ähnlich zu den vorherigen Modellen (`m41, m42`).\n- Nur gibt es jetzt ein kleines \"Index-i\" am $\\mu$ und am $h$ (h wie `heights`).\n- Es gibt jetzt nicht mehr nur einen Mittelwert $\\mu$, sondern für jede Beobachtung (Zeile) einen Mittelwert $\\mu_i$.\n- Lies  etwa so:\n\n>    \"Die Wahrscheinlichkeit, eine bestimmte Größe bei Person $i$ zu beobachten, gegeben $\\mu$ und $\\sigma$ ist normalverteilt (mit Mittelwert $\\mu$ und Streuung $\\sigma$)\".\n\n\n\n\n\n### Regressionsformel, `m43`\n\n\n$$\n\\begin{aligned}\n\\color{green}{\\mu_i} & \\color{green}= \\color{green}{\\alpha + \\beta\\cdot \\text{weight}_i}  && \\color{green}{\\text{Lineares Modell} } \\\\\n\\end{aligned}\n$$\n\n\n- $\\mu$ ist jetzt nicht mehr ein Parameter, der (stochastisch) geschätzt werden muss. $\\mu$ wird jetzt (deterministisch) *berechnet*. Gegeben $\\alpha$ und $\\beta$ ist $\\mu$ ohne Ungewissheit bekannt.\n- $\\text{weight}_i$ ist der Prädiktorwert (`weight`) der $i$ten Beobachtung, also einer !Kung-Person (Zeile $i$ im Datensatz).\n- Lies  etwa so:\n\n>    \"Der Mittelwert $\\mu_i$ der $i$ten Person berechnet sich als Summe von $\\alpha$ und $\\beta$ mal  $\\text{weight}_i$\".\n\n\n- $\\mu_i$ ist eine lineare Funktion von `weight`.\n- $\\beta$ gibt den Unterschied in `height` zweier Beobachtung an, die sich um eine Einheit in `weight` unterscheiden (Steigung der Regressionsgeraden).\n- $\\alpha$ gibt an, wie groß $\\mu$ ist, wenn `weight` Null ist (Achsenabschnitt, engl. intercept).\n\n\n\n### Priori-Werte des Modells `m43`\n\n\n\n$$\n\\begin{align*}\n\\color{blue}\\alpha & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(178, 20)} && \\color{blue}{\\text{Priori Achsenabschnitt}} \\\\\n\\color{blue}\\beta  & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(0, 10)}  && \\color{blue}{\\text{Priori Regressionsgewicht}}\\\\\n\\color{blue}\\sigma & \\color{blue}\\sim \\color{blue}{\\operatorname{Exp}(0.1)}  && \\color{blue}{\\text{Priori Sigma}}\n\\end{align*}\n$$\n\n- Parameter sind hypothetische Kreaturen: Man kann sie nicht beobachten, sie existieren nicht wirklich. Ihre Verteilungen nennt man Priori-Verteilungen.\n- $\\alpha$ wurde in `m41` als $\\mu$ bezeichnet, da wir dort eine \"Regression ohne Prädiktoren\" berechnet haben.\n- $\\sigma$ ist uns schon als Parameter bekannt und behält seine Bedeutung aus dem letzten Kapitel.\n- Da `height` nicht zentriert ist, der Mittelwert von $\\alpha$ bei 178 und nicht 0.\n- $\\beta$ fasst unser Vorwissen, ob und wie sehr der Zusammenhang zwischen Gewicht und Größe positiv (gleichsinnig) ist.\n\n\n## Vertiefung: Prior-Prädiktiv-Verteilung\n\n🏎️ VERTIEFUNG 🏎️\n\n### Moment\n\n   - 🤔 Moment. Dieser Prior, $\\beta$ in `m43` erachtet positive und negative Zusammenhang als gleich wahrscheinlich?!\n   - Sind wir wirklich indifferent, ob der Zusammenhang von Gewicht und Größe positiv oder negativ ist? [Nein, sind wir nicht.](https://media.giphy.com/media/daPCSjwus6UR2JxRX1/giphy.gif) \n    \n\n\n### Priori-Prädiktiv-Verteilung für `m43`\n\n\n\n- Was denkt [wir](https://media.giphy.com/media/Aausss8uUBIe3bZ3d2/giphy.gif) bzw. unser Golem *apriori* über den Zusammenhang von Größe und Gewicht?\n- Um diese Frage zu beantworten ziehen wir Stichproben aus den Priori-Verteilungen des Modells, also für $\\alpha$, $\\beta$ und $\\sigma$.\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/m43-prior-pred_1d1511e61ff5ed1d5bfefb325ab743bb'}\n\n```{.r .cell-code}\nm43_prior_pred <-\n    stan_glm(height ~ weight_c, \n             prior = normal(0, 10),\n             prior_intercept = normal(178, 20),  # mu\n             prior_aux = exponential(0.1),  # sigma\n             refresh = FALSE, \n             prior_PD = TRUE,  # Schalter für Prior-Pred-Verteilung\n             data = d2)\n\n\nm43_prior_pred_draws <- \n  m43_prior_pred %>% \n  as_tibble() %>% \n  rename(a = `(Intercept)`,\n         b = weight_c) %>% \n  slice_sample(n = 50)\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-10_0c4478bfc5682febb9ee6465fae315db'}\n\n```{.r .cell-code}\nm43_prior_pred_draws %>% \n  slice_head(n=5) %>% \n  gt() %>% \n  fmt_number(everything(), decimals = 1)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"txbniecyad\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#txbniecyad .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#txbniecyad .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#txbniecyad .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#txbniecyad .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#txbniecyad .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#txbniecyad .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#txbniecyad .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#txbniecyad .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#txbniecyad .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#txbniecyad .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#txbniecyad .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#txbniecyad .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#txbniecyad .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#txbniecyad .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#txbniecyad .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#txbniecyad .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#txbniecyad .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#txbniecyad .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#txbniecyad .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#txbniecyad .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#txbniecyad .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#txbniecyad .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#txbniecyad .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#txbniecyad .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#txbniecyad .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#txbniecyad .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#txbniecyad .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#txbniecyad .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#txbniecyad .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#txbniecyad .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#txbniecyad .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#txbniecyad .gt_left {\n  text-align: left;\n}\n\n#txbniecyad .gt_center {\n  text-align: center;\n}\n\n#txbniecyad .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#txbniecyad .gt_font_normal {\n  font-weight: normal;\n}\n\n#txbniecyad .gt_font_bold {\n  font-weight: bold;\n}\n\n#txbniecyad .gt_font_italic {\n  font-style: italic;\n}\n\n#txbniecyad .gt_super {\n  font-size: 65%;\n}\n\n#txbniecyad .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#txbniecyad .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#txbniecyad .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#txbniecyad .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#txbniecyad .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#txbniecyad .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#txbniecyad .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">a</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">b</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">sigma</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">185.6</td>\n<td class=\"gt_row gt_right\">6.1</td>\n<td class=\"gt_row gt_right\">10.6</td></tr>\n    <tr><td class=\"gt_row gt_right\">153.9</td>\n<td class=\"gt_row gt_right\">0.1</td>\n<td class=\"gt_row gt_right\">24.5</td></tr>\n    <tr><td class=\"gt_row gt_right\">181.8</td>\n<td class=\"gt_row gt_right\">13.4</td>\n<td class=\"gt_row gt_right\">3.9</td></tr>\n    <tr><td class=\"gt_row gt_right\">193.4</td>\n<td class=\"gt_row gt_right\">−6.8</td>\n<td class=\"gt_row gt_right\">15.0</td></tr>\n    <tr><td class=\"gt_row gt_right\">169.6</td>\n<td class=\"gt_row gt_right\">2.1</td>\n<td class=\"gt_row gt_right\">15.0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\nJede Zeile definiert eine Regressionsgerade.\n\n\n\n### Prior-Prädiktiv-Simulation für `m43` mit `stan_glm()` \n\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-11_cebf4b19c51e4835423af89797d3b486'}\n\n```{.r .cell-code}\nm43_prior_pred <-\n    stan_glm(height ~ weight_c, \n             prior = normal(0, 10),  # beta\n             prior_intercept = normal(178, 20),  # alpha\n             prior_aux = exponential(0.1),  # sigma\n             refresh = FALSE, \n             prior_PD = TRUE,  # DIESER Schalter macht's\n             data = d2)\n\nm43_prior_pred_draws <- \n  m43_prior_pred %>% \n  as_tibble() %>% \n  rename(a = `(Intercept)`,\n         b = weight_c) %>% \n  slice_sample(n = 50)\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-12_2e3ef08d37dc856bf44aa65a0ec240e5'}\n\n:::\n\n\n\n\n\n\n\n\n\n\n### Visualisieren der Prior-Prädiktiv-Verteilung\n\n\n\n\n::: {.cell fig.asp='0.5' hash='lineare-modelle_cache/html/prior-pv1_54a6d5513285e436eb13c40baec8d805'}\n\n```{.r .cell-code}\nd2 %>% ggplot() +\n  geom_point(aes(x = weight_c, y = height)) + \n  geom_abline(data = m43_prior_pred_draws,\naes(intercept = a, slope = b), color = \"skyblue\", size = 0.2) +\n  scale_y_continuous(limits = c(0, 500)) +\n  geom_hline(yintercept = 272, size = .5) +\n  geom_hline(yintercept = 0, linetype = \"dashed\")\n```\n:::\n\n\n\n\n🤯 Einige dieser Regressionsgeraden sind unsinnig!\n\n\n\n::: {.cell fig.asp='0.3' hash='lineare-modelle_cache/html/unnamed-chunk-13_58b33f21a199e76e4ec484756c55d398'}\n\n```{.r .cell-code}\nd2 %>% ggplot() +\n  geom_point(aes(x = weight_c, y = height)) + \n  geom_abline(data = m43_prior_pred_draws,\naes(intercept = a, slope = b), color = \"skyblue\", size = 0.2) +\n  scale_y_continuous(limits = c(0, 500)) +\n  geom_hline(yintercept = 272, size = .5) +\n  geom_hline(yintercept = 0, linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\nDie durchgezogene horizontale Linie gibt die Größe des [größten Menschens, Robert Pershing Wadlow](https://en.wikipedia.org/wiki/Robert_Wadlow), an.\n\n\n\n\n\n### Ein positiver Wert für $\\beta$ ist plausibler\n\n\n#### Oh no\n\nEine Normalverteilung mit viel Streuung:\n\n\n::: {.cell fig.asp='0.5' hash='lineare-modelle_cache/html/Post-Regression-16_992be85effc17b4d2a3e568c7937a1aa'}\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-16-1.png){width=672}\n:::\n:::\n\n\n👎 $\\beta=-20$ wäre mit diesem Prior gut möglich: Pro kg Gewicht sind Menschen im Schnitt 20cm kleiner, laut dem Modell. Quatsch.\n\n\n\n\n#### Oh yes\n\nWir bräuchten eher so eine Verteilung, mit mehr Masse auf der positiven Seite (x>0):\n\n\n::: {.cell fig.asp='0.5' hash='lineare-modelle_cache/html/Post-Regression-17_6174b1a70a87cc526971a5d9f4989864'}\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-17-1.png){width=672}\n:::\n:::\n\n\n👍 Vermutlich besser: Ein Großteil der Wahrscheinlichkeitsmasse ist $X>0$. Allerdings gibt's keine Gewähr, dass unser Prior \"richtig\" ist.\n\n\n\n\n### Priori-Prädiktiv-Simulation, 2. Versuch\n\n\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-14_cf6889a6f529d6ae1baa29e47b0cbe89'}\n\n```{.r .cell-code}\nm43a_prior_pred <-\n    stan_glm(\n      height ~ weight_c, \n      prior = normal(2, 2),  # Regressionsgewicht\n      prior_intercept = normal(178, 20),  # mu\n      prior_aux = exponential(0.1),  # sigma\n      refresh = FALSE, \n      # Schalter für Prior-Pred-Verteilung:\n      prior_PD = TRUE, \n      data = d2)\n\n\nm43a_prior_pred_draws <- \n  m43a_prior_pred %>% \n  as_tibble() %>% \n  # Spaltennamen kürzen: \n  rename(a = `(Intercept)`) %>%  \n  rename(b = weight_c,\n         s = sigma)\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-15_440d3905f1277546414756213b411248'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"epfvkzhkbl\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#epfvkzhkbl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#epfvkzhkbl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#epfvkzhkbl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#epfvkzhkbl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#epfvkzhkbl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#epfvkzhkbl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#epfvkzhkbl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#epfvkzhkbl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#epfvkzhkbl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#epfvkzhkbl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#epfvkzhkbl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#epfvkzhkbl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#epfvkzhkbl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epfvkzhkbl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#epfvkzhkbl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#epfvkzhkbl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epfvkzhkbl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#epfvkzhkbl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epfvkzhkbl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#epfvkzhkbl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epfvkzhkbl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#epfvkzhkbl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epfvkzhkbl .gt_left {\n  text-align: left;\n}\n\n#epfvkzhkbl .gt_center {\n  text-align: center;\n}\n\n#epfvkzhkbl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#epfvkzhkbl .gt_font_normal {\n  font-weight: normal;\n}\n\n#epfvkzhkbl .gt_font_bold {\n  font-weight: bold;\n}\n\n#epfvkzhkbl .gt_font_italic {\n  font-style: italic;\n}\n\n#epfvkzhkbl .gt_super {\n  font-size: 65%;\n}\n\n#epfvkzhkbl .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#epfvkzhkbl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#epfvkzhkbl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#epfvkzhkbl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#epfvkzhkbl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#epfvkzhkbl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#epfvkzhkbl .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">a</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">b</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">s</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">173.9</td>\n<td class=\"gt_row gt_right\">0.1</td>\n<td class=\"gt_row gt_right\">0.0</td></tr>\n    <tr><td class=\"gt_row gt_right\">207.7</td>\n<td class=\"gt_row gt_right\">2.1</td>\n<td class=\"gt_row gt_right\">0.0</td></tr>\n    <tr><td class=\"gt_row gt_right\">190.2</td>\n<td class=\"gt_row gt_right\">−1.4</td>\n<td class=\"gt_row gt_right\">0.0</td></tr>\n    <tr><td class=\"gt_row gt_right\">144.1</td>\n<td class=\"gt_row gt_right\">5.0</td>\n<td class=\"gt_row gt_right\">1.1</td></tr>\n    <tr><td class=\"gt_row gt_right\">176.3</td>\n<td class=\"gt_row gt_right\">5.1</td>\n<td class=\"gt_row gt_right\">0.4</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\nDas Argument `prior_PD = TRUE` sorgt dafür, dass keine Posteriori-Verteilung, sondern eine Prior-Prädiktiv-Verteilung berechnet wird.\n\n\n\n\n### Visualisieren der Prior-Prädiktiv-Verteilung, `m43a`\n\n\nUnsere Priori-Werte scheinen einigermaßen vernünftige Vorhersagen zu tätigen. Allerdings erwartet unser Golem einige Riesen.\n\n\n\n::: {.cell fig.asp='0.5' hash='lineare-modelle_cache/html/unnamed-chunk-16_e876772eb0c3a4f042824fa7ba1eece6'}\n\n```{.r .cell-code}\nd2 %>% \n  ggplot(aes(x = weight_c, y = height)) +\n  geom_point() +\n  geom_abline(data = {m43a_prior_pred_draws %>% slice_head(n=50)},\n              aes(slope = b,\n                  intercept = a),\n              color = \"skyblue\",\n              size = .2,\n              alpha = .7) +\n  geom_hline(yintercept = 272, size = .5) +\n  geom_hline(yintercept = 0, linetype = \"dashed\")+\n  scale_y_continuous(limits = c(0, 500)) \n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nDie durchgezogene horizontale Linie gibt die Größe des [größten Menschens, Robert Pershing Wadlow](https://en.wikipedia.org/wiki/Robert_Wadlow), an.\n\n\n\n\n\n\n\n\n### Moment, kann hier jeder machen, was er will?\n\n\n\nEs doch den einen, richtigen, objektiven Priori-Wert geben?!\n\nKann denn jeder hier machen, was er will?! Wo kommen wir da hin?!\n\n\n>    This is a mistake. There is no more a uniquely correct prior than there is a uniquely correct likelihood. Statistical models are machines for inference. Many machines will work, but some work better than others. Priors can be wrong, but only in the same sense that a kind of hammer can be wrong for building a table.  \n\n@mcelreath_statistical_2020, p. 96.\n\n\n\n\n\n### Hier ist unser Modell, `m43a`\n\n\n\n\n$$\n\\begin{align}\n\\text{height}_i &\\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i &= \\alpha + \\beta \\cdot  \\text{weight}_i\\\\\n\\alpha &\\sim \\operatorname{Normal}(178, 20)\\\\\n\\beta &\\sim \\operatorname{Normal}(5,3)\\\\\n\\sigma &\\sim \\operatorname{Exp}(0.1)\n\\end{align}\n$$\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-25_475c3fb51721b7a5237c340433c3e902'}\n\n```{.r .cell-code}\n# Zufallszahlen festlegen:\nset.seed(42)  \n# Posteriori-Vert. berechnen:\nm43a <-\n  stan_glm(\n    height ~ weight_c,  # Regressionsformel\n    prior = normal(5, 3),  # Regressionsgewicht (beta 1)\n    prior_intercept = normal(178, 20),  # mu\n    prior_aux = exponential(0.1),  # sigma\n    refresh = 0,  # zeig mir keine Details\n    data = d2)\n```\n:::\n\n\n\n\n\n\n### Eine Zusammenfassung der Posteriori-Verteilung für `m43a`\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-17_44cec94dd5b245a86c37b16e64179e73'}\n\n```{.r .cell-code}\nm43a %>% \n  parameters()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   |      Median|   CI|      CI_low|     CI_high| pd| ROPE_Percentage|      Rhat|      ESS|Prior_Distribution | Prior_Location| Prior_Scale|\n|:-----------|-----------:|----:|-----------:|-----------:|--:|---------------:|---------:|--------:|:------------------|--------------:|-----------:|\n|(Intercept) | 154.6452186| 0.95| 154.0867377| 155.2097388|  1|               0| 0.9992177| 4131.743|normal             |            178|          20|\n|weight_c    |   0.9080384| 0.95|   0.8270187|   0.9930941|  1|               0| 0.9998787| 3836.631|normal             |              5|           3|\n\n</div>\n:::\n:::\n\n\n\nUnser Modell `m43a` schätzt die typische Körpergröße einer !Kung-Person *mittleren Gewichts* (`weight_c = 0`) auf knapp 155 cm, und ist sich dieses Werts ziemlich sicher.\nPro Kilogramm kommt (laut unserem Modell) ein knapper Zentimeter hinzu, typischerweise;\nauch hier ist sich das Modell ziemlich sicher, da dass zugehörige 95%-CI keine 20 Zentimenter umfasst.\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Die Post-Verteilung befragen\n\n\n### m43a\n\n\nSagen wir, auf Basis gut geprüfter Evidenz haben wir folgendes Modell festgelegt: `height ~ weight_c`.\n\nPrioris:\n\n$$\n\\beta_1 \\sim N(5,3) \\\\\n\\beta_0 \\sim N(178, 20) \\\\\n\\sigma \\sim E(0.1)\n$$\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/m43a_6a0393be74908ad9296db0dc3a8728a6'}\n\n```{.r .cell-code}\n# Zufallszahlen festlegen:\nset.seed(42)  \n# Posteriori-Vert. berechnen:\nm43a <-\n  stan_glm(\n    height ~ weight_c,  # Regressionsformel\n    prior = normal(5, 3),  # Regressionsgewicht (beta 1)\n    prior_intercept = normal(178, 20),  # mu\n    prior_aux = exponential(0.1),  # sigma\n    refresh = 0,  # zeig mir keine Details\n    data = d2)\n```\n:::\n\n\n\nWir nennen es `m43a`^[Wer ist hier für die Namensgebung zuständig?].\n\n\n### Mittelwerte von $\\alpha$ und $\\beta$ aus der Post-Verteilung\n\n\n\nDie ersten paar Zeilen:\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-3_097eed61574e386ccabdc5d97c50fb04'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"fhppwtrsws\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#fhppwtrsws .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fhppwtrsws .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fhppwtrsws .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fhppwtrsws .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fhppwtrsws .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fhppwtrsws .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fhppwtrsws .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fhppwtrsws .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fhppwtrsws .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fhppwtrsws .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fhppwtrsws .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fhppwtrsws .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fhppwtrsws .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhppwtrsws .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fhppwtrsws .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fhppwtrsws .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhppwtrsws .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fhppwtrsws .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhppwtrsws .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fhppwtrsws .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhppwtrsws .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fhppwtrsws .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhppwtrsws .gt_left {\n  text-align: left;\n}\n\n#fhppwtrsws .gt_center {\n  text-align: center;\n}\n\n#fhppwtrsws .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fhppwtrsws .gt_font_normal {\n  font-weight: normal;\n}\n\n#fhppwtrsws .gt_font_bold {\n  font-weight: bold;\n}\n\n#fhppwtrsws .gt_font_italic {\n  font-style: italic;\n}\n\n#fhppwtrsws .gt_super {\n  font-size: 65%;\n}\n\n#fhppwtrsws .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#fhppwtrsws .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fhppwtrsws .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fhppwtrsws .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fhppwtrsws .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fhppwtrsws .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fhppwtrsws .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">(Intercept)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">weight_c</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">sigma</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">154.8</td>\n<td class=\"gt_row gt_right\">0.9</td>\n<td class=\"gt_row gt_right\">4.9</td></tr>\n    <tr><td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">154.7</td>\n<td class=\"gt_row gt_right\">0.8</td>\n<td class=\"gt_row gt_right\">4.8</td></tr>\n    <tr><td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">154.9</td>\n<td class=\"gt_row gt_right\">1.0</td>\n<td class=\"gt_row gt_right\">5.1</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-4_b00a6935541ebce7c2c2fd61b56138ed'}\n\n```{.r .cell-code}\nparameters(m43a)\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-5_b5dfce33a1575099ea1dcedff2bbf047'}\n::: {.cell-output-display}\nTable: Fixed effects\n\n|Parameter   | Median |           95% CI |   pd | % in ROPE |  Rhat |     ESS |              Prior |\n|:-----------|:------:|:----------------:|:----:|:---------:|:-----:|:-------:|:------------------:|\n|(Intercept) | 154.65 | (154.09, 155.21) | 100% |        0% | 0.999 | 4132.00 | Normal (178 +- 20) |\n|weight_c    |   0.91 |     (0.83, 0.99) | 100% |        0% | 1.000 | 3837.00 |    Normal (5 +- 3) |\n:::\n:::\n\n\n\n\nDie Kennzahl  `pd` (propability of direction) gibt die Wahrscheinlichkeit an,\ndass der Effekt positiv (also größer als Null) oder negativ ist (jenachdem ob der Median des Effekts positiv oder negativ ist).\n`pd` gibt aber nicht an, wie stark der Effekt ist, nur ob er klar auf einer Seite der Null liegt.\nDamit ist er so etwas (grob!) Ähnliches wie der p-Wert in der Frequentistischen Statistik [@makowski_indices_2019].\n\n\nAm besten das Diagramm dazu anschauen:\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-18_8373e6588dd5e9a6069f136dbacc1c64'}\n\n```{.r .cell-code}\nplot(p_direction(m43a))\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\n`Rhat` und `ESS` sind Kennzahlen, die untersuchen, ob mit der Stichprobenziehung im Bayes-Modell alles gut funktioniert hat. Bei einfachen Modellen (die wir hier berechnen) sollte da in der Regel alles in Ordnung sein.\n`Rhat` sollte nicht (viel) größer als 1 oder 1,01 sein. `ESS` (effective sample size) gibt die Anzahl der effektiv nutzbaren Stichproben an (im Standard werden 4000 berechnet). Die Zahl sollte nicht deutlich geringer sein.\n\nWir werden uns aber mit diesen beiden Kennwerten nicht weiter beschäftigen in diesem Kurs.\n\n\n### Visualisieren der \"mittleren\" Regressiongeraden\n\n\n\nZur Erinnerung: Die Bayes-Analyse liefert uns viele Stichproben zu den gesuchten Parametern,\nhier $\\beta_0$, $\\beta_1$ und $\\sigma$:\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-19_f2ad11b2ba6ee69e2b58241ae87643ca'}\n\n```{.r .cell-code}\nm43a %>% \n  as_tibble() %>% \n  head()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| (Intercept)|  weight_c|    sigma|\n|-----------:|---------:|--------:|\n|    154.7538| 0.9059392| 4.944015|\n|    154.7377| 0.8296286| 4.791166|\n|    154.8777| 0.9501849| 5.142597|\n|    155.0067| 0.9629459| 5.278018|\n|    154.3270| 0.8646662| 4.934844|\n|    154.3545| 0.8767378| 4.812926|\n\n</div>\n:::\n:::\n\n\nWir können z.B. ein Lagemaß wie den Median hernehmen, um die \"mittlere\" Regressionsgerade zu betrachten:\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-6_9d468737c633dc2aee6d175d9e694c5a'}\n\n```{.r .cell-code}\nd2 %>% \n  ggplot() +\n  aes(x = weight_c, y = height) +\n  geom_point() +\n  geom_abline(\n    slope = 0.9,  # Median beta 1\n    intercept = 154,  # Median beta 0\n    color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-befragen-6-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n### Zentrale Statistiken zu den Parametern\n\nIn diesem Modell gibt es drei Parameter: $\\mu, \\beta, \\sigma$.\n\nHier folgen einige Beispiele an Fragen, die wir an unser Modell bzw. die Post-Verteilung stellen können.\n\n\n#### Lagemaße zu den Parametern\n\n- Was ist die mittlere Größe einer !Kung-Person? ($\\beta_0$)\n- Was ist der Schätzwert für den Zusammenhang von Gewicht und Größe? ($\\beta_1$)\n- Was ist der Schätzwert für Ungewissheit in der Schätzung der Größe? ($\\sigma$)\n- Was ist der wahrscheinlichste Wert für z.B: $\\beta_1$?\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-7_15fffdffbf4c256ec8fe9517d1d78235'}\n\n```{.r .cell-code}\nm43a %>% \n  parameters()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   |      Median|   CI|      CI_low|     CI_high| pd| ROPE_Percentage|      Rhat|      ESS|Prior_Distribution | Prior_Location| Prior_Scale|\n|:-----------|-----------:|----:|-----------:|-----------:|--:|---------------:|---------:|--------:|:------------------|--------------:|-----------:|\n|(Intercept) | 154.6452186| 0.95| 154.0867377| 155.2097388|  1|               0| 0.9992177| 4131.743|normal             |            178|          20|\n|weight_c    |   0.9080384| 0.95|   0.8270187|   0.9930941|  1|               0| 0.9998787| 3836.631|normal             |              5|           3|\n\n</div>\n:::\n:::\n\n\n\nWandelt man das Ausgabe-Objekt der Bayes-Regression mit `as_tibble()` in eine Tabelle um,\nso bekommt man eine Tabelle mit den Stichproben der Post-Verteilung:\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-20_e47a511810934a39efb158bc88f09dd6'}\n\n```{.r .cell-code}\nm43a_post <- \n  m43a %>% \n  as_tibble()\n\nm43a_post %>% \n  head()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| (Intercept)|  weight_c|    sigma|\n|-----------:|---------:|--------:|\n|    154.7538| 0.9059392| 4.944015|\n|    154.7377| 0.8296286| 4.791166|\n|    154.8777| 0.9501849| 5.142597|\n|    155.0067| 0.9629459| 5.278018|\n|    154.3270| 0.8646662| 4.934844|\n|    154.3545| 0.8767378| 4.812926|\n\n</div>\n:::\n:::\n\n\n\nWie wir gesehen haben, nutzen wir diese Tabeller der Post-Verteilung immer wieder.\nSpeichern wir uns sie also als ein Objekt ab, `m43_post`.\n\n\n\n![Typischer Bayes-Nutzer, der ein Ungewissheitsintervall berechnet. Bildquelle: Easystats, bayestestR](https://easystats.github.io/bayestestR/reference/figures/bayesianMaster.jpg)\n\n[Quelle](https://easystats.github.io/bayestestR/articles/bayestestR.html)\n\n\nEine Visualisierung zeigt gut sowohl Lage- als auch Streuungsmaße der Parameter, zumindest grob:\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-21_457f627cb67e1baf3772579bc9cafece'}\n\n```{.r .cell-code}\nm43a_post %>% \n  ggplot(aes(x = weight_c)) +\n  geom_density(fill = \"orange\")\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\nDas Diagramm zeigt, dass Mittelwert, Median und Modus eng zusammenliegen.\nZur Erinnerung: Der Modus gibt den häufigsten, d.h. hier also den wahrscheinlichsten, Wert an.\n\nDer Modus wird hier auch *Maximum a Posteriori* (MAP) genannt, daher:\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/map-estimate-m43a_e4d53c91ed130045f421debf30ada32e'}\n\n```{.r .cell-code}\nm43a_post %>% \n  summarise(map_b1 = map_estimate(weight_c))\n```\n:::\n\n\n\n\n\n\nHier ist die Verteilung von $\\sigma$ visualisiert:\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-22_21d04776703bbbdee35d2862e1a67a22'}\n\n```{.r .cell-code}\nm43a_post %>% \n  ggplot(aes(x = sigma)) +\n  geom_density(fill = \"orange\")\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\nAlternativ kann man sich die Verteilung eines Parameters auch so ausgeben lassen,\ngleich mit Intervallgrenzen, z.B. 95%.\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-23_59a9c2ee97cce27f1f8b758306789053'}\n\n```{.r .cell-code}\nm43a_hdi <- hdi(m43a_post)  # analog mit eti(m43a)\n\nplot(m43a_hdi)\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nErgänzt man bei `plot()` noch `show_intercept = TRUE` wird auch der Achsenabschnitt angezeigt.\n\n\n\n\n### Streuungsmaße zu den Parametern\n\n\n- Wie unsicher sind wir uns in den Schätzungen der Parameter?\n\n\n\nDiese Frage wird durch die Ungewissheitsintervalle in der Ausgabe beantwortet.\n\n\n:::callout-note\nAn einigen Stellen wird empfohlen, anstelle eines (gebräuchlichen) 95%-Intervalls \nauf ein 90%- oder 89%-Intervall auszuweichen, aufgrund der besseren numerischen Stabilität.\n:::\n\n\n### Ungewissheit von $\\alpha$ und $\\beta$ aus der Post-Verteilung visualisiert\n\n\n\nDie ersten 10 Stichproben\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-10_27d7d5dfd73b7a26780750dec7cdd201'}\n\n```{.r .cell-code}\nd2 %>% \n  ggplot(aes(x = weight_c, \n             y = height)) +\n  geom_point() +\n  geom_abline(\n    data = m43a_post %>% \n      slice_head(n = 10),\n    aes(slope = weight_c,\n        intercept = `(Intercept)`),\n    alpha = .3)\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-befragen-10-1.png){width=672}\n:::\n:::\n\n\n\nDie ersten 100 Stichproben\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-11-ersten-1000_15fa755b71d4eaa9c9abfa3630327e29'}\n\n```{.r .cell-code}\nd2 %>% \n  ggplot(aes(x = weight_c, \n             y = height)) +\n  geom_point() +\n  geom_abline(\n    data = m43a_post %>% \n      slice_head(n = 100),\n     aes(slope = weight_c,\n        intercept = `(Intercept)`),\n    alpha = .1)\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-befragen-11-ersten-1000-1.png){width=672}\n:::\n:::\n\n\n\nDie ersten `1e3` Stichproben\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-11-die-ersten-1000_b4890d63ee4afb49f49b09a44a577ad0'}\n\n```{.r .cell-code}\nd2 %>% \n  ggplot(aes(x = weight_c, \n             y = height)) +\n  geom_point() +\n  geom_abline(\n    data = m43a_post %>% \n      slice_head(n = 1e3),\n     aes(slope = weight_c,\n        intercept = `(Intercept)`),\n    alpha = .01)\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-befragen-11-die-ersten-1000-1.png){width=672}\n:::\n:::\n\n\n\nDie ersten 1000000 ... okay, lassen wir es gut sein^[Im Standard beschert uns `stan_glm()` 4000 Stichproben.].\n\n\n### Fragen zu Quantilen des Achsenabschnitts \n\n:::callout-note\nZur Erinnerung: Bei einem zentrierten Prädiktor misst der Achsenabschnitt die mittlere Größe.\n:::\n\n- Welche mittlere Größe mit zu 50%, 90% Wskt. nicht überschritten?\n- Welche mittlere Größe mit zu 95% Wskt. nicht unterschritten?\n- Von wo bis wo reicht der innere 50%-Schätzbereich der mittleren Größe?\n\n\n\nQuantile:\n\n\n::: {.cell hash='lineare-modelle_cache/html/quantile-post_425cb268663f19b084ad0c726457f1d4'}\n\n```{.r .cell-code}\nm43a_post %>% \n  summarise(\n    q_50 = quantile(`(Intercept)`, prob = .5),\n    q_90 = quantile(`(Intercept)`, prob = .9),\n    q_05 = quantile(`(Intercept)`, prob = .05))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     q_50|     q_90|     q_05|\n|--------:|--------:|--------:|\n| 154.6452| 155.0094| 154.1813|\n\n</div>\n:::\n:::\n\n\n50%-PI:\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-24_2ebf6bdaff100fa9ee21b33ac35ece18'}\n\n```{.r .cell-code}\nm43a_post %>% \n  summarise(pi_50 = quantile(`(Intercept)`, prob = c(.25, .75)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    pi_50|\n|--------:|\n| 154.4600|\n| 154.8446|\n\n</div>\n:::\n:::\n\n\n\n\n### Fragen zu Wahrscheinlichkeitsmassen des Achsenabschnitts \n\n\n\nWie wahrscheinlich ist es, dass die mittlere Größe bei mind. 155 cm liegt?\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-25_8292a1105612073c66dd272b0c6eacb9'}\n\n```{.r .cell-code}\nm43a_post %>% \n  count(gross = `(Intercept)` >= 155) %>% \n  mutate(prop = n / sum(n))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|gross |    n|   prop|\n|:-----|----:|------:|\n|FALSE | 3574| 0.8935|\n|TRUE  |  426| 0.1065|\n\n</div>\n:::\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-26_9ff524677d711d1b7d1f79ebced603e0'}\n\n:::\n\n\nDie Wahrscheinlichkeit beträgt 0.11.\n\n\n- Wie wahrscheinlich ist es, dass die mittlere Größe höchstens 154.5 cm beträgt?\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-27_cf6855c29783f63825ce0ae876828a6c'}\n\n```{.r .cell-code}\nm43a_post %>% \n  count(klein = (`(Intercept)` <= 154.5)) %>% \n  mutate(prop = n / sum(n))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|klein |    n|   prop|\n|:-----|----:|------:|\n|FALSE | 2810| 0.7025|\n|TRUE  | 1190| 0.2975|\n\n</div>\n:::\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-28_f8bedfb6686651268caabb81a942b53c'}\n\n:::\n\n\n\nDie Wahrscheinlichkeit beträgt 0.3.\n\n\n\n\n\n\n<!-- ### Ungewissheit von Achsenabschnitt und Steigung  -->\n\n<!-- ... als Histogramme visualisiert -->\n\n<!--  -->\n\n<!-- ### Achsenabschnitt -->\n\n<!-- ```{r Post-Regression-befragen-13, echo = TRUE, eval = TRUE} -->\n<!-- post_m43a %>%  -->\n<!--   ggplot(aes(x = a)) + -->\n<!--   geom_density() -->\n<!-- ``` -->\n\n<!-- ] -->\n\n<!-- .pull-right[ -->\n\n<!-- ### Regressionsgewicht (Steigung) -->\n\n<!-- ```{r Post-Regression-befragen-14, echo = TRUE} -->\n<!-- post_m43a %>%  -->\n<!--   ggplot(aes(x = b)) + -->\n<!--   geom_density() -->\n<!-- ``` -->\n\n<!-- ] -->\n\n\n## Post-Verteilung bedingt auf einen Prädiktorwert\n\n\n### Visualisierung\n\n\nWas ist wohl die Wahrscheinlichkeit der Körpergröße bei einem bestimmten Gewicht?\n\nAngenommen wir wissen, dass das Gewicht bei, sagen wir 45 kg liegt.\nWelche Körpergröße ist (im Schnitt) zu erwarten? Wie unsicher sind wir uns über diesen Mittelwert?\n\nEtwas formaler ausgedrückt:\n\n$\\mu|\\text{weight}=45$\n\n\n45 kg entspricht genau dem Mittelwert von `weight`. Geht man von zentrierten Prädiktorwerten aus, gilt in dem Fall `weight_c = 0`.\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/mu-at-45_3f598a0090316e757fab6ecfa27e9cce'}\n\n```{.r .cell-code}\nmu_at_45 <-\n  m43a_post %>% \n  mutate(mu_at_45 = `(Intercept)`)\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-15_4f0477fc97490e52ad1d172e599bb25d'}\n\n```{.r .cell-code}\nmu_at_45 %>% \n  ggplot(aes(x = mu_at_45)) +\n  geom_density()\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-17_9b48ec2c16f23ee4e66fa481afa9a50a'}\n\n```{.r .cell-code}\n# | echo: false\nmu_at_45 %>% \n  ggplot(aes(x = mu_at_45)) +\n  geom_density() +\n  scale_y_continuous(NULL, breaks = NULL) +\n  xlab(expression(mu[\"height | weight = 45\"])) +\n  scale_x_continuous(limits = c(150, 160))\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-befragen-17-1.png){width=672}\n:::\n:::\n\n\n\nAnalog können wir fragen,\nwie groß wohl eine Person mit 50 kg im Mittelwert sein wird und wie (un)gewiss wir uns über diesen Mittelwert sind.\n\n\n50 kg, das sind 5 über dem Mittelwert, in zentrierten Einheiten ausgedrückt also `weight_c = 5`.\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/mu-at-50_1e68e37855deaa02a1304aaceb18cfb9'}\n\n```{.r .cell-code}\nmu_at_50 <-\n  m43a_post %>% \n  mutate(mu_at_50 = `(Intercept)` + 5 * weight_c)\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-16_1b47f4bfda3586e8d15ecbf6a9da53dc'}\n\n```{.r .cell-code}\nmu_at_50 %>% \n  ggplot(aes(x = mu_at_50)) +\n  geom_density()\n```\n:::\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-18_ef6187318dd6b9e3db727a20713e9ae2'}\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/Post-Regression-befragen-18-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Lagemaße und Streuungen\n\n\n\n\nWas ist das 90% PI für $\\mu|w=50$ ?\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-19_6999b90041a9baee4de24b5fff7aec4c'}\n\n```{.r .cell-code}\nmu_at_50 %>% \n  summarise(pi = quantile(mu_at_50, prob = c(0.05, .95)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|       pi|\n|--------:|\n| 158.6054|\n| 159.7872|\n\n</div>\n:::\n:::\n\n\nDie mittlere Größe - gegeben $w=50$ - liegt mit 90% Wahrscheinlichkeit zwischen den beiden Werten.\n\n\n\nWelche mittlere Größe wird mit 95% Wahrscheinlichkeit nicht überschritten, wenn die Person 45kg wiegt?\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-20_c92711b64cfeca63881a551d90e7f4c7'}\n\n```{.r .cell-code}\nmu_at_45 %>% \n  summarise(q_95 = quantile(mu_at_45, prob = .95))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     q_95|\n|--------:|\n| 155.1262|\n\n</div>\n:::\n:::\n\n\n\n\n\n## Die PPV befragen\n\n\n🏎️ VERTIEFUNG 🏎️\n\n\n\n\n\n\n\n\nDie Posterior-Prädiktiv-Verteilung (PPV) gibt uns die Möglichkeit,\nnach der Wahrscheinlichkeit *tatsächlicher* Körpergrößen zu fragen - \nund nicht nur nach *mittleren* Körpergrößen anhand der Post-Verteilung.\n\n\n:::callout-important\nDie Post-Verteilung macht nur Aussagen zur mittleren Körpergröße,\ndenn das ist was wir modellieren wollten.\nMöchten wir Aussagen zur Wahrscheinlichkeit tatsächlicher Größen treffen,\nbrauchen wir die PPV.\n:::\n\n\n### Perzentil-Intervalle für verschiedenen Prädiktor-Werte\n\n\nWir erstellen uns eine Sequenz an Prädiktorwerten, die uns interessieren:\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-29_d594e181e6cb15dfe2eede421d3c3004'}\n\n```{.r .cell-code}\nweight_df <- tibble(weight_c = seq(-20,20, by = 5))\n```\n:::\n\n\n\nFür diese Werte lassen wir uns dann die Perzentil-Intervalle (PI) ausgeben:\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-21_463797deda32f6cec9372c801f496479'}\n\n```{.r .cell-code}\nmus <- \n  predictive_interval(\n    m43a, \n    newdata = weight_df) %>% \n  as_tibble() %>% \n  bind_cols(weight_df)\n```\n:::\n\n\nUm die Perzentilintervalle zu erstellen, wird von `predictive_interval()` für jeden Prädiktorwert eine Posteriori-Verteilung erstellt und das 5%- sowie 95%-Quantil berechnet. \n\nWir sehen etwa, dass wir bei einer Person mittleren Gewichts, eine Körpergrö0e von ca. 146 cm bis 163 cm zu erwarten haben (95%-KI).\nHoppla! Das ist ja viel ungenauer, als die Angaben der Post-Verteilung oben.\nJa, denn die Post-Verteilung hat die Ungewissheit zum *Mittelwert* ausgedrückt;\ndie PPV gibt die Ungewissheit *tatsächlicher* beobachtbarer Körpergrößen aus,\nnicht nur die Ungewissheit zum Mittelwert.\n\n\n\nHier ist ein Auszug aus der PPV-Tabelle:\n\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-23_8a6826fa086f7f96100c2ada33898601'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"dketeqqmtd\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#dketeqqmtd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dketeqqmtd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dketeqqmtd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dketeqqmtd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dketeqqmtd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dketeqqmtd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dketeqqmtd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dketeqqmtd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dketeqqmtd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dketeqqmtd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dketeqqmtd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dketeqqmtd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dketeqqmtd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dketeqqmtd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dketeqqmtd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dketeqqmtd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dketeqqmtd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dketeqqmtd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dketeqqmtd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dketeqqmtd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dketeqqmtd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dketeqqmtd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dketeqqmtd .gt_left {\n  text-align: left;\n}\n\n#dketeqqmtd .gt_center {\n  text-align: center;\n}\n\n#dketeqqmtd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dketeqqmtd .gt_font_normal {\n  font-weight: normal;\n}\n\n#dketeqqmtd .gt_font_bold {\n  font-weight: bold;\n}\n\n#dketeqqmtd .gt_font_italic {\n  font-style: italic;\n}\n\n#dketeqqmtd .gt_super {\n  font-size: 65%;\n}\n\n#dketeqqmtd .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#dketeqqmtd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dketeqqmtd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dketeqqmtd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dketeqqmtd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dketeqqmtd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dketeqqmtd .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">weight_c</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">5%</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">95%</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">−20.0</td>\n<td class=\"gt_row gt_right\">127.7</td>\n<td class=\"gt_row gt_right\">145.4</td></tr>\n    <tr><td class=\"gt_row gt_right\">−15.0</td>\n<td class=\"gt_row gt_right\">132.3</td>\n<td class=\"gt_row gt_right\">149.7</td></tr>\n    <tr><td class=\"gt_row gt_right\">−10.0</td>\n<td class=\"gt_row gt_right\">137.2</td>\n<td class=\"gt_row gt_right\">154.2</td></tr>\n    <tr><td class=\"gt_row gt_right\">−5.0</td>\n<td class=\"gt_row gt_right\">141.4</td>\n<td class=\"gt_row gt_right\">158.5</td></tr>\n    <tr><td class=\"gt_row gt_right\">0.0</td>\n<td class=\"gt_row gt_right\">146.1</td>\n<td class=\"gt_row gt_right\">163.3</td></tr>\n    <tr><td class=\"gt_row gt_right\">5.0</td>\n<td class=\"gt_row gt_right\">150.9</td>\n<td class=\"gt_row gt_right\">167.6</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n\n\n### Perzentilintervalle für verschiedenen Prädiktorwerte visualisiert\n\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-30_554e4167c79ea3958acd515a29514406'}\n\n```{.r .cell-code}\nmus <- \n  mus %>% \n  mutate(height = 154.6 + 0.9*weight_c)\n\nd2 %>% \n  ggplot(aes(x = weight_c, y = height)) +\n  geom_point() +\n  geom_abline(slope = coef(m43a)[2], intercept = coef(m43a)[1], color = \"blue\") +\n  geom_errorbar(data = mus,\n                aes(ymin = `5%`,\n                    ymax = `95%`),\n                size = .5,\n                width = .5,\n                color = \"firebrick\")\n```\n\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\nDie vertikalen Balken geben die 95%-KI wieder, die wir jeweils zu erwarten haben.\n\nNoch eine andere Visualisierung; je dicker die Katzenaugen, desto mehr Samples liegen vor an der Stelle,\nund umso genauer ist die Schätzung.\n\n\n\n::: {.cell hash='lineare-modelle_cache/html/unnamed-chunk-31_48761726161c78a801534d22716e9663'}\n::: {.cell-output-display}\n![](lineare-modelle_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\nAlso: Je dicker die Violine, desto wahrscheinlicher $\\mu | w_i}$.\n\n\n\n### Die PPV visualisiert\n\nGerade eben haben wir bedingte PPVen angeschaut: Also eine PPV für einen bestimmten Prädiktorwert, z.B. bei einer Person mittleren Gewichts.\n\nWir können auch den Mittelwert über alle bedingten PPV anschauen, sozusagen die \"Master-PPV\" oder \"unbedingte PPV\" oder schlicht PPV.\n\n\nVergleichen wir die echten Werte für `height`, $h$, mit den von der PPV simulierten Werten für `height`, $h_{sim}$.\n\n\n::: {.cell hash='lineare-modelle_cache/html/ppv-plot1_44d8b48a5415fb5e598f737b4642c332'}\n\n```{.r .cell-code}\nlibrary(bayesplot)\nh <- d2$height\nh_sim <- \n  posterior_predict(m43a, \n                    draws = 50)\nppc_dens_overlay(\n  h, h_sim)\n```\n:::\n\n\n`?posterior_predict` zeigt Hilfe für diese Funktion. \nDie Funktion zeigt die Vorhersagen für die AV laut der Posteriori-Verteilung.\n\n\n\nDie zwei Gipfel hat unser Modell nicht mitgekriegt, ansonsten decken sich die Vorhersagen der PPV gut mit den echten Daten.\n\n\n\n\n\n### PPV plotten, von Hand\n\n\nPPV berechnen (lassen):\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-27_c70c1887f01d0ed963228675d49cf366'}\n\n```{.r .cell-code}\nset.seed(42)\nppv_m43a <- posterior_predict(\n  m43a,\n  newdata = weight_df,\n  draws = 100) %>% \n  as_tibble() %>% \n  pivot_longer(\n    cols = everything(),\n    names_to = \"weight_condition\",\n    values_to = \"height\")\n```\n:::\n\n\nUnd plotten:\n\n\n::: {.cell fig.asp='0.4' hash='lineare-modelle_cache/html/ppv-regr_7722cc3ee9a09bb69f091f55b0332969'}\n\n```{.r .cell-code}\nppv_m43a %>% \n  ggplot(aes(x = height)) +\n  geom_density()\n```\n:::\n\n\n\n\n\n\n\n\n### Fragen an die PPV\n\n- Wie groß sind die !Kung im Schnitt?\n- Welche Größe wird von 90% der Personen nicht überschritten?\n- Wie groß sind die 10% kleinsten?\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-29_51e2f5774075f9de3bd59beffad791a4'}\n\n```{.r .cell-code}\nppv_m43a %>% \n  summarise(\n    q_10 = quantile(height, prob = .1),\n    height_mean = mean(height),\n    q_50 = quantile(height, prob = .5),\n    q_90 = quantile(height, prob = .9)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     q_10| height_mean|   q_50|     q_90|\n|--------:|-----------:|------:|--------:|\n| 137.5486|    154.4375| 154.49| 171.6555|\n\n</div>\n:::\n:::\n\n\n\nWas ist der 50% Bereich der Körpergröße?\n\n\n::: {.cell hash='lineare-modelle_cache/html/Post-Regression-befragen-30_518ffa894d1913c6324005643df90a94'}\n\n```{.r .cell-code}\nppv_m43a %>% \n  summarise(pi_50 = quantile(height,prob = c(.25, .75)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    pi_50|\n|--------:|\n| 144.1386|\n| 164.9547|\n\n</div>\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}