{
  "hash": "e859e4a263c4d92f6b04c0712922502a",
  "result": {
    "markdown": "# Lineare Modelle\n\n\n## Lernsteuerung\n\n\n### Lernziele\n\nNach Absolvieren des jeweiligen Kapitels sollen folgende Lernziele erreicht sein.\n\nSie können ...\n\n\n\n- die Post-Verteilung für einfache lineare Modelle in R berechnen\n- zentrale Informationen zu Modellparametern - wie Lage- oder Streuungsmaße und auch Schätzintervalle - aus der Post-Verteilung herauslesen\n- künftige, laut Modell zu erwartende Beobachtungen mit der PPV simulieren\n\n\n\n### Vorbereitung im Eigenstudium\n\n- [Statistik1, Kap. \"Geradenmodelle 1\"](https://statistik1.netlify.app/080-regression1)\n\n\n\n\n### Benötigte R-Pakete\n\nIn diesem Kapitel benötigen Sie folgende R-Pakete.\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-1_75b7b9dad9a80cabae35c3facdb718e3'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(easystats)\nlibrary(rstanarm)\n```\n:::\n\n\n\n\n\nDa wir in diesem Kapitel immer mal wieder eine Funktion aus dem R-Paket `{easystats}` verwenden: [Hier](https://easystats.github.io/easystats/articles/list_of_functions.html) finden Sie eine Übersicht aller Funktionen des Pakets.^[Da es viele Funktionen sind, bietet es sich an mit *Strg-F* auf der Webseite nach Ihrem Lieblingsbefehl zu suchen.]\n\n\n### Begleitvideso\n\n- [Prädiktoren zentrieren](https://youtu.be/3Z1dXPO_MSE)\n\n\n## Post-Verteilung der Regression\n\n\n### Einfache Regression\n\n\n\nDie (einfache) Regression prüft, inwieweit zwei Variablen, $Y$ und $X$ linear zusammenhängen.\nJe mehr sie zusammenhängen, desto besser kann man $X$ nutzen, um $Y$ vorherzusagen (und umgekehrt).\nHängen $X$ und $Y$ zusammen, heißt das nicht (unbedingt), dass es einen *kausalen* Zusammenhang zwischen $X$ und $Y$ gibt.\n*Linear* ist ein Zusammenhang, wenn der Zuwachs in $Y$ relativ zu $X$ konstant ist: wenn $X$ um eine Einheit steigt, steigt $Y$ immer um $b$ Einheiten (nicht kausal, sondern deskriptiv gemeint).\n\n[Datenquelle](https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv), @mcelreath_statistical_2020.\n\nLaden wir die !Kung-Daten und visualisieren wir uns den Zusammenhang zwischen Gewicht (X) und Größe (Y), @fig-kung-zshg.\n\n\n\n::: {.cell fig.asp='0.5' hash='0900-lineare-modelle_cache/html/fig-kung-zshg_6f4497d8f713dd24078f766144ddbc00'}\n\n```{.r .cell-code}\nKung_path <- \"https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv\"\n\nd <- read_csv(Kung_path)  \n\nd2 <- \n  d %>% \n  filter(age > 18) \n\nd2 %>% \n  ggplot(\n       aes(x = weight, y = height)) +\n  geom_point(alpha = .7) +\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![Der Zusammenhang von Größe und Gewicht im !Kung-Datensatz](0900-lineare-modelle_files/figure-html/fig-kung-zshg-1.png){#fig-kung-zshg width=672}\n:::\n:::\n\n\n\n\n\n\n### Bei jedem Prädiktorwert eine Post-Verteilung für $\\mu$\n\n\nKomfort pur: Unser Modell erlaubt uns für jeden beliebigen Wert des Prädiktors eine Post-Verteilung (von $\\mu$) zu berechnen.\n\nHier am Beispiel von `m42`, s. @fig-post42.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/m42-read-from-disk_94864f23032b33991869d8d697c08e50'}\n\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-10_4b9a65c7128d66338221c3bf793fc39c'}\n\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Plot-condition_6d974d24bdaefd7d4b9efdf08bd047f7'}\n\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/m3_e7bfbe4658b664c93ddc7675d4a6515e'}\n\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/objects-m43-m43a-to-disk_7b8f4dfd18bce6ce05c013aa554ccd3f'}\n\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/m43-plot_7a875dcd073aa461708f6a18f59d75aa'}\n\n:::\n\n::: {.cell fig.asp='1' hash='0900-lineare-modelle_cache/html/fig-post42_5684c6c085cf5fc86fc673ed23c50e2c'}\n::: {.cell-output-display}\n![Für jeden beliebigen Prädiktorwert kann man eine Post-Verteilung bekommen. A: Regressionsmodell mit einigen ausgewählten Gewichtswerten. B: Für jeden beliebigen Gewichtswert bekommt man eine Post-Verteilung](0900-lineare-modelle_files/figure-html/fig-post42-1.png){#fig-post42 width=100%}\n:::\n:::\n\n\n\n\n\n\n### Statistiken zum !Kung-Datensatz\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-2_159a4a9cdd86b162ebdc16b59a6aa90f'}\n\n:::\n\n\n\n[Datenquelle](https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv)\n\n\n@tbl-kung1 zeigt die zentralen deskriptiven Statistiken zum !Kung-Datensatz.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-3_e0cff5d753f63dcd846c9f5ca6f16e7c'}\n\n```{.r .cell-code}\nKung_path <- \"https://raw.githubusercontent.com/sebastiansauer/Lehre/main/data/Howell1a.csv\"  \nd <- read_csv(Kung_path)  \n\nd2 <- d %>% filter(age > 18)\n\ndescribe_distribution(d2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Variable |        Mean|         SD|       IQR|       Min|       Max|  Skewness|   Kurtosis|   n| n_Missing|\n|:--------|-----------:|----------:|---------:|---------:|---------:|---------:|----------:|---:|---------:|\n|height   | 154.6443688|  7.7735641| 12.065000| 136.52500| 179.07000| 0.1434736| -0.4973852| 346|         0|\n|weight   |  45.0455429|  6.4552197|  9.135626|  31.52464|  62.99259| 0.1398158| -0.5317283| 346|         0|\n|age      |  41.5397399| 15.8093044| 22.000000|  19.00000|  88.00000| 0.6758624| -0.2014534| 346|         0|\n|male     |   0.4739884|  0.5000461|  1.000000|   0.00000|   1.00000| 0.1046415| -2.0006483| 346|         0|\n\n</div>\n:::\n:::\n\n::: {#tbl-kung1 .cell tbl-cap='Verteiung der (metrischen) Variablen im !Kung-Datensatz' hash='0900-lineare-modelle_cache/html/tbl-kung1_0b699aeb551822bf8b5e54bd08e27d32'}\n::: {.cell-output-display}\n|Variable |   Mean |    SD |   IQR |            Range | Skewness | Kurtosis |   n | n_Missing |\n|:--------|:------:|:-----:|:-----:|:----------------:|:--------:|:--------:|:---:|:---------:|\n|height   | 154.64 |  7.77 | 12.06 | (136.53, 179.07) |     0.14 |    -0.50 | 346 |         0 |\n|weight   |  45.05 |  6.46 |  9.14 |   (31.52, 62.99) |     0.14 |    -0.53 | 346 |         0 |\n|age      |  41.54 | 15.81 | 22.00 |   (19.00, 88.00) |     0.68 |    -0.20 | 346 |         0 |\n|male     |   0.47 |  0.50 |  1.00 |     (0.00, 1.00) |     0.10 |    -2.00 | 346 |         0 |\n:::\n:::\n\n\n\nWie aus @tbl-kung1 abzulesen ist, beträgt das mittlere Körpergewicht (`weight`) liegt ca. 45kg (sd 7 kg).\n\n\n### Etwas mehr EDA\n\n\n\n\nWir brauchen die EDA hier nicht wirklich, aber es ist praktisch. Das Paket `DataExplorer` hat ein paar nette Hilfen zur explorativen Datenanalyse.\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-3_98c8a33b934a08997bfc51483fe9c477'}\n\n```{.r .cell-code}\nlibrary(DataExplorer)\n```\n:::\n\n\n#### Gibt es fehlende Werte?\n\nNein, s. Abb. @fig-na.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-na_3d936f60c316bab272fa695b6aec8380'}\n\n```{.r .cell-code}\nd2 %>% plot_missing()\n```\n\n::: {.cell-output-display}\n![Fehlende Werte - fehlen.](0900-lineare-modelle_files/figure-html/fig-na-1.png){#fig-na width=672}\n:::\n:::\n\n\n\n\n#### Verteilung der numerischen Variablen\n\nBetrachten wir die Verteilung der *numerischen* Variablen des Datensatzes, s. @fig-d2-hists.\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-d2-hists_0defef51feee2eb6acb6b7f2c4ca1fac'}\n\n```{.r .cell-code}\nd2 %>% plot_histogram()\n```\n\n::: {.cell-output-display}\n![Verteilung (als Histogramme dargestellt) der numerischen Variablen des Datensatzes](0900-lineare-modelle_files/figure-html/fig-d2-hists-1.png){#fig-d2-hists width=672}\n:::\n:::\n\n\n\n\n#### Verteilung der kategorialen Variablen\n\n\nBetrachten wir die Verteilung der *kategorialen* Variablen des Datensatzes, s. @fig-d2-bars.\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-d2-bars_5eae62a00608ad203dd0a9ea6aca04c3'}\n\n```{.r .cell-code}\nd2 %>% plot_bar()\n```\n\n::: {.cell-output-display}\n![Verteilung (als Balkendiagramme dargestellt) der kategorialen Variablen des Datensatzes](0900-lineare-modelle_files/figure-html/fig-d2-bars-1.png){#fig-d2-bars width=672}\n:::\n:::\n\n\n\n\n#### Korrelationen\n\nDie Korrelationen der (numerischen) Variablen sind in @fig-num-korrs dargestellt.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-num-korrs_9713cc8c782f6bdf0c0e5596a557a328'}\n\n```{.r .cell-code}\nd2 %>% plot_correlation()\n```\n\n::: {.cell-output-display}\n![Korrelationsmatrix](0900-lineare-modelle_files/figure-html/fig-num-korrs-1.png){#fig-num-korrs width=672}\n:::\n:::\n\n\n\n#### Bonus\n\nProbieren Sie mal die folgende Funktion aus, die Ihnen einen Bericht zur EDA erstellt: `create_report(d2)`.\n\n\n\n\n\n\n\n\n### Prädiktor zentrieren \n\n\n\n\nZieht man von jedem Gewichtswert den Mittelwert ab, so bekommt man die Abweichung des Gewichts vom Mittelwert (Prädiktor \"zentrieren\", engl. to *c*enter).\nWenn man den Prädiktor (`weight`) zentriert hat, ist der Achsenabschnitt, $\\alpha$, einfacher zu verstehen.\nIn einem Modell mit zentriertem Prädiktor (`weight`) gibt der Achsenabschnitt die Größe einer Person mit durchschnittlichem Gewicht an. \nWürde man `weight` nicht zentrieren, gibt der Achsenabschnitt die Größe einer Person mit `weight=0` an, was nicht wirklich sinnvoll zu interpretieren ist.\n\n\n\nVgl. @gelman_regression_2021, Kap. 10.4,  12.2.\n\n\n\n\nSo kann man das Zentrieren bewerkstelligen (mit Hilfe von `center` aus `{easystats}`):\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-8_18678d38a0026ff7ac673515805f5e0e'}\n\n```{.r .cell-code}\nd3 <- \n  d2 %>% \n  mutate(weight_c = as.numeric(center(weight)))\n```\n:::\n\n\n\n\nOder so, von Hand:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-7_4778ccb4acb85dcd65246c549d5c8361'}\n\n```{.r .cell-code}\nd3 <-\n  d2 %>% \n  mutate(weight_c = weight - mean(weight))\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-8_8caed66a795260413bf68424afe22de5'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"bcbxpznrhr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bcbxpznrhr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bcbxpznrhr thead, #bcbxpznrhr tbody, #bcbxpznrhr tfoot, #bcbxpznrhr tr, #bcbxpznrhr td, #bcbxpznrhr th {\n  border-style: none;\n}\n\n#bcbxpznrhr p {\n  margin: 0;\n  padding: 0;\n}\n\n#bcbxpznrhr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bcbxpznrhr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bcbxpznrhr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bcbxpznrhr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bcbxpznrhr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bcbxpznrhr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bcbxpznrhr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bcbxpznrhr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bcbxpznrhr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bcbxpznrhr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bcbxpznrhr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bcbxpznrhr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bcbxpznrhr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bcbxpznrhr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bcbxpznrhr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcbxpznrhr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bcbxpznrhr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bcbxpznrhr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bcbxpznrhr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcbxpznrhr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bcbxpznrhr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcbxpznrhr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bcbxpznrhr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcbxpznrhr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bcbxpznrhr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bcbxpznrhr .gt_left {\n  text-align: left;\n}\n\n#bcbxpznrhr .gt_center {\n  text-align: center;\n}\n\n#bcbxpznrhr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bcbxpznrhr .gt_font_normal {\n  font-weight: normal;\n}\n\n#bcbxpznrhr .gt_font_bold {\n  font-weight: bold;\n}\n\n#bcbxpznrhr .gt_font_italic {\n  font-style: italic;\n}\n\n#bcbxpznrhr .gt_super {\n  font-size: 65%;\n}\n\n#bcbxpznrhr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bcbxpznrhr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bcbxpznrhr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bcbxpznrhr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bcbxpznrhr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bcbxpznrhr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bcbxpznrhr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"height\">height</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"weight\">weight</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"male\">male</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"weight_c\">weight_c</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"height\" class=\"gt_row gt_right\">152</td>\n<td headers=\"weight\" class=\"gt_row gt_right\">48</td>\n<td headers=\"age\" class=\"gt_row gt_right\">63</td>\n<td headers=\"male\" class=\"gt_row gt_right\">1</td>\n<td headers=\"weight_c\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"height\" class=\"gt_row gt_right\">140</td>\n<td headers=\"weight\" class=\"gt_row gt_right\">36</td>\n<td headers=\"age\" class=\"gt_row gt_right\">63</td>\n<td headers=\"male\" class=\"gt_row gt_right\">0</td>\n<td headers=\"weight_c\" class=\"gt_row gt_right\">−9</td></tr>\n    <tr><td headers=\"height\" class=\"gt_row gt_right\">137</td>\n<td headers=\"weight\" class=\"gt_row gt_right\">32</td>\n<td headers=\"age\" class=\"gt_row gt_right\">65</td>\n<td headers=\"male\" class=\"gt_row gt_right\">0</td>\n<td headers=\"weight_c\" class=\"gt_row gt_right\">−13</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\nWie man sieht, ist die Verteilung \"zur Seite geschoben\": Der Mittelwert liegt jetzt eben bei 0, s. @fig-d3-center.\n\n\n\n\n::: {.cell fig.asp='0.4' hash='0900-lineare-modelle_cache/html/fig-d3-center_6981dc230e72350ab3f4c857d74b7962'}\n::: {.cell-output-display}\n![Das Zentrieren ändert die Verteilungsform nicht, sondern \"schiebt\" die Verteilung nur zur Seite](0900-lineare-modelle_files/figure-html/fig-d3-center-1.png){#fig-d3-center width=672}\n:::\n:::\n\n\n\n\nDas schwierigste ist dabei, nicht zu vergessen, dass `d3` die Tabelle mit zentriertem Prädiktor ist, nicht `d2`.\n\n\n## Modell m43: zentrierter Prädiktor\n\n\nEinige Regressionskoeffizienten, wie der Achsenabschnitt (Intercept) sind schwer zu interpretieren:\nBei einem (erwachsenen) Menschen mit *Gewicht 0*, was wäre wohl die Körpergröße?\nHm, Philosophie steht heute nicht auf der Tagesordnung.\n\nDa wäre es schön, wenn wir die Daten so umformen könnten, dass der Achsenabschnitt eine sinnvolle Aussage macht.\nZum Glück geht das leicht: Wir zentrieren den Prädiktor (Gewicht)!\n\n\n:::callout-important\nDurch Zentrieren kann man die Ergebnisse einer Regression einfacher interpretieren.\n:::\n\n\n\n\n\n### Modelldefinition von `m43`\n\nFür jede Ausprägung des Prädiktors (`weight_centered`), $wc_i$, wird eine Post-Verteilung für die abhängige Variable (`height`, $h_i$) berechnet.\nDer Mittelwert $\\mu$ für jede Post-Verteilung ergibt sich aus dem linearen Modell (unserer Regressionsformel).\n Die Post-Verteilung berechnet sich auf Basis der Priori-Werte und des Likelihood (Bayes-Formel).\n Wir brauchen Priori-Werte für die Steigung $\\beta$ und den Achsenabschnitt $\\alpha$ der Regressionsgeraden.\n Außerdem brauchen wir einen Priori-Wert, der die Streuung $\\sigma$ der Größe (`height`) angibt; dieser Wert wird als exonentialverteilt angenommen.\n Der Likelihood gibt an, wie wahrscheinlich ein Wert `height` ist, gegeben $\\mu$ und $\\sigma$.\n\n\n\\begin{align*}\n\\color{red}{\\text{height}_i} & \\color{red}\\sim \\color{red}{\\operatorname{Normal}(\\mu_i, \\sigma)} && \\color{red}{\\text{Likelihood}} \\\\\n\\color{green}{\\mu_i} & \\color{green}= \\color{green}{\\alpha + \\beta\\cdot \\text{weightcentered}_i}  && \\color{green}{\\text{Lineares Modell} } \\\\\n\\color{blue}\\alpha & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(178, 20)} && \\color{blue}{\\text{Priori}} \\\\\n\\color{blue}\\beta  & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(0, 10)}  && \\color{blue}{\\text{Priori}}\\\\\n\\color{blue}\\sigma & \\color{blue}\\sim \\color{blue}{\\operatorname{Exp}(0.1)}  && \\color{blue}{\\text{Priori}}\n\\end{align*}\n\n\n\n:::callout-note\nDer Achsenabschnit (engl. *intercept*) eines Regressionsmodell wird in der Literatur oft mit $\\beta_0$ bezeichnet,\naber manchmal auch mit $\\alpha$.\nUnd manchmal mit noch anderen Buchstaben, das Alphabet ist weit. 🤷\n:::\n\n\n\n\n\n\n### Likelihood, `m43`\n\n\n\n$$\n\\begin{aligned}\n\\color{red}{\\text{height}_i} & \\color{red}\\sim \\color{red}{\\operatorname{Normal}(\\mu_i, \\sigma)} && \\color{red}{\\text{Likelihood}}\n\\end{aligned}\n$$\n\n\n\n\n Der Likelihood von `m43` ist ähnlich zu den vorherigen Modellen (`m41, m42`).\n Nur gibt es jetzt ein kleines \"Index-i\" am $\\mu$ und am $h$ (h wie `heights`).\n Es gibt jetzt nicht mehr nur einen Mittelwert $\\mu$, sondern für jede Beobachtung (Zeile) einen Mittelwert $\\mu_i$.\n Lies  etwa so:\n\n>    \"Die Wahrscheinlichkeit, eine bestimmte Größe bei Person $i$ zu beobachten, gegeben $\\mu$ und $\\sigma$ ist normalverteilt (mit Mittelwert $\\mu$ und Streuung $\\sigma$)\".\n\n\n\n\n### Regressionsformel, `m43`\n\n\n$$\n\\begin{aligned}\n\\color{green}{\\mu_i} & \\color{green}= \\color{green}{\\alpha + \\beta\\cdot \\text{weight}_i}  && \\color{green}{\\text{Lineares Modell} } \\\\\n\\end{aligned}\n$$\n\n\n $\\mu$ ist jetzt nicht mehr ein Parameter, der (stochastisch) geschätzt werden muss. $\\mu$ wird jetzt (deterministisch) *berechnet*. Gegeben $\\alpha$ und $\\beta$ ist $\\mu$ ohne Ungewissheit bekannt.\n $\\text{weight}_i$ ist der Prädiktorwert (`weight`) der $i$ten Beobachtung, also einer !Kung-Person (Zeile $i$ im Datensatz).\nLies  etwa so:\n\n>    \"Der Mittelwert $\\mu_i$ der $i$ten Person berechnet sich als Summe von $\\alpha$ und $\\beta$ mal  $\\text{weight}_i$\".\n\n\n $\\mu_i$ ist eine lineare Funktion von `weight`.\n $\\beta$ gibt den Unterschied in `height` zweier Beobachtung an, die sich um eine Einheit in `weight` unterscheiden (Steigung der Regressionsgeraden).\n $\\alpha$ gibt an, wie groß $\\mu$ ist, wenn `weight` Null ist (Achsenabschnitt, engl. intercept).\n\n\n\n### Priori-Werte des Modells `m43`\n\n\n\n\\begin{align*}\n\\color{blue}\\alpha & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(178, 20)} && \\color{blue}{\\text{Priori Achsenabschnitt}} \\\\\n\\color{blue}\\beta  & \\color{blue}\\sim \\color{blue}{\\operatorname{Normal}(0, 10)}  && \\color{blue}{\\text{Priori Regressionsgewicht}}\\\\\n\\color{blue}\\sigma & \\color{blue}\\sim \\color{blue}{\\operatorname{Exp}(0.1)}  && \\color{blue}{\\text{Priori Sigma}}\n\\end{align*}\n\n- Parameter sind hypothetische Kreaturen: Man kann sie nicht beobachten, sie existieren nicht wirklich. Ihre Verteilungen nennt man Priori-Verteilungen.\n- $\\alpha$ wurde in `m41` als $\\mu$ bezeichnet, da wir dort eine \"Regression ohne Prädiktoren\" berechnet haben.\n- $\\sigma$ ist uns schon als Parameter bekannt und behält seine Bedeutung aus dem letzten Kapitel.\n- Da `height` nicht zentriert ist, der Mittelwert von $\\alpha$ bei 178 und nicht 0.\n- $\\beta$ fasst unser Vorwissen, ob und wie sehr der Zusammenhang zwischen Gewicht und Größe positiv (gleichsinnig) ist.\n\n\n\n\n\n\n## Vertiefung: Prior-Prädiktiv-Verteilung\n\n🏎️ VERTIEFUNG, nicht prüfungsrelevant 🏎️\n\n### Moment\n\n 🤔 Moment. Dieser Prior, $\\beta$ in `m43` erachtet positive und negative Zusammenhang als gleich wahrscheinlich?!\n\nSind wir wirklich indifferent, ob der Zusammenhang von Gewicht und Größe positiv oder negativ ist? [Nein, sind wir nicht.](https://media.giphy.com/media/daPCSjwus6UR2JxRX1/giphy.gif) \n    \n\n\n### Priori-Prädiktiv-Verteilung für `m43`\n\n\n\nWas denkt [wir](https://media.giphy.com/media/Aausss8uUBIe3bZ3d2/giphy.gif) bzw. unser Golem *apriori* über den Zusammenhang von Größe und Gewicht?\nUm diese Frage zu beantworten ziehen wir Stichproben aus den Priori-Verteilungen des Modells, also für $\\alpha$, $\\beta$ und $\\sigma$.\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/m43-prior-pred_d152e483440f78ef8cdb7e8b1c19015b'}\n\n```{.r .cell-code}\nm43_prior_pred <-\n    stan_glm(height ~ weight_c, \n             prior = normal(0, 10),\n             prior_intercept = normal(178, 20),  # mu\n             prior_aux = exponential(0.1),  # sigma\n             refresh = FALSE, \n             prior_PD = TRUE,  # Schalter für Prior-Pred-Verteilung\n             data = d3)\n\n\nm43_prior_pred_draws <- \n  m43_prior_pred %>% \n  as_tibble() %>% \n  rename(a = `(Intercept)`,\n         b = weight_c) %>% \n  slice_sample(n = 50)\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-9_5dbe6191cd6b341c48b4f471442b9331'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"wfnhdrdimg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wfnhdrdimg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wfnhdrdimg thead, #wfnhdrdimg tbody, #wfnhdrdimg tfoot, #wfnhdrdimg tr, #wfnhdrdimg td, #wfnhdrdimg th {\n  border-style: none;\n}\n\n#wfnhdrdimg p {\n  margin: 0;\n  padding: 0;\n}\n\n#wfnhdrdimg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wfnhdrdimg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wfnhdrdimg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wfnhdrdimg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wfnhdrdimg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wfnhdrdimg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wfnhdrdimg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wfnhdrdimg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wfnhdrdimg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wfnhdrdimg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wfnhdrdimg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wfnhdrdimg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wfnhdrdimg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wfnhdrdimg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wfnhdrdimg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wfnhdrdimg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wfnhdrdimg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wfnhdrdimg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wfnhdrdimg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wfnhdrdimg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wfnhdrdimg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wfnhdrdimg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wfnhdrdimg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wfnhdrdimg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wfnhdrdimg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wfnhdrdimg .gt_left {\n  text-align: left;\n}\n\n#wfnhdrdimg .gt_center {\n  text-align: center;\n}\n\n#wfnhdrdimg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wfnhdrdimg .gt_font_normal {\n  font-weight: normal;\n}\n\n#wfnhdrdimg .gt_font_bold {\n  font-weight: bold;\n}\n\n#wfnhdrdimg .gt_font_italic {\n  font-style: italic;\n}\n\n#wfnhdrdimg .gt_super {\n  font-size: 65%;\n}\n\n#wfnhdrdimg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wfnhdrdimg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wfnhdrdimg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wfnhdrdimg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wfnhdrdimg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wfnhdrdimg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wfnhdrdimg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a\">a</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"b\">b</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sigma\">sigma</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">225.2</td>\n<td headers=\"b\" class=\"gt_row gt_right\">0.8</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">0.5</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">212.0</td>\n<td headers=\"b\" class=\"gt_row gt_right\">−17.9</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">25.6</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">136.0</td>\n<td headers=\"b\" class=\"gt_row gt_right\">−8.9</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">18.5</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">154.9</td>\n<td headers=\"b\" class=\"gt_row gt_right\">−2.3</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">3.8</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">201.7</td>\n<td headers=\"b\" class=\"gt_row gt_right\">−19.7</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">17.8</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\nJede Zeile definiert eine Regressionsgerade.\n\n\n\n### Prior-Prädiktiv-Simulation für `m43` mit `stan_glm()` \n\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-10_a4d793495369e387e0d2d9382482e02e'}\n\n```{.r .cell-code}\nm43_prior_pred <-\n    stan_glm(height ~ weight_c, \n             prior = normal(0, 10),  # beta\n             prior_intercept = normal(178, 20),  # alpha\n             prior_aux = exponential(0.1),  # sigma\n             refresh = FALSE, \n             prior_PD = TRUE,  # DIESER Schalter macht's\n             data = d3)\n\nm43_prior_pred_draws <- \n  m43_prior_pred %>% \n  as_tibble() %>% \n  rename(a = `(Intercept)`,\n         b = weight_c) %>% \n  slice_sample(n = 50)\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-11_468d95636a4b766c3ed8e000ba357c1a'}\n\n:::\n\n\n\n\n\n\n\n\n\n\n### Visualisieren der Prior-Prädiktiv-Verteilung\n\n\n\n\n::: {.cell fig.asp='0.5' hash='0900-lineare-modelle_cache/html/prior-pv1_f468906cea9a0d06bb4f4e12e442e3c0'}\n\n```{.r .cell-code}\nd3 %>% ggplot() +\n  geom_point(aes(x = weight_c, y = height)) + \n  geom_abline(data = m43_prior_pred_draws,\naes(intercept = a, slope = b), color = \"skyblue\", size = 0.2) +\n  scale_y_continuous(limits = c(0, 500)) +\n  geom_hline(yintercept = 272, size = .5) +\n  geom_hline(yintercept = 0, linetype = \"dashed\")\n```\n:::\n\n\n\n\n🤯 Einige dieser Regressionsgeraden sind unsinnig!\n\n\n\n::: {.cell fig.asp='0.3' hash='0900-lineare-modelle_cache/html/unnamed-chunk-12_c5a75acd2153b023df682ee9ce170186'}\n\n```{.r .cell-code}\nd3 %>% ggplot() +\n  geom_point(aes(x = weight_c, y = height)) + \n  geom_abline(data = m43_prior_pred_draws,\naes(intercept = a, slope = b), color = \"skyblue\", size = 0.2) +\n  scale_y_continuous(limits = c(0, 500)) +\n  geom_hline(yintercept = 272, size = .5) +\n  geom_hline(yintercept = 0, linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\nDie durchgezogene horizontale Linie gibt die Größe des [größten Menschens, Robert Pershing Wadlow](https://en.wikipedia.org/wiki/Robert_Wadlow), an.\n\n\n\n\n\n### Ein positiver Wert für $\\beta$ ist plausibler\n\n\n#### Oh no\n\nEine Normalverteilung mit viel Streuung:\n\n\n::: {.cell fig.asp='0.5' hash='0900-lineare-modelle_cache/html/Post-Regression-16_7ff08e4c23babe4f0a16310be3928264'}\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/Post-Regression-16-1.png){width=672}\n:::\n:::\n\n\n👎 $\\beta=-20$ wäre mit diesem Prior gut möglich: Pro kg Gewicht sind Menschen im Schnitt 20cm kleiner, laut dem Modell. Quatsch.\n\n\n\n\n#### Oh yes\n\nWir bräuchten eher so eine Verteilung, mit mehr Masse auf der positiven Seite (x>0):\n\n\n::: {.cell fig.asp='0.5' hash='0900-lineare-modelle_cache/html/Post-Regression-17_b49cbf8e6012111a8336e3f25c07cb93'}\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/Post-Regression-17-1.png){width=672}\n:::\n:::\n\n\n👍 Vermutlich besser: Ein Großteil der Wahrscheinlichkeitsmasse ist $X>0$. Allerdings gibt's keine Gewähr, dass unser Prior \"richtig\" ist.\n\n\n\n\n### Priori-Prädiktiv-Simulation, 2. Versuch\n\n\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-13_121f506aa90ec0f8ed4f6cefc053b39f'}\n\n```{.r .cell-code}\nm43a_prior_pred <-\n    stan_glm(\n      height ~ weight_c, \n      prior = normal(2, 2),  # Regressionsgewicht\n      prior_intercept = normal(178, 20),  # mu\n      prior_aux = exponential(0.1),  # sigma\n      refresh = FALSE, \n      # Schalter für Prior-Pred-Verteilung:\n      prior_PD = TRUE, \n      data = d3)\n\n\nm43a_prior_pred_draws <- \n  m43a_prior_pred %>% \n  as_tibble() %>% \n  # Spaltennamen kürzen: \n  rename(a = `(Intercept)`) %>%  \n  rename(b = weight_c,\n         s = sigma)\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-14_bbe0db1ca309da4652e0d95b94a32ad4'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"yfnredceor\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yfnredceor table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yfnredceor thead, #yfnredceor tbody, #yfnredceor tfoot, #yfnredceor tr, #yfnredceor td, #yfnredceor th {\n  border-style: none;\n}\n\n#yfnredceor p {\n  margin: 0;\n  padding: 0;\n}\n\n#yfnredceor .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yfnredceor .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yfnredceor .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yfnredceor .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yfnredceor .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yfnredceor .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yfnredceor .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yfnredceor .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yfnredceor .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yfnredceor .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yfnredceor .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yfnredceor .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yfnredceor .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yfnredceor .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yfnredceor .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yfnredceor .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yfnredceor .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yfnredceor .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yfnredceor .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yfnredceor .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yfnredceor .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yfnredceor .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yfnredceor .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yfnredceor .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yfnredceor .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yfnredceor .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yfnredceor .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yfnredceor .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yfnredceor .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yfnredceor .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yfnredceor .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yfnredceor .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yfnredceor .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yfnredceor .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yfnredceor .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yfnredceor .gt_left {\n  text-align: left;\n}\n\n#yfnredceor .gt_center {\n  text-align: center;\n}\n\n#yfnredceor .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yfnredceor .gt_font_normal {\n  font-weight: normal;\n}\n\n#yfnredceor .gt_font_bold {\n  font-weight: bold;\n}\n\n#yfnredceor .gt_font_italic {\n  font-style: italic;\n}\n\n#yfnredceor .gt_super {\n  font-size: 65%;\n}\n\n#yfnredceor .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yfnredceor .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yfnredceor .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yfnredceor .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yfnredceor .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yfnredceor .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yfnredceor .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a\">a</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"b\">b</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"s\">s</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">199.3</td>\n<td headers=\"b\" class=\"gt_row gt_right\">3.8</td>\n<td headers=\"s\" class=\"gt_row gt_right\">1.2</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">186.7</td>\n<td headers=\"b\" class=\"gt_row gt_right\">3.4</td>\n<td headers=\"s\" class=\"gt_row gt_right\">0.6</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">177.5</td>\n<td headers=\"b\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"s\" class=\"gt_row gt_right\">54.9</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">176.0</td>\n<td headers=\"b\" class=\"gt_row gt_right\">1.3</td>\n<td headers=\"s\" class=\"gt_row gt_right\">0.1</td></tr>\n    <tr><td headers=\"a\" class=\"gt_row gt_right\">177.7</td>\n<td headers=\"b\" class=\"gt_row gt_right\">4.4</td>\n<td headers=\"s\" class=\"gt_row gt_right\">23.6</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\nDas Argument `prior_PD = TRUE` sorgt dafür, dass keine Posteriori-Verteilung, sondern eine Prior-Prädiktiv-Verteilung berechnet wird.\n\n\n\n\n### Visualisieren der Prior-Prädiktiv-Verteilung, `m43a`\n\n\nUnsere Priori-Werte scheinen einigermaßen vernünftige Vorhersagen zu tätigen. Allerdings erwartet unser Golem einige Riesen.\n\n\n\n::: {.cell fig.asp='0.5' hash='0900-lineare-modelle_cache/html/unnamed-chunk-15_0be1a09888cb2b51960cd3ebc176a40d'}\n\n```{.r .cell-code}\nd3 %>% \n  ggplot(aes(x = weight_c, y = height)) +\n  geom_point() +\n  geom_abline(data = {m43a_prior_pred_draws %>% slice_head(n=50)},\n              aes(slope = b,\n                  intercept = a),\n              color = \"skyblue\",\n              size = .2,\n              alpha = .7) +\n  geom_hline(yintercept = 272, size = .5) +\n  geom_hline(yintercept = 0, linetype = \"dashed\")+\n  scale_y_continuous(limits = c(0, 500)) \n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\nDie durchgezogene horizontale Linie gibt die Größe des [größten Menschens, Robert Pershing Wadlow](https://en.wikipedia.org/wiki/Robert_Wadlow), an.\n\n\n\n\n\n\n\n\n### Moment, kann hier jeder machen, was er will?\n\n\n\nEs doch den einen, richtigen, objektiven Priori-Wert geben?!\n\nKann denn jeder hier machen, was er will?! Wo kommen wir da hin?!\n\n\n>    This is a mistake. There is no more a uniquely correct prior than there is a uniquely correct likelihood. Statistical models are machines for inference. Many machines will work, but some work better than others. Priors can be wrong, but only in the same sense that a kind of hammer can be wrong for building a table.  \n\n@mcelreath_statistical_2020, p. 96.\n\n\n\n\n\n### Hier ist unser Modell, `m43a`\n\n\n\n\n\\begin{align}\n\\text{height}_i &\\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i &= \\alpha + \\beta \\cdot  \\text{weight}_i\\\\\n\\alpha &\\sim \\operatorname{Normal}(178, 20)\\\\\n\\beta &\\sim \\operatorname{Normal}(5,3)\\\\\n\\sigma &\\sim \\operatorname{Exp}(0.1)\n\\end{align}\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-25_2e7a5f97afb9797ff3b58a9282dd6b52'}\n\n```{.r .cell-code}\n# Posteriori-Vert. berechnen:\nm43a <-\n  stan_glm(\n    height ~ weight_c,  # Regressionsformel\n    prior = normal(5, 3),  # Regressionsgewicht (beta 1)\n    prior_intercept = normal(178, 20),  # mu\n    prior_aux = exponential(0.1),  # sigma\n    refresh = 0,  # zeig mir keine Details\n    seed = 42,  # Zufallszahlen festlegen\n    data = d3)\n```\n:::\n\n\n\n\n\n\n### Eine Zusammenfassung der Posteriori-Verteilung für `m43a`\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-16_4d8a890297f77a1340d23c627b8402d1'}\n\n```{.r .cell-code}\nm43a %>% \n  parameters()\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-17_a7a232a0ddf727623075e0c8569d77ef'}\n::: {.cell-output-display}\n|Parameter   | Median |           95% CI |   pd |  Rhat |     ESS |              Prior |\n|:-----------|:------:|:----------------:|:----:|:-----:|:-------:|:------------------:|\n|(Intercept) | 154.65 | (154.14, 155.19) | 100% | 0.999 | 3214.00 | Normal (178 +- 20) |\n|weight_c    |   0.91 |     (0.82, 0.99) | 100% | 1.001 | 4134.00 |    Normal (5 +- 3) |\n:::\n:::\n\n\n\n\nUnser Modell `m43a` schätzt die typische Körpergröße einer !Kung-Person *mittleren Gewichts* (`weight_c = 0`) auf knapp 155 cm, und ist sich dieses Werts ziemlich sicher.\nPro Kilogramm kommt (laut unserem Modell) ein knapper Zentimeter hinzu, typischerweise;\nauch hier ist sich das Modell ziemlich sicher, da dass zugehörige 95%-CI keine 20 Zentimenter umfasst.\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Die Post-Verteilung befragen\n\n\n### m43a\n\n\nSagen wir, auf Basis gut geprüfter Evidenz haben wir folgendes Modell festgelegt: `height ~ weight_c`, s. @eq-m43a.\n\nPrioris:\n\n$$\\beta_1 \\sim N(5,3); \\\\\n\\beta_0 \\sim N(178, 20); \\\\\n\\sigma \\sim E(0.1)$${#eq-m43a}\n\n\nWir nennen das Modell `m43a`^[Wer ist hier für die Namensgebung zuständig? Besoffen oder was?], s. @lst-m43a.\n\n\n\n\n```{#lst-m43a .r lst-cap=\"Modelldefinition von m43a in R\"}\nm43a <-\n  stan_glm(\n    height ~ weight_c,  # Regressionsformel\n    prior = normal(5, 3),  # Regressionsgewicht (beta 1)\n    prior_intercept = normal(178, 20),  # mu\n    prior_aux = exponential(0.1),  # sigma\n    refresh = 0,  # zeig mir keine Details\n    seed = 42,  # lege die Zufallszahlen fest für Reproduzierbarkeit\n    data = d3)\n```\n\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/m43a_87a32d647ff640d3ef5a4bdfe91ba7ce'}\n\n:::\n\n\n\n:::callout-note\nMit `seed` kann man die Zufallszahlen fixieren,\nso dass jedes Mal die gleichen Werte resultieren.\nSo ist die Nachprüfbarkeit der Ergebnisse (\"Reproduzierbarkeit\") sichergestellt^[oder zumindest *besser* sichergestellt].\nWelche Wert für `seed` man verwendet, ist egal,\nsolange alle den gleichen verwenden.\nDer Autor verwendet z.B. oft den Wert 42.\nZur Erinnerung: Der Golem zieht Zufallszahlen,\ndamit erstellt er Stichproben, die die Postverteilung schätzen.\n:::\n\n\n\n\n### Mittelwerte von $\\alpha$ und $\\beta$ aus der Post-Verteilung\n\n\n\nDie ersten paar Zeilen:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-3_396fc4ef52f8e1714675b53ad4e5164d'}\n::: {.cell-output-display}\n```{=html}\n<div id=\"bqwelppemb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bqwelppemb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bqwelppemb thead, #bqwelppemb tbody, #bqwelppemb tfoot, #bqwelppemb tr, #bqwelppemb td, #bqwelppemb th {\n  border-style: none;\n}\n\n#bqwelppemb p {\n  margin: 0;\n  padding: 0;\n}\n\n#bqwelppemb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bqwelppemb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bqwelppemb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bqwelppemb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bqwelppemb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bqwelppemb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bqwelppemb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bqwelppemb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bqwelppemb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bqwelppemb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bqwelppemb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bqwelppemb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bqwelppemb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bqwelppemb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bqwelppemb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bqwelppemb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bqwelppemb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bqwelppemb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bqwelppemb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bqwelppemb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bqwelppemb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bqwelppemb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bqwelppemb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bqwelppemb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bqwelppemb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bqwelppemb .gt_left {\n  text-align: left;\n}\n\n#bqwelppemb .gt_center {\n  text-align: center;\n}\n\n#bqwelppemb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bqwelppemb .gt_font_normal {\n  font-weight: normal;\n}\n\n#bqwelppemb .gt_font_bold {\n  font-weight: bold;\n}\n\n#bqwelppemb .gt_font_italic {\n  font-style: italic;\n}\n\n#bqwelppemb .gt_super {\n  font-size: 65%;\n}\n\n#bqwelppemb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bqwelppemb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bqwelppemb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bqwelppemb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bqwelppemb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bqwelppemb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bqwelppemb .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"(Intercept)\">(Intercept)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"weight_c\">weight_c</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sigma\">sigma</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"(Intercept)\" class=\"gt_row gt_right\">155.1</td>\n<td headers=\"weight_c\" class=\"gt_row gt_right\">0.9</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">5.0</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"(Intercept)\" class=\"gt_row gt_right\">155.5</td>\n<td headers=\"weight_c\" class=\"gt_row gt_right\">0.8</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">5.1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"(Intercept)\" class=\"gt_row gt_right\">155.5</td>\n<td headers=\"weight_c\" class=\"gt_row gt_right\">0.9</td>\n<td headers=\"sigma\" class=\"gt_row gt_right\">5.1</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nHier sind die Zusammenfassungen der Stichproben aus der Post-Verteilung, komfortabel zu erhalten mit dem Befehle `parameters`:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-4_692b288a50f61cd6007b806a2c29e30d'}\n\n```{.r .cell-code}\nparameters(m43a)\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-5_33d398df0ff2f9f613c5a4b306239071'}\n::: {.cell-output-display}\n|Parameter   | Median |           95% CI |   pd |  Rhat |     ESS |              Prior |\n|:-----------|:------:|:----------------:|:----:|:-----:|:-------:|:------------------:|\n|(Intercept) | 154.65 | (154.14, 155.19) | 100% | 0.999 | 3214.00 | Normal (178 +- 20) |\n|weight_c    |   0.91 |     (0.82, 0.99) | 100% | 1.001 | 4134.00 |    Normal (5 +- 3) |\n:::\n:::\n\n\n\n\n::: {#def-pd}\n\n## Effektwahrscheinlichkeit\n\nDie Kennzahl  `pd` (propability of direction) gibt die *Effektwahrscheinlichkeit* an: Die Wahrscheinlichkeit,\ndass der Effekt positiv (also größer als Null) oder negativ ist (je nachdem ob der Median des Effekts positiv oder negativ ist).\n`pd` gibt aber nicht an, wie stark der Effekt ist, nur ob er klar auf einer Seite der Null liegt.\nDamit ist er so etwas (grob!) Ähnliches wie der p-Wert in der Frequentistischen Statistik [@makowski_indices_2019].\n\n:::\n\n\nAm besten das Diagramm dazu anschauen, s @fig-pd1.\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-pd1_ed13644438a80c743a4dc3f066c430b3'}\n\n```{.r .cell-code}\nplot(p_direction(m43a))\n```\n\n::: {.cell-output-display}\n![Diagramm zur Probability of Direction, Modell m43a](0900-lineare-modelle_files/figure-html/fig-pd1-1.png){#fig-pd1 width=672}\n:::\n:::\n\n\n\n\n`Rhat` und `ESS` sind Kennzahlen, die untersuchen, ob mit der Stichprobenziehung im Bayes-Modell alles gut funktioniert hat. Bei einfachen Modellen (die wir hier berechnen) sollte da in der Regel alles in Ordnung sein.\n`Rhat` sollte nicht (viel) größer als 1 oder 1,01 sein. `ESS` (effective sample size) gibt die Anzahl der effektiv nutzbaren Stichproben an (im Standard werden 4000 berechnet). Die Zahl sollte nicht deutlich geringer sein.\n\nWir werden uns aber mit diesen beiden Kennwerten nicht weiter beschäftigen in diesem Kurs.\n\n\n### Visualisieren der \"mittleren\" Regressiongeraden\n\n\n\nZur Erinnerung: Die Bayes-Analyse liefert uns viele Stichproben zu den gesuchten Parametern,\nhier $\\beta_0$, $\\beta_1$ und $\\sigma$.\nÜberzeugen wir uns mit einem Blick in die Post-Verteilung von `m43a`:\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-19_c0baaf315173d844205e408f8ab0c157'}\n\n```{.r .cell-code}\nm43a %>% \n  as_tibble() %>% \n  head()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| (Intercept)|  weight_c|    sigma|\n|-----------:|---------:|--------:|\n|    155.1421| 0.8581434| 5.042898|\n|    155.4658| 0.8348727| 5.071101|\n|    155.4522| 0.8549260| 5.144382|\n|    155.2342| 0.8816371| 5.352756|\n|    155.3172| 0.8745051| 5.349856|\n|    154.9315| 0.9030495| 5.207581|\n\n</div>\n:::\n:::\n\n\nWir können z.B. ein Lagemaß wie den Median hernehmen, um die \"mittlere\" Regressionsgerade zu betrachten:\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-6_f5ff26a9197a7ed8c2da550a16c8dc23'}\n\n```{.r .cell-code}\nd3 %>% \n  ggplot() +\n  aes(x = weight_c, y = height) +\n  geom_point() +\n  geom_abline(\n    slope = 0.9,  # Median beta 1\n    intercept = 154,  # Median beta 0\n    color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/Post-Regression-befragen-6-1.png){width=672}\n:::\n:::\n\n\nEinfacher ist die Syntax vielleicht, wenn man die Funktion `estimate_expectation` benutzt, s. @fig-expect-m43a.\nMit \"expectation\" sind hier die erwarteten Werte, also die Regressionsgerade, gemeint.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-expect-m43a_456a71f19bb237c9dffe9fd674c58dea'}\n\n```{.r .cell-code}\nm43_expect <- estimate_expectation(m43a)\nplot(m43_expect)\n```\n\n::: {.cell-output-display}\n![Erwartete Werte des Modell m43a, sprich, die Regressionsgerade](0900-lineare-modelle_files/figure-html/fig-expect-m43a-1.png){#fig-expect-m43a width=672}\n:::\n:::\n\n\n\n\n\n### Zentrale Statistiken zu den Parametern\n\nIn diesem Modell gibt es drei Parameter: $\\alpha, \\beta, \\sigma$.\n\nHier folgen einige Beispiele an Fragen, die wir an unser Modell bzw. die Post-Verteilung stellen können.\n\n\n#### Lagemaße zu den Parametern\n\n- Was ist die mittlere Größe einer !Kung-Person? ($\\beta_0$)\n- Was ist der Schätzwert für den Zusammenhang von Gewicht und Größe? ($\\beta_1$)\n- Was ist der Schätzwert für Ungewissheit in der Schätzung der Größe? ($\\sigma$)\n- Was ist der wahrscheinlichste Wert für z.B: $\\beta_1$?\n\n\nEine nützliche Zusammenfassung der Post-Verteilung bekommt man mit `parameters(modell)`:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-7_8e109ce59da9c440e33720f4c9cf92e0'}\n\n```{.r .cell-code}\nm43a %>% \n  parameters()\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-7a_aa5dc3cba5887b793ca830d9d19a0db3'}\n::: {.cell-output-display}\n|Parameter   | Median |           95% CI |   pd |  Rhat |     ESS |              Prior |\n|:-----------|:------:|:----------------:|:----:|:-----:|:-------:|:------------------:|\n|(Intercept) | 154.65 | (154.14, 155.19) | 100% | 0.999 | 3214.00 | Normal (178 +- 20) |\n|weight_c    |   0.91 |     (0.82, 0.99) | 100% | 1.001 | 4134.00 |    Normal (5 +- 3) |\n:::\n:::\n\n\n\nWandelt man das Ausgabe-Objekt der Bayes-Regression, d.h. `m43a`, mit `as_tibble()` in eine Tabelle um,\nso bekommt man eine Tabelle mit den Stichproben der Post-Verteilung:\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-21_c8fdbd41a677edfd98869dac3726368a'}\n\n```{.r .cell-code}\nm43a_post <- \n  m43a %>% \n  as_tibble()\n\nm43a_post %>% \n  head()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| (Intercept)|  weight_c|    sigma|\n|-----------:|---------:|--------:|\n|    155.1421| 0.8581434| 5.042898|\n|    155.4658| 0.8348727| 5.071101|\n|    155.4522| 0.8549260| 5.144382|\n|    155.2342| 0.8816371| 5.352756|\n|    155.3172| 0.8745051| 5.349856|\n|    154.9315| 0.9030495| 5.207581|\n\n</div>\n:::\n:::\n\n\n\nWie wir gesehen haben, nutzen wir diese Tabelle der Post-Verteilung immer wieder.\nSpeichern wir uns sie also als ein Objekt ab, `m43_post`.\n\n\nJetzt haben wir wieder eine schöne Tabelle mit Stichproben aus der Post-Verteilung,\ndie wir wie gewohnt befragen können.\n\n\n\nEine Visualisierung zeigt gut sowohl Lage- als auch Streuungsmaße der Parameter, zumindest grob.,\n\n\n\n\n\nOder man erstellt selber ein Diagramm mit `ggplot`.\n\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-22_3837a55781dfe38a36ba261a98cd5245'}\n\n```{.r .cell-code}\nm43a_post %>% \n  ggplot(aes(x = weight_c)) +\n  geom_density(fill = \"orange\")\n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\nDas Diagramm zeigt, dass Mittelwert, Median und Modus eng zusammenliegen.\nZur Erinnerung: Der Modus gibt den häufigsten, d.h. hier also den wahrscheinlichsten, Wert an.\n\nDer Modus wird hier auch *Maximum a Posteriori* (MAP) genannt, daher:\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/map-estimate-m43a_156657b84c6dce7be7bb9581d47e65b1'}\n\n```{.r .cell-code}\nm43a_post %>% \n  summarise(map_b1 = map_estimate(weight_c))\n```\n:::\n\n\n\n\n\n\nHier ist die Verteilung von $\\sigma$ visualisiert, s. @fig-m43a-post.\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-m43a-post_42b5c03a3e1f8b300558a6927fafa5b1'}\n\n```{.r .cell-code}\nm43a_post %>% \n  ggplot(aes(x = sigma)) +\n  geom_density(fill = \"orange\")\n```\n\n::: {.cell-output-display}\n![Die Post-Verteilung für den Parameter sigma, m43a](0900-lineare-modelle_files/figure-html/fig-m43a-post-1.png){#fig-m43a-post width=672}\n:::\n:::\n\n\n\nAlternativ kann man sich die Verteilung eines Parameters auch so ausgeben lassen,\ngleich mit Intervallgrenzen, z.B. 95%, s.@fig-m43a-plot.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-m43a-plot_908283741499569c3148ef6d974bd3dd'}\n\n```{.r .cell-code}\nm43a_hdi <- hdi(m43a_post)  # analog mit eti(m43a)\n\nplot(m43a_hdi)\n```\n\n::: {.cell-output-display}\n![Die Parameter Gewicht (zentriert) und sigma des Modells m43a](0900-lineare-modelle_files/figure-html/fig-m43a-plot-1.png){#fig-m43a-plot width=672}\n:::\n:::\n\n\nErgänzt man bei `plot()` noch `show_intercept = TRUE` wird auch der Achsenabschnitt angezeigt.\n\n\n\n\n\n### Streuungsmaße zu den Parametern\n\n\n- Wie unsicher sind wir uns in den Schätzungen der Parameter?\n\n\n\nDiese Frage wird durch die Ungewissheitsintervalle in der Ausgabe beantwortet.\n\n\n:::callout-note\nAn einigen Stellen wird empfohlen, anstelle eines (gebräuchlichen) 95%-Intervalls \nauf ein 90%- oder 89%-Intervall auszuweichen, aufgrund der besseren numerischen Stabilität.\n:::\n\n\n### Ungewissheit von $\\alpha$ und $\\beta$ aus der Post-Verteilung visualisiert\n\n\n\nDie ersten 10 Stichproben:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-10_3ba1a6dce937cb7ddb735173681f52e2'}\n\n```{.r .cell-code}\nd3 %>% \n  ggplot(aes(x = weight_c, \n             y = height)) +\n  geom_point() +\n  geom_abline(\n    data = m43a_post %>% \n      slice_head(n = 10),\n    aes(slope = weight_c,\n        intercept = `(Intercept)`),\n    alpha = .3)\n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/Post-Regression-befragen-10-1.png){width=672}\n:::\n:::\n\n\n\nDie ersten 100 Stichproben:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-11-ersten-1000_ec27beb4411b03644785ab5a0ae617ba'}\n\n```{.r .cell-code}\nd3 %>% \n  ggplot(aes(x = weight_c, \n             y = height)) +\n  geom_point() +\n  geom_abline(\n    data = m43a_post %>% \n      slice_head(n = 100),\n     aes(slope = weight_c,\n        intercept = `(Intercept)`),\n    alpha = .1)\n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/Post-Regression-befragen-11-ersten-1000-1.png){width=672}\n:::\n:::\n\n\n\nDie ersten `1e3` Stichproben:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-11-die-ersten-1000_f0929978fd25c3237c636c177717e2b4'}\n\n```{.r .cell-code}\nd3 %>% \n  ggplot(aes(x = weight_c, \n             y = height)) +\n  geom_point() +\n  geom_abline(\n    data = m43a_post %>% \n      slice_head(n = 1e3),\n     aes(slope = weight_c,\n        intercept = `(Intercept)`),\n    alpha = .01)\n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/Post-Regression-befragen-11-die-ersten-1000-1.png){width=672}\n:::\n:::\n\n\n\n\n\nDie ersten 1000000 ... okay, lassen wir es gut sein^[Im Standard beschert uns `stan_glm()` 4000 Stichproben.].\n\n\n\nEinfacher ist die Visualisierung mit `estimate_expectation`:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-25_44fd896261b2a0e5903d26d82572c595'}\n\n```{.r .cell-code}\nestimate_expectation(m43a, seed = 42) %>% plot()\n```\n\n::: {.cell-output-display}\n![](0900-lineare-modelle_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n### Fragen zu Quantilen des Achsenabschnitts \n\n:::callout-note\nZur Erinnerung: Bei einem zentrierten Prädiktor misst der Achsenabschnitt die mittlere Größe.\n:::\n\n- Welche mittlere Größe wird mit zu 50%, 90% bzw. 95% Wahrscheinlichkeit nicht überschritten?\n- Welche mittlere Größe mit zu 95% Wskt. nicht unterschritten?\n- Von wo bis wo reicht der innere 50%-Schätzbereich der mittleren Größe?\n\n\n\nQuantile:\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/quantile-post_1a61250b05e306fe6c661c2edc5e4799'}\n\n```{.r .cell-code}\nm43a_post %>% \n  summarise(\n    q_50 = quantile(`(Intercept)`, prob = .5),\n    q_90 = quantile(`(Intercept)`, prob = .9),\n    q_05 = quantile(`(Intercept)`, prob = .95))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     q_50|     q_90|     q_05|\n|--------:|--------:|--------:|\n| 154.6548| 155.0032| 155.0951|\n\n</div>\n:::\n:::\n\n\n50%-PI:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-26_7f6b88e61804f897fa750fb587d87831'}\n\n```{.r .cell-code}\nm43a %>% \n  eti(ci = .5)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   |  CI|      CI_low|     CI_high|Effects |Component   |\n|:-----------|---:|-----------:|-----------:|:-------|:-----------|\n|(Intercept) | 0.5| 154.4632928| 154.8373635|fixed   |conditional |\n|weight_c    | 0.5|   0.8772824|   0.9354291|fixed   |conditional |\n\n</div>\n:::\n:::\n\n\n\n\n### Fragen zu Wahrscheinlichkeitsmassen des Achsenabschnitts \n\n\n\nWie wahrscheinlich ist es, dass die mittlere Größe bei mind. 155 cm liegt?\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-27_db8303b42911d1ef5e540d7c16b4172d'}\n\n```{.r .cell-code}\nm43a_post %>% \n  count(gross = `(Intercept)` >= 155) %>% \n  mutate(prop = n / sum(n))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|gross |    n|    prop|\n|:-----|----:|-------:|\n|FALSE | 3593| 0.89825|\n|TRUE  |  407| 0.10175|\n\n</div>\n:::\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-28_55efdbdb6f390511893033bbff62b5bf'}\n\n:::\n\n\nDie Wahrscheinlichkeit beträgt 0.1.\n\n\nWie wahrscheinlich ist es, dass die mittlere Größe höchstens 154.5 cm beträgt?\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-29_ac73d0acbd2def949d06f2f93a6043ca'}\n\n```{.r .cell-code}\nm43a_post %>% \n  count(klein = (`(Intercept)` <= 154.5)) %>% \n  mutate(prop = n / sum(n))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|klein |    n|    prop|\n|:-----|----:|-------:|\n|FALSE | 2833| 0.70825|\n|TRUE  | 1167| 0.29175|\n\n</div>\n:::\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/wsktklein_337b54c5e9c6ec3895f9f82b26e34b92'}\n\n:::\n\n\n\nDie Wahrscheinlichkeit beträgt 0.29.\n\n\n\n\n\n\n<!-- ### Ungewissheit von Achsenabschnitt und Steigung  -->\n\n<!-- ... als Histogramme visualisiert -->\n\n<!--  -->\n\n<!-- ### Achsenabschnitt -->\n\n<!-- ```{r Post-Regression-befragen-13, echo = TRUE, eval = TRUE} -->\n<!-- post_m43a %>%  -->\n<!--   ggplot(aes(x = a)) + -->\n<!--   geom_density() -->\n<!-- ``` -->\n\n<!-- ] -->\n\n<!-- .pull-right[ -->\n\n<!-- ### Regressionsgewicht (Steigung) -->\n\n<!-- ```{r Post-Regression-befragen-14, echo = TRUE} -->\n<!-- post_m43a %>%  -->\n<!--   ggplot(aes(x = b)) + -->\n<!--   geom_density() -->\n<!-- ``` -->\n‚\n<!-- ] -->\n\n\n\n### Typischer Bayes-Nutzer in Aktion\n\n![Typischer Bayes-Nutzer, der ein Ungewissheitsintervall berechnet. Bildquelle: Easystats, bayestestR](img/bayesianMaster.jpg){width=\"50%\" fig-align=\"center\"}\n\n[Quelle](https://easystats.github.io/bayestestR/articles/bayestestR.html)\n\n\n\n\n\n## Post-Verteilung bedingt auf einen Prädiktorwert\n\n\n### Visualisierung\n\n\nWas ist wohl die Wahrscheinlichkeit der Körpergröße bei einem bestimmten Gewicht?\n\nAngenommen wir wissen, dass das Gewicht bei, sagen wir 45 kg liegt.\nWelche Körpergröße ist (im Schnitt) zu erwarten? Wie unsicher sind wir uns über diesen Mittelwert?\n\nEtwas formaler ausgedrückt:\n\n$\\mu|\\text{weight}=45$\n\n\n45 kg entspricht genau dem Mittelwert von `weight`. Geht man von zentrierten Prädiktorwerten aus, gilt in dem Fall `weight_c = 0`.\nErstellen wir uns dazu eine Tabelle:\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/mu-at-45-def_c9c9f5de26fa1818cafd9595afb7cee9'}\n\n```{.r .cell-code}\nmu_at_45 <-\n  m43a_post %>% \n  mutate(mu_at_45 = `(Intercept)`)\n```\n:::\n\n\nUnd plotten diese, s. @fig-mu-at-45.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-15_8309790d4c87ddf1d89cdbdadb37015d'}\n\n```{.r .cell-code}\nmu_at_45 %>% \n  ggplot(aes(x = mu_at_45)) +\n  geom_density()\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-mu-at-45_055e6a18f688a9465c7193d0a9edef97'}\n::: {.cell-output-display}\n![Post-Verteilung der Größe (laut unserem Modell) bei einem Gewicht von 45kg](0900-lineare-modelle_files/figure-html/fig-mu-at-45-1.png){#fig-mu-at-45 width=672}\n:::\n:::\n\n\n\nAnalog können wir fragen,\nwie groß wohl eine Person mit 50 kg im Mittelwert sein wird und wie (un)gewiss wir uns über diesen Mittelwert sind.\n\n\n50 kg, das sind 5 über dem Mittelwert, in zentrierten Einheiten ausgedrückt also `weight_c = 5`. Auch dazu erstellen wir uns eine Tabelle.\n\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/mu-at-50_48d34ef04f356147d454c4cf60ae6a0a'}\n\n```{.r .cell-code}\nmu_at_50 <-\n  mu_at_45 %>% \n  mutate(mu_at_50 = `(Intercept)` + 5 * weight_c)\n\nhead(mu_at_50)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| (Intercept)|  weight_c|    sigma| mu_at_45| mu_at_50|\n|-----------:|---------:|--------:|--------:|--------:|\n|    155.1421| 0.8581434| 5.042898| 155.1421| 159.4329|\n|    155.4658| 0.8348727| 5.071101| 155.4658| 159.6402|\n|    155.4522| 0.8549260| 5.144382| 155.4522| 159.7269|\n|    155.2342| 0.8816371| 5.352756| 155.2342| 159.6424|\n|    155.3172| 0.8745051| 5.349856| 155.3172| 159.6897|\n|    154.9315| 0.9030495| 5.207581| 154.9315| 159.4467|\n\n</div>\n:::\n:::\n\n\nDie Verteilung der mittleren Größe bei einem Gewicht von 50kg ist weiter \"rechts\" (Richtung höhere Größe) zentriert, s. @fig-mu-at-50.\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-16_8d13e964f5c65dcba3f1c94545603aec'}\n\n```{.r .cell-code}\nmu_at_50 %>% \n  ggplot(aes(x = mu_at_50)) +\n  geom_density()\n```\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-mu-at-50_44d03760649566277a08cd2b3381ec57'}\n::: {.cell-output-display}\n![Post-Verteilung der mittleren Größe (laut unserem Modell) bedingt auf ein Gewicht von 50 kg](0900-lineare-modelle_files/figure-html/fig-mu-at-50-1.png){#fig-mu-at-50 width=672}\n:::\n:::\n\n\n\n\n\n### Lagemaße und Streuungen\n\nBefragen wir die bedingte Post-Verteilung. Eine erste Frage zielt nach den typischen deskriptiven Statistiken, also nach Lage und Streuung der Verteilung der Körpergröße.\n\n\n\n\nWas ist das 90% PI für $\\mu|w=50$ ?\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-19_687d3a45a8a9ec203296f6bb7480841a'}\n\n```{.r .cell-code}\nmu_at_50 %>% \n  eti(mu_at_50, ci = .9)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   |  CI|      CI_low|     CI_high|\n|:-----------|---:|-----------:|-----------:|\n|(Intercept) | 0.9| 154.2144131| 155.0950875|\n|weight_c    | 0.9|   0.8358413|   0.9763181|\n|sigma       | 0.9|   4.8298399|   5.4758137|\n|mu_at_45    | 0.9| 154.2144131| 155.0950875|\n|mu_at_50    | 0.9| 158.6294638| 159.7578370|\n\n</div>\n:::\n:::\n\n\nDie mittlere Größe - gegeben $w=50$ - liegt mit 90% Wahrscheinlichkeit zwischen den beiden Werten (ca.) 159cm und 160cm.\n\n\n\nWelche mittlere Größe wird mit 95% Wahrscheinlichkeit nicht überschritten, wenn die Person 45kg wiegt?\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-20_d2c8c2f24ddb3dc8e639bc9487866738'}\n\n```{.r .cell-code}\nmu_at_45 %>% \n  summarise(q_95 = quantile(mu_at_45, prob = .95))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     q_95|\n|--------:|\n| 155.0951|\n\n</div>\n:::\n:::\n\n\n\n\n\n## Die PPV befragen\n\n\n\n\n\n\n\n\nDie Posterior-Prädiktiv-Verteilung (PPV) gibt uns die Möglichkeit,\nnach der Wahrscheinlichkeit *tatsächlicher* Körpergrößen zu fragen - \nund nicht nur nach *mittleren* Körpergrößen anhand der Post-Verteilung.\n\n\n:::callout-important\nDie Post-Verteilung macht *nur* Aussagen zur *mittleren* Körpergröße,\ndenn das ist was wir modellieren wollten.\nMöchten wir Aussagen zur Wahrscheinlichkeit *tatsächlicher* Größen treffen,\nbrauchen wir die PPV.\nAllgemeiner gesagt: Die PPV macht Vorhersagen auf Basis eines Modells. \nFür jede Vorhersage gibt es eine Verteilung, \ndie wir zu einem Punktschätzer (z.B. Median) und einem Schätzbereich (z.B. 89%-HDI) zusammenfassen können.\n:::\n\nAn dieser Stelle sollten wir uns vor Augen führen, dass die PPV *mehr* Ungewissheit beinhaltet,\ndenn sie berücksichtigt derer zweier Arten:\n\n1. Ungewissheit bzgl. der Modellparameter (Steigung und Achsenabschnitt der Regressionsgeraden)\n2. Ungewissheit der Vorhersagen (das Modell macht keine perfekten Vorhersagen)\n\n\nDie *Post-Verteilung* berücksichtigt nur die Ungewissheit in den Modellparametern,\nmacht also nur Aussagen zur Regressionsgeraden.\n\nDie PPV macht Aussagen für konkrete Beobachtungen.\nDer Unterschied ist in @fig-ppv-vs-post dargestellt; die Funktionen stammen übrigens aus `{easystats}`.\n\n\n\n::: {#fig-ppv-vs-post .cell layout-ncol=\"2\" hash='0900-lineare-modelle_cache/html/fig-ppv-vs-post_ea3d328192897bf1d55f7db2b4f83e04'}\n\n```{.r .cell-code}\nestimate_prediction(m43a) %>% plot()\nestimate_relation(m43a) %>% plot()\n```\n\n::: {.cell-output-display}\n![PPV mit viel Ungewissheit](0900-lineare-modelle_files/figure-html/fig-ppv-vs-post-1.png){#fig-ppv-vs-post-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Post-Verteilung mit wenig(er) Ungewissheit](0900-lineare-modelle_files/figure-html/fig-ppv-vs-post-2.png){#fig-ppv-vs-post-2 width=672}\n:::\n\nPPV vs. Post-Verteilung\n:::\n\n\n\n### Perzentil-Intervalle für bestimmte Prädiktor-Werte\n\n\n\n>    Wie groß ist ein !Kung-Mann mit mittlerem Gewicht?\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-31_823c2730c8a576935c43b4be8dec2b76'}\n\n```{.r .cell-code}\nset.seed(42)\nestimate_prediction(m43a, data = tibble(weight_c = 0), seed = 42)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| weight_c| Predicted|       SE|   CI_low|  CI_high|\n|--------:|---------:|--------:|--------:|--------:|\n|        0|  154.5787| 5.162584| 144.2798| 164.5835|\n\n</div>\n:::\n:::\n\n\nUnser Modell, `ma43a` schätzt ca. 145cm bis 165cm.\n\n\nWir können uns auch eine Sequenz an Prädiktorwerten, die uns interessieren, erstellen, s. `weight_df`:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-32_96b23e046d4a4d53ea382bfb7fdbad98'}\n\n```{.r .cell-code}\nweight_df <- tibble(weight_c = seq(-20,20, by = 5))\n```\n:::\n\n\n\nFür diese Werte lassen wir uns dann die Perzentil-Intervalle (PI) ausgeben:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-21_0da7a2ed022e8935a146d235e106ceb4'}\n\n```{.r .cell-code}\nmus <- \n  estimate_prediction(m43a, data = weight_df) \n\nhead(mus)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| weight_c| Predicted|       SE|   CI_low|  CI_high|\n|--------:|---------:|--------:|--------:|--------:|\n|      -20|  136.5669| 5.371291| 125.8810| 147.3205|\n|      -15|  141.0826| 5.250343| 130.6368| 151.1919|\n|      -10|  145.7617| 5.144039| 135.5270| 155.5853|\n|       -5|  150.0022| 5.174693| 139.5637| 159.9117|\n|        0|  154.5556| 5.178200| 144.5177| 164.8595|\n|        5|  159.2914| 5.138765| 149.2243| 169.2083|\n\n</div>\n:::\n:::\n\n\nUm die Perzentilintervalle zu erstellen, wird von `estimate_prediction()` für jeden Prädiktorwert eine PPV erstellt und (in der Voreinstellung) das 5%- sowie 95%-Quantil dafür berechnet. \nSie können die Voreinstellung ändern mittels des Arguments `ci`;\num ein 89%-PI zu berechnen, würde man z.B. schreiben `ci = .89`.\n\nUm Reproduzierbarkeit sicherzustellen,\nhaben wir mit `set.seed(42)` die Zufallszahlen fixiert.\n\n\nHoppla! Das ist ja viel ungenauer, als die Angaben der Post-Verteilung oben.\nJa, denn die Post-Verteilung hat die Ungewissheit zum *Mittelwert* ausgedrückt;\ndie PPV gibt die Ungewissheit *tatsächlicher* beobachtbarer Körpergrößen aus,\nnicht nur die Ungewissheit zum Mittelwert.\n\n\nBerechnen wir die PPV für die bestehenden Beobachtungen aus `m43a`:\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/ppv-m43a_fcfff62ce3e14edfdc5ffeeaf59e8d69'}\n\n```{.r .cell-code}\nppv_m43a <- estimate_prediction(\n  m43a,\n  data = weight_df)\n\nmus \n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| weight_c| Predicted|       SE|   CI_low|  CI_high|\n|--------:|---------:|--------:|--------:|--------:|\n|      -20|  136.5669| 5.371291| 125.8810| 147.3205|\n|      -15|  141.0826| 5.250343| 130.6368| 151.1919|\n|      -10|  145.7617| 5.144039| 135.5270| 155.5853|\n|       -5|  150.0022| 5.174693| 139.5637| 159.9117|\n|        0|  154.5556| 5.178200| 144.5177| 164.8595|\n|        5|  159.2914| 5.138765| 149.2243| 169.2083|\n|       10|  163.6660| 5.220188| 153.4377| 174.0912|\n|       15|  168.2456| 5.249081| 158.2699| 178.4302|\n|       20|  172.7290| 5.322229| 162.4394| 183.2873|\n\n</div>\n:::\n:::\n\n\n\n\n\n\n\n### Perzentilintervalle für verschiedenen Prädiktorwerte visualisiert\n\n@fig-m43a-nochmal visualisiert die Ungewissheit von Vorhersagen laut der PPV.\nDie Ungewissheit in @fig-m43a-nochmal ist die Antwort auf die Frage: \"Wie sicher sind wir uns,\nzur Größe einer !Kung-Person, gegeben dass die z.B. 10 kg mehr als der Durchschnitt wiegt?\"\nEine Vorhersage bezeichnet man auch als \"bedingte Verteilung\", da man den Wert einer Verteilung voraussagt,\n*gegeben* einer Bedingung, z.B. `weight_c = 10`.  \n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-m43a-nochmal_604fb48b14fcba6e186c93d537e95395'}\n::: {.cell-output-display}\n![Visualisierung der Ungewissheit der Vorhersagen laut PPV: Die Vorhersage von Beobachtungen beinhaltet mehr Ungewissheit als die Vorhersage von zu erwartenden Werten, daher sind die Ungewissheitsintervalle der PPV größer als die der Post-Verteilung.](0900-lineare-modelle_files/figure-html/fig-m43a-nochmal-1.png){#fig-m43a-nochmal width=672}\n:::\n:::\n\n\n\nDie vertikalen Balken geben die 95%-KI wieder, die wir jeweils zu erwarten haben.\n\nNoch eine andere Visualisierung, s. @fig-katzenaugen; \nje dicker die \"Katzenaugen\", desto mehr Stichproben (samples) liegen vor an der Stelle,\nund umso genauer ist die Schätzung.\n\n\n\n::: {.cell layout-ncol=\"2\" hash='0900-lineare-modelle_cache/html/fig-katzenaugen_523fd233c45023978c39dd8c02b46c7c'}\n::: {.cell-output-display}\n![Die PPV für bestimmte Gewichtswerte w, visualisiert mit Katzenaugen-Diagrammen](0900-lineare-modelle_files/figure-html/fig-katzenaugen-1.png){#fig-katzenaugen width=672}\n:::\n:::\n\n\n\nAlso: Je dicker die Violine, desto wahrscheinlicher $\\mu | w_i$.\n\n\n\n### Die PPV über alle Beobachtungen visualisiert\n\nGerade eben haben wir *bedingte* PPVen angeschaut: Also eine PPV für einen *bestimmten* Prädiktorwert, z.B. bei einer Person mittleren Gewichts.\nWir können auch den Mittelwert über alle bedingten PPV anschauen, sozusagen die \"*Master-PPV*\" oder \"unbedingte PPV\" oder schlicht PPV.\nVergleichen wir die echten Werte für `height`, $y$, mit den von der PPV simulierten Werten für `height`, $y_{rep}$, s. @fig-ppv-check.\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/fig-ppv-check_dd5ceea9399a85bbe6036c21ed86b0a3'}\n\n```{.r .cell-code}\ncheck_predictions(m43a)  # aus easystatss\n```\n\n::: {.cell-output-display}\n![Vergleich der Vorhersagen für y (leichte, blaue Linien) mit der beobachteten Verteilung von y](0900-lineare-modelle_files/figure-html/fig-ppv-check-1.png){#fig-ppv-check width=672}\n:::\n:::\n\n\n`?check_predictions` zeigt Hilfe für diese Funktion. \nDie Funktion zeigt die Vorhersagen für die AV laut der Posteriori-Verteilung.\n\n\n\nDie zwei Gipfel hat unser Modell nicht mitgekriegt, \nansonsten decken sich die Vorhersagen der PPV gut mit den echten Daten.\n\n\n\n\n\n\n\n\n### Fragen an die Master-PPV\n\n- Wie groß sind die !Kung im Schnitt?\n- Welche Größe wird von 90% der Personen nicht überschritten?\n- Wie groß sind die 10% kleinsten?\n\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-33_1af1f8634d982e7d7f0db4f42214b49f'}\n\n```{.r .cell-code}\nppv_m43a <- posterior_predict(\n  m43a,\n  newdata = weight_df,\n  draws = 100) %>% \n  as_tibble() %>% \n  pivot_longer(\n    cols = everything(),\n    names_to = \"weight_condition\",\n    values_to = \"height\")\nhead(ppv_m43a)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|weight_condition |   height|\n|:----------------|--------:|\n|1                | 132.5265|\n|2                | 136.7188|\n|3                | 147.7576|\n|4                | 143.1540|\n|5                | 156.0412|\n|6                | 157.4500|\n\n</div>\n:::\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/unnamed-chunk-34_20e7bce688854713e96982651e37aa59'}\n\n```{.r .cell-code}\nppv_m43a <-\n  ppv_m43a <- posterior_predict(\n  m43a,\n  newdata = weight_df,\n  draws = 100) %>% \n  as_tibble() %>% \n  pivot_longer(\n    cols = everything(),\n    names_to = \"weight_condition\",\n    values_to = \"height\")\n\nhead(ppv_m43a)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|weight_condition |   height|\n|:----------------|--------:|\n|1                | 144.0829|\n|2                | 144.6354|\n|3                | 141.7168|\n|4                | 153.3734|\n|5                | 153.9631|\n|6                | 157.1561|\n\n</div>\n:::\n:::\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-29_a9a3cf372ef9acae23680bbfbe6d71e3'}\n\n```{.r .cell-code}\nppv_m43a %>% \n  summarise(\n    q_10 = quantile(height, prob = .1),\n    height_mean = mean(height),\n    q_50 = quantile(height, prob = .5),\n    q_90 = quantile(height, prob = .9)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     q_10| height_mean|     q_50|     q_90|\n|--------:|-----------:|--------:|--------:|\n| 137.6442|    154.7309| 154.7682| 171.8652|\n\n</div>\n:::\n:::\n\n\n\nWas ist der 50% Bereich der Körpergröße?\n\n\n::: {.cell hash='0900-lineare-modelle_cache/html/Post-Regression-befragen-30_0312e4b72526eeaf3548a4ab2d4b616d'}\n\n```{.r .cell-code}\nppv_m43a %>% \n  eti(ci = .5)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter |  CI|   CI_low|  CI_high|\n|:---------|---:|--------:|--------:|\n|height    | 0.5| 144.9652| 165.2586|\n\n</div>\n:::\n:::\n\n\n\n## Aufgaben\n\n\n\n- [Bayes-Ziel1](https://datenwerk.netlify.app/posts/bayes-ziel1/bayes-ziel1)\n- [Bayesmod-bestimmen01](https://datenwerk.netlify.app/posts/bayesmod-bestimmen01/bayesmod-bestimmen01)\n- [Likelihood2](https://datenwerk.netlify.app/posts/likelihood2/likelihood2)\n- [Post-befragen1](https://datenwerk.netlify.app/posts/post-befragen1/post-befragen1)\n- [Postvert-Regr-01](https://datenwerk.netlify.app/posts/postvert-regr-01/postvert-regr-01)\n- [regression1a](https://datenwerk.netlify.app/posts/regression1a/regression1a.html)\n- [Regression2](https://datenwerk.netlify.app/posts/regression2/regression2)\n- [Bed-Post-Wskt1](https://datenwerk.netlify.app/posts/bed-post-wskt1/bed-post-wskt1)\n- [Priorwahl1](https://datenwerk.netlify.app/posts/priorwahl1/priorwahl1)\n- [Bayesmod-bestimmen02\n](https://datenwerk.netlify.app/posts/bayesmod-bestimmen02/bayesmod-bestimmen02)\n- [Aussagen-einfache-Regr](https://datenwerk.netlify.app/posts/aussagen-einfache-regr/aussagen-einfache-regr)\n- [Likelihood-identifizieren](https://datenwerk.netlify.app/posts/likelihood-identifizieren/likelihood-identifizieren)\n- [Priorwahl2](https://datenwerk.netlify.app/posts/priorwahl2/priorwahl2)\n- [penguins-stan-01](https://datenwerk.netlify.app/posts/penguins-stan-01/penguins-stan-01.html)\n\n\n\n\n\n\n\n\n## ---\n\n\n\n![](img/outro-09.jpg){width=100%}\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}